// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.9
// 	protoc        v3.21.12
// source: workflow/v1/workflow.proto

package v1

import (
	_ "google.golang.org/genproto/googleapis/api/annotations"
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

// Request for executing a workflow
type ExecuteWorkflowRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	WorkflowType  string                 `protobuf:"bytes,1,opt,name=workflow_type,json=workflowType,proto3" json:"workflow_type,omitempty"`
	Parameters    map[string]string      `protobuf:"bytes,2,rep,name=parameters,proto3" json:"parameters,omitempty" protobuf_key:"bytes,1,opt,name=key" protobuf_val:"bytes,2,opt,name=value"`
	UserId        string                 `protobuf:"bytes,3,opt,name=user_id,json=userId,proto3" json:"user_id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ExecuteWorkflowRequest) Reset() {
	*x = ExecuteWorkflowRequest{}
	mi := &file_workflow_v1_workflow_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ExecuteWorkflowRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ExecuteWorkflowRequest) ProtoMessage() {}

func (x *ExecuteWorkflowRequest) ProtoReflect() protoreflect.Message {
	mi := &file_workflow_v1_workflow_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ExecuteWorkflowRequest.ProtoReflect.Descriptor instead.
func (*ExecuteWorkflowRequest) Descriptor() ([]byte, []int) {
	return file_workflow_v1_workflow_proto_rawDescGZIP(), []int{0}
}

func (x *ExecuteWorkflowRequest) GetWorkflowType() string {
	if x != nil {
		return x.WorkflowType
	}
	return ""
}

func (x *ExecuteWorkflowRequest) GetParameters() map[string]string {
	if x != nil {
		return x.Parameters
	}
	return nil
}

func (x *ExecuteWorkflowRequest) GetUserId() string {
	if x != nil {
		return x.UserId
	}
	return ""
}

// Reply for executing a workflow
type ExecuteWorkflowReply struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	ExecutionId   string                 `protobuf:"bytes,1,opt,name=execution_id,json=executionId,proto3" json:"execution_id,omitempty"`
	Status        string                 `protobuf:"bytes,2,opt,name=status,proto3" json:"status,omitempty"`
	Message       string                 `protobuf:"bytes,3,opt,name=message,proto3" json:"message,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ExecuteWorkflowReply) Reset() {
	*x = ExecuteWorkflowReply{}
	mi := &file_workflow_v1_workflow_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ExecuteWorkflowReply) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ExecuteWorkflowReply) ProtoMessage() {}

func (x *ExecuteWorkflowReply) ProtoReflect() protoreflect.Message {
	mi := &file_workflow_v1_workflow_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ExecuteWorkflowReply.ProtoReflect.Descriptor instead.
func (*ExecuteWorkflowReply) Descriptor() ([]byte, []int) {
	return file_workflow_v1_workflow_proto_rawDescGZIP(), []int{1}
}

func (x *ExecuteWorkflowReply) GetExecutionId() string {
	if x != nil {
		return x.ExecutionId
	}
	return ""
}

func (x *ExecuteWorkflowReply) GetStatus() string {
	if x != nil {
		return x.Status
	}
	return ""
}

func (x *ExecuteWorkflowReply) GetMessage() string {
	if x != nil {
		return x.Message
	}
	return ""
}

// Request for getting workflow status
type GetWorkflowStatusRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	ExecutionId   string                 `protobuf:"bytes,1,opt,name=execution_id,json=executionId,proto3" json:"execution_id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetWorkflowStatusRequest) Reset() {
	*x = GetWorkflowStatusRequest{}
	mi := &file_workflow_v1_workflow_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetWorkflowStatusRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetWorkflowStatusRequest) ProtoMessage() {}

func (x *GetWorkflowStatusRequest) ProtoReflect() protoreflect.Message {
	mi := &file_workflow_v1_workflow_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetWorkflowStatusRequest.ProtoReflect.Descriptor instead.
func (*GetWorkflowStatusRequest) Descriptor() ([]byte, []int) {
	return file_workflow_v1_workflow_proto_rawDescGZIP(), []int{2}
}

func (x *GetWorkflowStatusRequest) GetExecutionId() string {
	if x != nil {
		return x.ExecutionId
	}
	return ""
}

// Reply for getting workflow status
type GetWorkflowStatusReply struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	ExecutionId   string                 `protobuf:"bytes,1,opt,name=execution_id,json=executionId,proto3" json:"execution_id,omitempty"`
	Status        string                 `protobuf:"bytes,2,opt,name=status,proto3" json:"status,omitempty"`
	Result        string                 `protobuf:"bytes,3,opt,name=result,proto3" json:"result,omitempty"`
	ErrorMessage  string                 `protobuf:"bytes,4,opt,name=error_message,json=errorMessage,proto3" json:"error_message,omitempty"`
	CreatedAt     string                 `protobuf:"bytes,5,opt,name=created_at,json=createdAt,proto3" json:"created_at,omitempty"`
	UpdatedAt     string                 `protobuf:"bytes,6,opt,name=updated_at,json=updatedAt,proto3" json:"updated_at,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetWorkflowStatusReply) Reset() {
	*x = GetWorkflowStatusReply{}
	mi := &file_workflow_v1_workflow_proto_msgTypes[3]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetWorkflowStatusReply) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetWorkflowStatusReply) ProtoMessage() {}

func (x *GetWorkflowStatusReply) ProtoReflect() protoreflect.Message {
	mi := &file_workflow_v1_workflow_proto_msgTypes[3]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetWorkflowStatusReply.ProtoReflect.Descriptor instead.
func (*GetWorkflowStatusReply) Descriptor() ([]byte, []int) {
	return file_workflow_v1_workflow_proto_rawDescGZIP(), []int{3}
}

func (x *GetWorkflowStatusReply) GetExecutionId() string {
	if x != nil {
		return x.ExecutionId
	}
	return ""
}

func (x *GetWorkflowStatusReply) GetStatus() string {
	if x != nil {
		return x.Status
	}
	return ""
}

func (x *GetWorkflowStatusReply) GetResult() string {
	if x != nil {
		return x.Result
	}
	return ""
}

func (x *GetWorkflowStatusReply) GetErrorMessage() string {
	if x != nil {
		return x.ErrorMessage
	}
	return ""
}

func (x *GetWorkflowStatusReply) GetCreatedAt() string {
	if x != nil {
		return x.CreatedAt
	}
	return ""
}

func (x *GetWorkflowStatusReply) GetUpdatedAt() string {
	if x != nil {
		return x.UpdatedAt
	}
	return ""
}

// Request for listing workflow executions
type ListWorkflowExecutionsRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	UserId        string                 `protobuf:"bytes,1,opt,name=user_id,json=userId,proto3" json:"user_id,omitempty"`
	Page          int32                  `protobuf:"varint,2,opt,name=page,proto3" json:"page,omitempty"`
	PageSize      int32                  `protobuf:"varint,3,opt,name=page_size,json=pageSize,proto3" json:"page_size,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ListWorkflowExecutionsRequest) Reset() {
	*x = ListWorkflowExecutionsRequest{}
	mi := &file_workflow_v1_workflow_proto_msgTypes[4]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ListWorkflowExecutionsRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ListWorkflowExecutionsRequest) ProtoMessage() {}

func (x *ListWorkflowExecutionsRequest) ProtoReflect() protoreflect.Message {
	mi := &file_workflow_v1_workflow_proto_msgTypes[4]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ListWorkflowExecutionsRequest.ProtoReflect.Descriptor instead.
func (*ListWorkflowExecutionsRequest) Descriptor() ([]byte, []int) {
	return file_workflow_v1_workflow_proto_rawDescGZIP(), []int{4}
}

func (x *ListWorkflowExecutionsRequest) GetUserId() string {
	if x != nil {
		return x.UserId
	}
	return ""
}

func (x *ListWorkflowExecutionsRequest) GetPage() int32 {
	if x != nil {
		return x.Page
	}
	return 0
}

func (x *ListWorkflowExecutionsRequest) GetPageSize() int32 {
	if x != nil {
		return x.PageSize
	}
	return 0
}

// Reply for listing workflow executions
type ListWorkflowExecutionsReply struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Executions    []*WorkflowExecution   `protobuf:"bytes,1,rep,name=executions,proto3" json:"executions,omitempty"`
	Total         int32                  `protobuf:"varint,2,opt,name=total,proto3" json:"total,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ListWorkflowExecutionsReply) Reset() {
	*x = ListWorkflowExecutionsReply{}
	mi := &file_workflow_v1_workflow_proto_msgTypes[5]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ListWorkflowExecutionsReply) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ListWorkflowExecutionsReply) ProtoMessage() {}

func (x *ListWorkflowExecutionsReply) ProtoReflect() protoreflect.Message {
	mi := &file_workflow_v1_workflow_proto_msgTypes[5]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ListWorkflowExecutionsReply.ProtoReflect.Descriptor instead.
func (*ListWorkflowExecutionsReply) Descriptor() ([]byte, []int) {
	return file_workflow_v1_workflow_proto_rawDescGZIP(), []int{5}
}

func (x *ListWorkflowExecutionsReply) GetExecutions() []*WorkflowExecution {
	if x != nil {
		return x.Executions
	}
	return nil
}

func (x *ListWorkflowExecutionsReply) GetTotal() int32 {
	if x != nil {
		return x.Total
	}
	return 0
}

// Workflow execution structure
type WorkflowExecution struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Id            string                 `protobuf:"bytes,1,opt,name=id,proto3" json:"id,omitempty"`
	WorkflowType  string                 `protobuf:"bytes,2,opt,name=workflow_type,json=workflowType,proto3" json:"workflow_type,omitempty"`
	Status        string                 `protobuf:"bytes,3,opt,name=status,proto3" json:"status,omitempty"`
	UserId        string                 `protobuf:"bytes,4,opt,name=user_id,json=userId,proto3" json:"user_id,omitempty"`
	CreatedAt     string                 `protobuf:"bytes,5,opt,name=created_at,json=createdAt,proto3" json:"created_at,omitempty"`
	UpdatedAt     string                 `protobuf:"bytes,6,opt,name=updated_at,json=updatedAt,proto3" json:"updated_at,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *WorkflowExecution) Reset() {
	*x = WorkflowExecution{}
	mi := &file_workflow_v1_workflow_proto_msgTypes[6]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *WorkflowExecution) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*WorkflowExecution) ProtoMessage() {}

func (x *WorkflowExecution) ProtoReflect() protoreflect.Message {
	mi := &file_workflow_v1_workflow_proto_msgTypes[6]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use WorkflowExecution.ProtoReflect.Descriptor instead.
func (*WorkflowExecution) Descriptor() ([]byte, []int) {
	return file_workflow_v1_workflow_proto_rawDescGZIP(), []int{6}
}

func (x *WorkflowExecution) GetId() string {
	if x != nil {
		return x.Id
	}
	return ""
}

func (x *WorkflowExecution) GetWorkflowType() string {
	if x != nil {
		return x.WorkflowType
	}
	return ""
}

func (x *WorkflowExecution) GetStatus() string {
	if x != nil {
		return x.Status
	}
	return ""
}

func (x *WorkflowExecution) GetUserId() string {
	if x != nil {
		return x.UserId
	}
	return ""
}

func (x *WorkflowExecution) GetCreatedAt() string {
	if x != nil {
		return x.CreatedAt
	}
	return ""
}

func (x *WorkflowExecution) GetUpdatedAt() string {
	if x != nil {
		return x.UpdatedAt
	}
	return ""
}

var File_workflow_v1_workflow_proto protoreflect.FileDescriptor

const file_workflow_v1_workflow_proto_rawDesc = "" +
	"\n" +
	"\x1aworkflow/v1/workflow.proto\x12\vworkflow.v1\x1a\x1cgoogle/api/annotations.proto\"\xea\x01\n" +
	"\x16ExecuteWorkflowRequest\x12#\n" +
	"\rworkflow_type\x18\x01 \x01(\tR\fworkflowType\x12S\n" +
	"\n" +
	"parameters\x18\x02 \x03(\v23.workflow.v1.ExecuteWorkflowRequest.ParametersEntryR\n" +
	"parameters\x12\x17\n" +
	"\auser_id\x18\x03 \x01(\tR\x06userId\x1a=\n" +
	"\x0fParametersEntry\x12\x10\n" +
	"\x03key\x18\x01 \x01(\tR\x03key\x12\x14\n" +
	"\x05value\x18\x02 \x01(\tR\x05value:\x028\x01\"k\n" +
	"\x14ExecuteWorkflowReply\x12!\n" +
	"\fexecution_id\x18\x01 \x01(\tR\vexecutionId\x12\x16\n" +
	"\x06status\x18\x02 \x01(\tR\x06status\x12\x18\n" +
	"\amessage\x18\x03 \x01(\tR\amessage\"=\n" +
	"\x18GetWorkflowStatusRequest\x12!\n" +
	"\fexecution_id\x18\x01 \x01(\tR\vexecutionId\"\xce\x01\n" +
	"\x16GetWorkflowStatusReply\x12!\n" +
	"\fexecution_id\x18\x01 \x01(\tR\vexecutionId\x12\x16\n" +
	"\x06status\x18\x02 \x01(\tR\x06status\x12\x16\n" +
	"\x06result\x18\x03 \x01(\tR\x06result\x12#\n" +
	"\rerror_message\x18\x04 \x01(\tR\ferrorMessage\x12\x1d\n" +
	"\n" +
	"created_at\x18\x05 \x01(\tR\tcreatedAt\x12\x1d\n" +
	"\n" +
	"updated_at\x18\x06 \x01(\tR\tupdatedAt\"i\n" +
	"\x1dListWorkflowExecutionsRequest\x12\x17\n" +
	"\auser_id\x18\x01 \x01(\tR\x06userId\x12\x12\n" +
	"\x04page\x18\x02 \x01(\x05R\x04page\x12\x1b\n" +
	"\tpage_size\x18\x03 \x01(\x05R\bpageSize\"s\n" +
	"\x1bListWorkflowExecutionsReply\x12>\n" +
	"\n" +
	"executions\x18\x01 \x03(\v2\x1e.workflow.v1.WorkflowExecutionR\n" +
	"executions\x12\x14\n" +
	"\x05total\x18\x02 \x01(\x05R\x05total\"\xb7\x01\n" +
	"\x11WorkflowExecution\x12\x0e\n" +
	"\x02id\x18\x01 \x01(\tR\x02id\x12#\n" +
	"\rworkflow_type\x18\x02 \x01(\tR\fworkflowType\x12\x16\n" +
	"\x06status\x18\x03 \x01(\tR\x06status\x12\x17\n" +
	"\auser_id\x18\x04 \x01(\tR\x06userId\x12\x1d\n" +
	"\n" +
	"created_at\x18\x05 \x01(\tR\tcreatedAt\x12\x1d\n" +
	"\n" +
	"updated_at\x18\x06 \x01(\tR\tupdatedAt2\xa6\x03\n" +
	"\bWorkflow\x12z\n" +
	"\x0fExecuteWorkflow\x12#.workflow.v1.ExecuteWorkflowRequest\x1a!.workflow.v1.ExecuteWorkflowReply\"\x1f\x82\xd3\xe4\x93\x02\x19:\x01*\"\x14/v1/workflow/execute\x12\x8b\x01\n" +
	"\x11GetWorkflowStatus\x12%.workflow.v1.GetWorkflowStatusRequest\x1a#.workflow.v1.GetWorkflowStatusReply\"*\x82\xd3\xe4\x93\x02$\x12\"/v1/workflow/status/{execution_id}\x12\x8f\x01\n" +
	"\x16ListWorkflowExecutions\x12*.workflow.v1.ListWorkflowExecutionsRequest\x1a(.workflow.v1.ListWorkflowExecutionsReply\"\x1f\x82\xd3\xe4\x93\x02\x19\x12\x17/v1/workflow/executionsBK\n" +
	"\x1adev.kratos.api.workflow.v1B\x0fWorkflowProtoV1P\x01Z\x1abackend/api/workflow/v1;v1b\x06proto3"

var (
	file_workflow_v1_workflow_proto_rawDescOnce sync.Once
	file_workflow_v1_workflow_proto_rawDescData []byte
)

func file_workflow_v1_workflow_proto_rawDescGZIP() []byte {
	file_workflow_v1_workflow_proto_rawDescOnce.Do(func() {
		file_workflow_v1_workflow_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_workflow_v1_workflow_proto_rawDesc), len(file_workflow_v1_workflow_proto_rawDesc)))
	})
	return file_workflow_v1_workflow_proto_rawDescData
}

var file_workflow_v1_workflow_proto_msgTypes = make([]protoimpl.MessageInfo, 8)
var file_workflow_v1_workflow_proto_goTypes = []any{
	(*ExecuteWorkflowRequest)(nil),        // 0: workflow.v1.ExecuteWorkflowRequest
	(*ExecuteWorkflowReply)(nil),          // 1: workflow.v1.ExecuteWorkflowReply
	(*GetWorkflowStatusRequest)(nil),      // 2: workflow.v1.GetWorkflowStatusRequest
	(*GetWorkflowStatusReply)(nil),        // 3: workflow.v1.GetWorkflowStatusReply
	(*ListWorkflowExecutionsRequest)(nil), // 4: workflow.v1.ListWorkflowExecutionsRequest
	(*ListWorkflowExecutionsReply)(nil),   // 5: workflow.v1.ListWorkflowExecutionsReply
	(*WorkflowExecution)(nil),             // 6: workflow.v1.WorkflowExecution
	nil,                                   // 7: workflow.v1.ExecuteWorkflowRequest.ParametersEntry
}
var file_workflow_v1_workflow_proto_depIdxs = []int32{
	7, // 0: workflow.v1.ExecuteWorkflowRequest.parameters:type_name -> workflow.v1.ExecuteWorkflowRequest.ParametersEntry
	6, // 1: workflow.v1.ListWorkflowExecutionsReply.executions:type_name -> workflow.v1.WorkflowExecution
	0, // 2: workflow.v1.Workflow.ExecuteWorkflow:input_type -> workflow.v1.ExecuteWorkflowRequest
	2, // 3: workflow.v1.Workflow.GetWorkflowStatus:input_type -> workflow.v1.GetWorkflowStatusRequest
	4, // 4: workflow.v1.Workflow.ListWorkflowExecutions:input_type -> workflow.v1.ListWorkflowExecutionsRequest
	1, // 5: workflow.v1.Workflow.ExecuteWorkflow:output_type -> workflow.v1.ExecuteWorkflowReply
	3, // 6: workflow.v1.Workflow.GetWorkflowStatus:output_type -> workflow.v1.GetWorkflowStatusReply
	5, // 7: workflow.v1.Workflow.ListWorkflowExecutions:output_type -> workflow.v1.ListWorkflowExecutionsReply
	5, // [5:8] is the sub-list for method output_type
	2, // [2:5] is the sub-list for method input_type
	2, // [2:2] is the sub-list for extension type_name
	2, // [2:2] is the sub-list for extension extendee
	0, // [0:2] is the sub-list for field type_name
}

func init() { file_workflow_v1_workflow_proto_init() }
func file_workflow_v1_workflow_proto_init() {
	if File_workflow_v1_workflow_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_workflow_v1_workflow_proto_rawDesc), len(file_workflow_v1_workflow_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   8,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_workflow_v1_workflow_proto_goTypes,
		DependencyIndexes: file_workflow_v1_workflow_proto_depIdxs,
		MessageInfos:      file_workflow_v1_workflow_proto_msgTypes,
	}.Build()
	File_workflow_v1_workflow_proto = out.File
	file_workflow_v1_workflow_proto_goTypes = nil
	file_workflow_v1_workflow_proto_depIdxs = nil
}
