// Code generated by protoc-gen-go-http. DO NOT EDIT.
// versions:
// - protoc-gen-go-http v2.9.0
// - protoc             v3.21.12
// source: aichat/v1/admin.proto

package v1

import (
	context "context"
	http "github.com/go-kratos/kratos/v2/transport/http"
	binding "github.com/go-kratos/kratos/v2/transport/http/binding"
)

// This is a compile-time assertion to ensure that this generated file
// is compatible with the kratos package it is being compiled against.
var _ = new(context.Context)
var _ = binding.EncodeURL

const _ = http.SupportPackageIsVersion1

const OperationAdminServiceCreateFunction = "/aichat.admin.v1.AdminService/CreateFunction"
const OperationAdminServiceCreateWorkflow = "/aichat.admin.v1.AdminService/CreateWorkflow"
const OperationAdminServiceDeleteFunction = "/aichat.admin.v1.AdminService/DeleteFunction"
const OperationAdminServiceDeleteWorkflow = "/aichat.admin.v1.AdminService/DeleteWorkflow"
const OperationAdminServiceGetFunctionList = "/aichat.admin.v1.AdminService/GetFunctionList"
const OperationAdminServiceGetMCPConfig = "/aichat.admin.v1.AdminService/GetMCPConfig"
const OperationAdminServiceGetWorkflowList = "/aichat.admin.v1.AdminService/GetWorkflowList"
const OperationAdminServiceUpdateFunction = "/aichat.admin.v1.AdminService/UpdateFunction"
const OperationAdminServiceUpdateMCPConfig = "/aichat.admin.v1.AdminService/UpdateMCPConfig"
const OperationAdminServiceUpdateWorkflow = "/aichat.admin.v1.AdminService/UpdateWorkflow"

type AdminServiceHTTPServer interface {
	// CreateFunction 创建函数工具
	CreateFunction(context.Context, *CreateFunctionRequest) (*CreateFunctionReply, error)
	// CreateWorkflow 创建工作流
	CreateWorkflow(context.Context, *CreateWorkflowRequest) (*CreateWorkflowReply, error)
	// DeleteFunction 删除函数工具
	DeleteFunction(context.Context, *DeleteFunctionRequest) (*DeleteFunctionReply, error)
	// DeleteWorkflow 删除工作流
	DeleteWorkflow(context.Context, *DeleteWorkflowRequest) (*DeleteWorkflowReply, error)
	// GetFunctionList 获取函数工具列表
	GetFunctionList(context.Context, *GetFunctionListRequest) (*GetFunctionListReply, error)
	// GetMCPConfig 获取MCP配置
	GetMCPConfig(context.Context, *GetMCPConfigRequest) (*GetMCPConfigReply, error)
	// GetWorkflowList 获取工作流列表
	GetWorkflowList(context.Context, *GetWorkflowListRequest) (*GetWorkflowListReply, error)
	// UpdateFunction 更新函数工具
	UpdateFunction(context.Context, *UpdateFunctionRequest) (*UpdateFunctionReply, error)
	// UpdateMCPConfig 更新MCP配置
	UpdateMCPConfig(context.Context, *UpdateMCPConfigRequest) (*UpdateMCPConfigReply, error)
	// UpdateWorkflow 更新工作流
	UpdateWorkflow(context.Context, *UpdateWorkflowRequest) (*UpdateWorkflowReply, error)
}

func RegisterAdminServiceHTTPServer(s *http.Server, srv AdminServiceHTTPServer) {
	r := s.Route("/")
	r.GET("/api/v1/admin/config/mcp", _AdminService_GetMCPConfig0_HTTP_Handler(srv))
	r.POST("/api/v1/admin/config/mcp", _AdminService_UpdateMCPConfig0_HTTP_Handler(srv))
	r.GET("/api/v1/admin/function/list", _AdminService_GetFunctionList0_HTTP_Handler(srv))
	r.POST("/api/v1/admin/function/create", _AdminService_CreateFunction0_HTTP_Handler(srv))
	r.PUT("/api/v1/admin/function/{id}", _AdminService_UpdateFunction0_HTTP_Handler(srv))
	r.DELETE("/api/v1/admin/function/{id}", _AdminService_DeleteFunction0_HTTP_Handler(srv))
	r.GET("/api/v1/admin/workflow/list", _AdminService_GetWorkflowList0_HTTP_Handler(srv))
	r.POST("/api/v1/admin/workflow/create", _AdminService_CreateWorkflow0_HTTP_Handler(srv))
	r.PUT("/api/v1/admin/workflow/{id}", _AdminService_UpdateWorkflow0_HTTP_Handler(srv))
	r.DELETE("/api/v1/admin/workflow/{id}", _AdminService_DeleteWorkflow0_HTTP_Handler(srv))
}

func _AdminService_GetMCPConfig0_HTTP_Handler(srv AdminServiceHTTPServer) func(ctx http.Context) error {
	return func(ctx http.Context) error {
		var in GetMCPConfigRequest
		if err := ctx.BindQuery(&in); err != nil {
			return err
		}
		http.SetOperation(ctx, OperationAdminServiceGetMCPConfig)
		h := ctx.Middleware(func(ctx context.Context, req interface{}) (interface{}, error) {
			return srv.GetMCPConfig(ctx, req.(*GetMCPConfigRequest))
		})
		out, err := h(ctx, &in)
		if err != nil {
			return err
		}
		reply := out.(*GetMCPConfigReply)
		return ctx.Result(200, reply)
	}
}

func _AdminService_UpdateMCPConfig0_HTTP_Handler(srv AdminServiceHTTPServer) func(ctx http.Context) error {
	return func(ctx http.Context) error {
		var in UpdateMCPConfigRequest
		if err := ctx.Bind(&in); err != nil {
			return err
		}
		if err := ctx.BindQuery(&in); err != nil {
			return err
		}
		http.SetOperation(ctx, OperationAdminServiceUpdateMCPConfig)
		h := ctx.Middleware(func(ctx context.Context, req interface{}) (interface{}, error) {
			return srv.UpdateMCPConfig(ctx, req.(*UpdateMCPConfigRequest))
		})
		out, err := h(ctx, &in)
		if err != nil {
			return err
		}
		reply := out.(*UpdateMCPConfigReply)
		return ctx.Result(200, reply)
	}
}

func _AdminService_GetFunctionList0_HTTP_Handler(srv AdminServiceHTTPServer) func(ctx http.Context) error {
	return func(ctx http.Context) error {
		var in GetFunctionListRequest
		if err := ctx.BindQuery(&in); err != nil {
			return err
		}
		http.SetOperation(ctx, OperationAdminServiceGetFunctionList)
		h := ctx.Middleware(func(ctx context.Context, req interface{}) (interface{}, error) {
			return srv.GetFunctionList(ctx, req.(*GetFunctionListRequest))
		})
		out, err := h(ctx, &in)
		if err != nil {
			return err
		}
		reply := out.(*GetFunctionListReply)
		return ctx.Result(200, reply)
	}
}

func _AdminService_CreateFunction0_HTTP_Handler(srv AdminServiceHTTPServer) func(ctx http.Context) error {
	return func(ctx http.Context) error {
		var in CreateFunctionRequest
		if err := ctx.Bind(&in); err != nil {
			return err
		}
		if err := ctx.BindQuery(&in); err != nil {
			return err
		}
		http.SetOperation(ctx, OperationAdminServiceCreateFunction)
		h := ctx.Middleware(func(ctx context.Context, req interface{}) (interface{}, error) {
			return srv.CreateFunction(ctx, req.(*CreateFunctionRequest))
		})
		out, err := h(ctx, &in)
		if err != nil {
			return err
		}
		reply := out.(*CreateFunctionReply)
		return ctx.Result(200, reply)
	}
}

func _AdminService_UpdateFunction0_HTTP_Handler(srv AdminServiceHTTPServer) func(ctx http.Context) error {
	return func(ctx http.Context) error {
		var in UpdateFunctionRequest
		if err := ctx.Bind(&in); err != nil {
			return err
		}
		if err := ctx.BindQuery(&in); err != nil {
			return err
		}
		if err := ctx.BindVars(&in); err != nil {
			return err
		}
		http.SetOperation(ctx, OperationAdminServiceUpdateFunction)
		h := ctx.Middleware(func(ctx context.Context, req interface{}) (interface{}, error) {
			return srv.UpdateFunction(ctx, req.(*UpdateFunctionRequest))
		})
		out, err := h(ctx, &in)
		if err != nil {
			return err
		}
		reply := out.(*UpdateFunctionReply)
		return ctx.Result(200, reply)
	}
}

func _AdminService_DeleteFunction0_HTTP_Handler(srv AdminServiceHTTPServer) func(ctx http.Context) error {
	return func(ctx http.Context) error {
		var in DeleteFunctionRequest
		if err := ctx.BindQuery(&in); err != nil {
			return err
		}
		if err := ctx.BindVars(&in); err != nil {
			return err
		}
		http.SetOperation(ctx, OperationAdminServiceDeleteFunction)
		h := ctx.Middleware(func(ctx context.Context, req interface{}) (interface{}, error) {
			return srv.DeleteFunction(ctx, req.(*DeleteFunctionRequest))
		})
		out, err := h(ctx, &in)
		if err != nil {
			return err
		}
		reply := out.(*DeleteFunctionReply)
		return ctx.Result(200, reply)
	}
}

func _AdminService_GetWorkflowList0_HTTP_Handler(srv AdminServiceHTTPServer) func(ctx http.Context) error {
	return func(ctx http.Context) error {
		var in GetWorkflowListRequest
		if err := ctx.BindQuery(&in); err != nil {
			return err
		}
		http.SetOperation(ctx, OperationAdminServiceGetWorkflowList)
		h := ctx.Middleware(func(ctx context.Context, req interface{}) (interface{}, error) {
			return srv.GetWorkflowList(ctx, req.(*GetWorkflowListRequest))
		})
		out, err := h(ctx, &in)
		if err != nil {
			return err
		}
		reply := out.(*GetWorkflowListReply)
		return ctx.Result(200, reply)
	}
}

func _AdminService_CreateWorkflow0_HTTP_Handler(srv AdminServiceHTTPServer) func(ctx http.Context) error {
	return func(ctx http.Context) error {
		var in CreateWorkflowRequest
		if err := ctx.Bind(&in); err != nil {
			return err
		}
		if err := ctx.BindQuery(&in); err != nil {
			return err
		}
		http.SetOperation(ctx, OperationAdminServiceCreateWorkflow)
		h := ctx.Middleware(func(ctx context.Context, req interface{}) (interface{}, error) {
			return srv.CreateWorkflow(ctx, req.(*CreateWorkflowRequest))
		})
		out, err := h(ctx, &in)
		if err != nil {
			return err
		}
		reply := out.(*CreateWorkflowReply)
		return ctx.Result(200, reply)
	}
}

func _AdminService_UpdateWorkflow0_HTTP_Handler(srv AdminServiceHTTPServer) func(ctx http.Context) error {
	return func(ctx http.Context) error {
		var in UpdateWorkflowRequest
		if err := ctx.Bind(&in); err != nil {
			return err
		}
		if err := ctx.BindQuery(&in); err != nil {
			return err
		}
		if err := ctx.BindVars(&in); err != nil {
			return err
		}
		http.SetOperation(ctx, OperationAdminServiceUpdateWorkflow)
		h := ctx.Middleware(func(ctx context.Context, req interface{}) (interface{}, error) {
			return srv.UpdateWorkflow(ctx, req.(*UpdateWorkflowRequest))
		})
		out, err := h(ctx, &in)
		if err != nil {
			return err
		}
		reply := out.(*UpdateWorkflowReply)
		return ctx.Result(200, reply)
	}
}

func _AdminService_DeleteWorkflow0_HTTP_Handler(srv AdminServiceHTTPServer) func(ctx http.Context) error {
	return func(ctx http.Context) error {
		var in DeleteWorkflowRequest
		if err := ctx.BindQuery(&in); err != nil {
			return err
		}
		if err := ctx.BindVars(&in); err != nil {
			return err
		}
		http.SetOperation(ctx, OperationAdminServiceDeleteWorkflow)
		h := ctx.Middleware(func(ctx context.Context, req interface{}) (interface{}, error) {
			return srv.DeleteWorkflow(ctx, req.(*DeleteWorkflowRequest))
		})
		out, err := h(ctx, &in)
		if err != nil {
			return err
		}
		reply := out.(*DeleteWorkflowReply)
		return ctx.Result(200, reply)
	}
}

type AdminServiceHTTPClient interface {
	// CreateFunction 创建函数工具
	CreateFunction(ctx context.Context, req *CreateFunctionRequest, opts ...http.CallOption) (rsp *CreateFunctionReply, err error)
	// CreateWorkflow 创建工作流
	CreateWorkflow(ctx context.Context, req *CreateWorkflowRequest, opts ...http.CallOption) (rsp *CreateWorkflowReply, err error)
	// DeleteFunction 删除函数工具
	DeleteFunction(ctx context.Context, req *DeleteFunctionRequest, opts ...http.CallOption) (rsp *DeleteFunctionReply, err error)
	// DeleteWorkflow 删除工作流
	DeleteWorkflow(ctx context.Context, req *DeleteWorkflowRequest, opts ...http.CallOption) (rsp *DeleteWorkflowReply, err error)
	// GetFunctionList 获取函数工具列表
	GetFunctionList(ctx context.Context, req *GetFunctionListRequest, opts ...http.CallOption) (rsp *GetFunctionListReply, err error)
	// GetMCPConfig 获取MCP配置
	GetMCPConfig(ctx context.Context, req *GetMCPConfigRequest, opts ...http.CallOption) (rsp *GetMCPConfigReply, err error)
	// GetWorkflowList 获取工作流列表
	GetWorkflowList(ctx context.Context, req *GetWorkflowListRequest, opts ...http.CallOption) (rsp *GetWorkflowListReply, err error)
	// UpdateFunction 更新函数工具
	UpdateFunction(ctx context.Context, req *UpdateFunctionRequest, opts ...http.CallOption) (rsp *UpdateFunctionReply, err error)
	// UpdateMCPConfig 更新MCP配置
	UpdateMCPConfig(ctx context.Context, req *UpdateMCPConfigRequest, opts ...http.CallOption) (rsp *UpdateMCPConfigReply, err error)
	// UpdateWorkflow 更新工作流
	UpdateWorkflow(ctx context.Context, req *UpdateWorkflowRequest, opts ...http.CallOption) (rsp *UpdateWorkflowReply, err error)
}

type AdminServiceHTTPClientImpl struct {
	cc *http.Client
}

func NewAdminServiceHTTPClient(client *http.Client) AdminServiceHTTPClient {
	return &AdminServiceHTTPClientImpl{client}
}

// CreateFunction 创建函数工具
func (c *AdminServiceHTTPClientImpl) CreateFunction(ctx context.Context, in *CreateFunctionRequest, opts ...http.CallOption) (*CreateFunctionReply, error) {
	var out CreateFunctionReply
	pattern := "/api/v1/admin/function/create"
	path := binding.EncodeURL(pattern, in, false)
	opts = append(opts, http.Operation(OperationAdminServiceCreateFunction))
	opts = append(opts, http.PathTemplate(pattern))
	err := c.cc.Invoke(ctx, "POST", path, in, &out, opts...)
	if err != nil {
		return nil, err
	}
	return &out, nil
}

// CreateWorkflow 创建工作流
func (c *AdminServiceHTTPClientImpl) CreateWorkflow(ctx context.Context, in *CreateWorkflowRequest, opts ...http.CallOption) (*CreateWorkflowReply, error) {
	var out CreateWorkflowReply
	pattern := "/api/v1/admin/workflow/create"
	path := binding.EncodeURL(pattern, in, false)
	opts = append(opts, http.Operation(OperationAdminServiceCreateWorkflow))
	opts = append(opts, http.PathTemplate(pattern))
	err := c.cc.Invoke(ctx, "POST", path, in, &out, opts...)
	if err != nil {
		return nil, err
	}
	return &out, nil
}

// DeleteFunction 删除函数工具
func (c *AdminServiceHTTPClientImpl) DeleteFunction(ctx context.Context, in *DeleteFunctionRequest, opts ...http.CallOption) (*DeleteFunctionReply, error) {
	var out DeleteFunctionReply
	pattern := "/api/v1/admin/function/{id}"
	path := binding.EncodeURL(pattern, in, true)
	opts = append(opts, http.Operation(OperationAdminServiceDeleteFunction))
	opts = append(opts, http.PathTemplate(pattern))
	err := c.cc.Invoke(ctx, "DELETE", path, nil, &out, opts...)
	if err != nil {
		return nil, err
	}
	return &out, nil
}

// DeleteWorkflow 删除工作流
func (c *AdminServiceHTTPClientImpl) DeleteWorkflow(ctx context.Context, in *DeleteWorkflowRequest, opts ...http.CallOption) (*DeleteWorkflowReply, error) {
	var out DeleteWorkflowReply
	pattern := "/api/v1/admin/workflow/{id}"
	path := binding.EncodeURL(pattern, in, true)
	opts = append(opts, http.Operation(OperationAdminServiceDeleteWorkflow))
	opts = append(opts, http.PathTemplate(pattern))
	err := c.cc.Invoke(ctx, "DELETE", path, nil, &out, opts...)
	if err != nil {
		return nil, err
	}
	return &out, nil
}

// GetFunctionList 获取函数工具列表
func (c *AdminServiceHTTPClientImpl) GetFunctionList(ctx context.Context, in *GetFunctionListRequest, opts ...http.CallOption) (*GetFunctionListReply, error) {
	var out GetFunctionListReply
	pattern := "/api/v1/admin/function/list"
	path := binding.EncodeURL(pattern, in, true)
	opts = append(opts, http.Operation(OperationAdminServiceGetFunctionList))
	opts = append(opts, http.PathTemplate(pattern))
	err := c.cc.Invoke(ctx, "GET", path, nil, &out, opts...)
	if err != nil {
		return nil, err
	}
	return &out, nil
}

// GetMCPConfig 获取MCP配置
func (c *AdminServiceHTTPClientImpl) GetMCPConfig(ctx context.Context, in *GetMCPConfigRequest, opts ...http.CallOption) (*GetMCPConfigReply, error) {
	var out GetMCPConfigReply
	pattern := "/api/v1/admin/config/mcp"
	path := binding.EncodeURL(pattern, in, true)
	opts = append(opts, http.Operation(OperationAdminServiceGetMCPConfig))
	opts = append(opts, http.PathTemplate(pattern))
	err := c.cc.Invoke(ctx, "GET", path, nil, &out, opts...)
	if err != nil {
		return nil, err
	}
	return &out, nil
}

// GetWorkflowList 获取工作流列表
func (c *AdminServiceHTTPClientImpl) GetWorkflowList(ctx context.Context, in *GetWorkflowListRequest, opts ...http.CallOption) (*GetWorkflowListReply, error) {
	var out GetWorkflowListReply
	pattern := "/api/v1/admin/workflow/list"
	path := binding.EncodeURL(pattern, in, true)
	opts = append(opts, http.Operation(OperationAdminServiceGetWorkflowList))
	opts = append(opts, http.PathTemplate(pattern))
	err := c.cc.Invoke(ctx, "GET", path, nil, &out, opts...)
	if err != nil {
		return nil, err
	}
	return &out, nil
}

// UpdateFunction 更新函数工具
func (c *AdminServiceHTTPClientImpl) UpdateFunction(ctx context.Context, in *UpdateFunctionRequest, opts ...http.CallOption) (*UpdateFunctionReply, error) {
	var out UpdateFunctionReply
	pattern := "/api/v1/admin/function/{id}"
	path := binding.EncodeURL(pattern, in, false)
	opts = append(opts, http.Operation(OperationAdminServiceUpdateFunction))
	opts = append(opts, http.PathTemplate(pattern))
	err := c.cc.Invoke(ctx, "PUT", path, in, &out, opts...)
	if err != nil {
		return nil, err
	}
	return &out, nil
}

// UpdateMCPConfig 更新MCP配置
func (c *AdminServiceHTTPClientImpl) UpdateMCPConfig(ctx context.Context, in *UpdateMCPConfigRequest, opts ...http.CallOption) (*UpdateMCPConfigReply, error) {
	var out UpdateMCPConfigReply
	pattern := "/api/v1/admin/config/mcp"
	path := binding.EncodeURL(pattern, in, false)
	opts = append(opts, http.Operation(OperationAdminServiceUpdateMCPConfig))
	opts = append(opts, http.PathTemplate(pattern))
	err := c.cc.Invoke(ctx, "POST", path, in, &out, opts...)
	if err != nil {
		return nil, err
	}
	return &out, nil
}

// UpdateWorkflow 更新工作流
func (c *AdminServiceHTTPClientImpl) UpdateWorkflow(ctx context.Context, in *UpdateWorkflowRequest, opts ...http.CallOption) (*UpdateWorkflowReply, error) {
	var out UpdateWorkflowReply
	pattern := "/api/v1/admin/workflow/{id}"
	path := binding.EncodeURL(pattern, in, false)
	opts = append(opts, http.Operation(OperationAdminServiceUpdateWorkflow))
	opts = append(opts, http.PathTemplate(pattern))
	err := c.cc.Invoke(ctx, "PUT", path, in, &out, opts...)
	if err != nil {
		return nil, err
	}
	return &out, nil
}
