// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.9
// 	protoc        v3.21.12
// source: aichat/v1/chat.proto

package v1

import (
	_ "google.golang.org/genproto/googleapis/api/annotations"
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

// SendMessageRequest 发送消息请求
type SendMessageRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	ChatId        uint64                 `protobuf:"varint,1,opt,name=chat_id,json=chatId,proto3" json:"chat_id,omitempty"`
	Content       string                 `protobuf:"bytes,2,opt,name=content,proto3" json:"content,omitempty"`
	Type          string                 `protobuf:"bytes,3,opt,name=type,proto3" json:"type,omitempty"`
	Metadata      map[string]string      `protobuf:"bytes,4,rep,name=metadata,proto3" json:"metadata,omitempty" protobuf_key:"bytes,1,opt,name=key" protobuf_val:"bytes,2,opt,name=value"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *SendMessageRequest) Reset() {
	*x = SendMessageRequest{}
	mi := &file_aichat_v1_chat_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *SendMessageRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*SendMessageRequest) ProtoMessage() {}

func (x *SendMessageRequest) ProtoReflect() protoreflect.Message {
	mi := &file_aichat_v1_chat_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use SendMessageRequest.ProtoReflect.Descriptor instead.
func (*SendMessageRequest) Descriptor() ([]byte, []int) {
	return file_aichat_v1_chat_proto_rawDescGZIP(), []int{0}
}

func (x *SendMessageRequest) GetChatId() uint64 {
	if x != nil {
		return x.ChatId
	}
	return 0
}

func (x *SendMessageRequest) GetContent() string {
	if x != nil {
		return x.Content
	}
	return ""
}

func (x *SendMessageRequest) GetType() string {
	if x != nil {
		return x.Type
	}
	return ""
}

func (x *SendMessageRequest) GetMetadata() map[string]string {
	if x != nil {
		return x.Metadata
	}
	return nil
}

// SendMessageReply 发送消息响应
type SendMessageReply struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Success       bool                   `protobuf:"varint,1,opt,name=success,proto3" json:"success,omitempty"`
	Message       string                 `protobuf:"bytes,2,opt,name=message,proto3" json:"message,omitempty"`
	ChatId        uint64                 `protobuf:"varint,3,opt,name=chat_id,json=chatId,proto3" json:"chat_id,omitempty"`
	Messages      []*MessageInfo         `protobuf:"bytes,4,rep,name=messages,proto3" json:"messages,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *SendMessageReply) Reset() {
	*x = SendMessageReply{}
	mi := &file_aichat_v1_chat_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *SendMessageReply) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*SendMessageReply) ProtoMessage() {}

func (x *SendMessageReply) ProtoReflect() protoreflect.Message {
	mi := &file_aichat_v1_chat_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use SendMessageReply.ProtoReflect.Descriptor instead.
func (*SendMessageReply) Descriptor() ([]byte, []int) {
	return file_aichat_v1_chat_proto_rawDescGZIP(), []int{1}
}

func (x *SendMessageReply) GetSuccess() bool {
	if x != nil {
		return x.Success
	}
	return false
}

func (x *SendMessageReply) GetMessage() string {
	if x != nil {
		return x.Message
	}
	return ""
}

func (x *SendMessageReply) GetChatId() uint64 {
	if x != nil {
		return x.ChatId
	}
	return 0
}

func (x *SendMessageReply) GetMessages() []*MessageInfo {
	if x != nil {
		return x.Messages
	}
	return nil
}

// GetChatHistoryRequest 获取聊天历史请求
type GetChatHistoryRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	ChatId        uint64                 `protobuf:"varint,1,opt,name=chat_id,json=chatId,proto3" json:"chat_id,omitempty"`
	Page          int32                  `protobuf:"varint,2,opt,name=page,proto3" json:"page,omitempty"`
	PageSize      int32                  `protobuf:"varint,3,opt,name=page_size,json=pageSize,proto3" json:"page_size,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetChatHistoryRequest) Reset() {
	*x = GetChatHistoryRequest{}
	mi := &file_aichat_v1_chat_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetChatHistoryRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetChatHistoryRequest) ProtoMessage() {}

func (x *GetChatHistoryRequest) ProtoReflect() protoreflect.Message {
	mi := &file_aichat_v1_chat_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetChatHistoryRequest.ProtoReflect.Descriptor instead.
func (*GetChatHistoryRequest) Descriptor() ([]byte, []int) {
	return file_aichat_v1_chat_proto_rawDescGZIP(), []int{2}
}

func (x *GetChatHistoryRequest) GetChatId() uint64 {
	if x != nil {
		return x.ChatId
	}
	return 0
}

func (x *GetChatHistoryRequest) GetPage() int32 {
	if x != nil {
		return x.Page
	}
	return 0
}

func (x *GetChatHistoryRequest) GetPageSize() int32 {
	if x != nil {
		return x.PageSize
	}
	return 0
}

// GetChatHistoryReply 获取聊天历史响应
type GetChatHistoryReply struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Success       bool                   `protobuf:"varint,1,opt,name=success,proto3" json:"success,omitempty"`
	Messages      []*MessageInfo         `protobuf:"bytes,2,rep,name=messages,proto3" json:"messages,omitempty"`
	Total         int32                  `protobuf:"varint,3,opt,name=total,proto3" json:"total,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetChatHistoryReply) Reset() {
	*x = GetChatHistoryReply{}
	mi := &file_aichat_v1_chat_proto_msgTypes[3]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetChatHistoryReply) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetChatHistoryReply) ProtoMessage() {}

func (x *GetChatHistoryReply) ProtoReflect() protoreflect.Message {
	mi := &file_aichat_v1_chat_proto_msgTypes[3]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetChatHistoryReply.ProtoReflect.Descriptor instead.
func (*GetChatHistoryReply) Descriptor() ([]byte, []int) {
	return file_aichat_v1_chat_proto_rawDescGZIP(), []int{3}
}

func (x *GetChatHistoryReply) GetSuccess() bool {
	if x != nil {
		return x.Success
	}
	return false
}

func (x *GetChatHistoryReply) GetMessages() []*MessageInfo {
	if x != nil {
		return x.Messages
	}
	return nil
}

func (x *GetChatHistoryReply) GetTotal() int32 {
	if x != nil {
		return x.Total
	}
	return 0
}

// MessageInfo 消息信息
type MessageInfo struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Id            uint64                 `protobuf:"varint,1,opt,name=id,proto3" json:"id,omitempty"`
	Content       string                 `protobuf:"bytes,2,opt,name=content,proto3" json:"content,omitempty"`
	Type          string                 `protobuf:"bytes,3,opt,name=type,proto3" json:"type,omitempty"`
	From          string                 `protobuf:"bytes,4,opt,name=from,proto3" json:"from,omitempty"`
	CreatedAt     string                 `protobuf:"bytes,5,opt,name=created_at,json=createdAt,proto3" json:"created_at,omitempty"`
	Metadata      map[string]string      `protobuf:"bytes,6,rep,name=metadata,proto3" json:"metadata,omitempty" protobuf_key:"bytes,1,opt,name=key" protobuf_val:"bytes,2,opt,name=value"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *MessageInfo) Reset() {
	*x = MessageInfo{}
	mi := &file_aichat_v1_chat_proto_msgTypes[4]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *MessageInfo) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*MessageInfo) ProtoMessage() {}

func (x *MessageInfo) ProtoReflect() protoreflect.Message {
	mi := &file_aichat_v1_chat_proto_msgTypes[4]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use MessageInfo.ProtoReflect.Descriptor instead.
func (*MessageInfo) Descriptor() ([]byte, []int) {
	return file_aichat_v1_chat_proto_rawDescGZIP(), []int{4}
}

func (x *MessageInfo) GetId() uint64 {
	if x != nil {
		return x.Id
	}
	return 0
}

func (x *MessageInfo) GetContent() string {
	if x != nil {
		return x.Content
	}
	return ""
}

func (x *MessageInfo) GetType() string {
	if x != nil {
		return x.Type
	}
	return ""
}

func (x *MessageInfo) GetFrom() string {
	if x != nil {
		return x.From
	}
	return ""
}

func (x *MessageInfo) GetCreatedAt() string {
	if x != nil {
		return x.CreatedAt
	}
	return ""
}

func (x *MessageInfo) GetMetadata() map[string]string {
	if x != nil {
		return x.Metadata
	}
	return nil
}

var File_aichat_v1_chat_proto protoreflect.FileDescriptor

const file_aichat_v1_chat_proto_rawDesc = "" +
	"\n" +
	"\x14aichat/v1/chat.proto\x12\x0eaichat.chat.v1\x1a\x1cgoogle/api/annotations.proto\"\xe6\x01\n" +
	"\x12SendMessageRequest\x12\x17\n" +
	"\achat_id\x18\x01 \x01(\x04R\x06chatId\x12\x18\n" +
	"\acontent\x18\x02 \x01(\tR\acontent\x12\x12\n" +
	"\x04type\x18\x03 \x01(\tR\x04type\x12L\n" +
	"\bmetadata\x18\x04 \x03(\v20.aichat.chat.v1.SendMessageRequest.MetadataEntryR\bmetadata\x1a;\n" +
	"\rMetadataEntry\x12\x10\n" +
	"\x03key\x18\x01 \x01(\tR\x03key\x12\x14\n" +
	"\x05value\x18\x02 \x01(\tR\x05value:\x028\x01\"\x98\x01\n" +
	"\x10SendMessageReply\x12\x18\n" +
	"\asuccess\x18\x01 \x01(\bR\asuccess\x12\x18\n" +
	"\amessage\x18\x02 \x01(\tR\amessage\x12\x17\n" +
	"\achat_id\x18\x03 \x01(\x04R\x06chatId\x127\n" +
	"\bmessages\x18\x04 \x03(\v2\x1b.aichat.chat.v1.MessageInfoR\bmessages\"a\n" +
	"\x15GetChatHistoryRequest\x12\x17\n" +
	"\achat_id\x18\x01 \x01(\x04R\x06chatId\x12\x12\n" +
	"\x04page\x18\x02 \x01(\x05R\x04page\x12\x1b\n" +
	"\tpage_size\x18\x03 \x01(\x05R\bpageSize\"~\n" +
	"\x13GetChatHistoryReply\x12\x18\n" +
	"\asuccess\x18\x01 \x01(\bR\asuccess\x127\n" +
	"\bmessages\x18\x02 \x03(\v2\x1b.aichat.chat.v1.MessageInfoR\bmessages\x12\x14\n" +
	"\x05total\x18\x03 \x01(\x05R\x05total\"\x82\x02\n" +
	"\vMessageInfo\x12\x0e\n" +
	"\x02id\x18\x01 \x01(\x04R\x02id\x12\x18\n" +
	"\acontent\x18\x02 \x01(\tR\acontent\x12\x12\n" +
	"\x04type\x18\x03 \x01(\tR\x04type\x12\x12\n" +
	"\x04from\x18\x04 \x01(\tR\x04from\x12\x1d\n" +
	"\n" +
	"created_at\x18\x05 \x01(\tR\tcreatedAt\x12E\n" +
	"\bmetadata\x18\x06 \x03(\v2).aichat.chat.v1.MessageInfo.MetadataEntryR\bmetadata\x1a;\n" +
	"\rMetadataEntry\x12\x10\n" +
	"\x03key\x18\x01 \x01(\tR\x03key\x12\x14\n" +
	"\x05value\x18\x02 \x01(\tR\x05value:\x028\x012\xfc\x01\n" +
	"\vChatService\x12q\n" +
	"\vSendMessage\x12\".aichat.chat.v1.SendMessageRequest\x1a .aichat.chat.v1.SendMessageReply\"\x1c\x82\xd3\xe4\x93\x02\x16:\x01*\"\x11/api/v1/chat/send\x12z\n" +
	"\x0eGetChatHistory\x12%.aichat.chat.v1.GetChatHistoryRequest\x1a#.aichat.chat.v1.GetChatHistoryReply\"\x1c\x82\xd3\xe4\x93\x02\x16\x12\x14/api/v1/chat/historyBS\n" +
	"\x16dev.aichat.api.chat.v1B\vChatProtoV1P\x01Z*github.com/aichat/backend/api/aichat/v1;v1b\x06proto3"

var (
	file_aichat_v1_chat_proto_rawDescOnce sync.Once
	file_aichat_v1_chat_proto_rawDescData []byte
)

func file_aichat_v1_chat_proto_rawDescGZIP() []byte {
	file_aichat_v1_chat_proto_rawDescOnce.Do(func() {
		file_aichat_v1_chat_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_aichat_v1_chat_proto_rawDesc), len(file_aichat_v1_chat_proto_rawDesc)))
	})
	return file_aichat_v1_chat_proto_rawDescData
}

var file_aichat_v1_chat_proto_msgTypes = make([]protoimpl.MessageInfo, 7)
var file_aichat_v1_chat_proto_goTypes = []any{
	(*SendMessageRequest)(nil),    // 0: aichat.chat.v1.SendMessageRequest
	(*SendMessageReply)(nil),      // 1: aichat.chat.v1.SendMessageReply
	(*GetChatHistoryRequest)(nil), // 2: aichat.chat.v1.GetChatHistoryRequest
	(*GetChatHistoryReply)(nil),   // 3: aichat.chat.v1.GetChatHistoryReply
	(*MessageInfo)(nil),           // 4: aichat.chat.v1.MessageInfo
	nil,                           // 5: aichat.chat.v1.SendMessageRequest.MetadataEntry
	nil,                           // 6: aichat.chat.v1.MessageInfo.MetadataEntry
}
var file_aichat_v1_chat_proto_depIdxs = []int32{
	5, // 0: aichat.chat.v1.SendMessageRequest.metadata:type_name -> aichat.chat.v1.SendMessageRequest.MetadataEntry
	4, // 1: aichat.chat.v1.SendMessageReply.messages:type_name -> aichat.chat.v1.MessageInfo
	4, // 2: aichat.chat.v1.GetChatHistoryReply.messages:type_name -> aichat.chat.v1.MessageInfo
	6, // 3: aichat.chat.v1.MessageInfo.metadata:type_name -> aichat.chat.v1.MessageInfo.MetadataEntry
	0, // 4: aichat.chat.v1.ChatService.SendMessage:input_type -> aichat.chat.v1.SendMessageRequest
	2, // 5: aichat.chat.v1.ChatService.GetChatHistory:input_type -> aichat.chat.v1.GetChatHistoryRequest
	1, // 6: aichat.chat.v1.ChatService.SendMessage:output_type -> aichat.chat.v1.SendMessageReply
	3, // 7: aichat.chat.v1.ChatService.GetChatHistory:output_type -> aichat.chat.v1.GetChatHistoryReply
	6, // [6:8] is the sub-list for method output_type
	4, // [4:6] is the sub-list for method input_type
	4, // [4:4] is the sub-list for extension type_name
	4, // [4:4] is the sub-list for extension extendee
	0, // [0:4] is the sub-list for field type_name
}

func init() { file_aichat_v1_chat_proto_init() }
func file_aichat_v1_chat_proto_init() {
	if File_aichat_v1_chat_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_aichat_v1_chat_proto_rawDesc), len(file_aichat_v1_chat_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   7,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_aichat_v1_chat_proto_goTypes,
		DependencyIndexes: file_aichat_v1_chat_proto_depIdxs,
		MessageInfos:      file_aichat_v1_chat_proto_msgTypes,
	}.Build()
	File_aichat_v1_chat_proto = out.File
	file_aichat_v1_chat_proto_goTypes = nil
	file_aichat_v1_chat_proto_depIdxs = nil
}
