// Code generated by protoc-gen-go-http. DO NOT EDIT.
// versions:
// - protoc-gen-go-http v2.9.0
// - protoc             v3.21.12
// source: aichat/v1/chat.proto

package v1

import (
	context "context"
	http "github.com/go-kratos/kratos/v2/transport/http"
	binding "github.com/go-kratos/kratos/v2/transport/http/binding"
)

// This is a compile-time assertion to ensure that this generated file
// is compatible with the kratos package it is being compiled against.
var _ = new(context.Context)
var _ = binding.EncodeURL

const _ = http.SupportPackageIsVersion1

const OperationChatServiceGetChatHistory = "/aichat.chat.v1.ChatService/GetChatHistory"
const OperationChatServiceSendMessage = "/aichat.chat.v1.ChatService/SendMessage"

type ChatServiceHTTPServer interface {
	// GetChatHistory 获取聊天历史
	GetChatHistory(context.Context, *GetChatHistoryRequest) (*GetChatHistoryReply, error)
	// SendMessage 发送消息
	SendMessage(context.Context, *SendMessageRequest) (*SendMessageReply, error)
}

func RegisterChatServiceHTTPServer(s *http.Server, srv ChatServiceHTTPServer) {
	r := s.Route("/")
	r.POST("/api/v1/chat/send", _ChatService_SendMessage0_HTTP_Handler(srv))
	r.GET("/api/v1/chat/history", _ChatService_GetChatHistory0_HTTP_Handler(srv))
}

func _ChatService_SendMessage0_HTTP_Handler(srv ChatServiceHTTPServer) func(ctx http.Context) error {
	return func(ctx http.Context) error {
		var in SendMessageRequest
		if err := ctx.Bind(&in); err != nil {
			return err
		}
		if err := ctx.BindQuery(&in); err != nil {
			return err
		}
		http.SetOperation(ctx, OperationChatServiceSendMessage)
		h := ctx.Middleware(func(ctx context.Context, req interface{}) (interface{}, error) {
			return srv.SendMessage(ctx, req.(*SendMessageRequest))
		})
		out, err := h(ctx, &in)
		if err != nil {
			return err
		}
		reply := out.(*SendMessageReply)
		return ctx.Result(200, reply)
	}
}

func _ChatService_GetChatHistory0_HTTP_Handler(srv ChatServiceHTTPServer) func(ctx http.Context) error {
	return func(ctx http.Context) error {
		var in GetChatHistoryRequest
		if err := ctx.BindQuery(&in); err != nil {
			return err
		}
		http.SetOperation(ctx, OperationChatServiceGetChatHistory)
		h := ctx.Middleware(func(ctx context.Context, req interface{}) (interface{}, error) {
			return srv.GetChatHistory(ctx, req.(*GetChatHistoryRequest))
		})
		out, err := h(ctx, &in)
		if err != nil {
			return err
		}
		reply := out.(*GetChatHistoryReply)
		return ctx.Result(200, reply)
	}
}

type ChatServiceHTTPClient interface {
	// GetChatHistory 获取聊天历史
	GetChatHistory(ctx context.Context, req *GetChatHistoryRequest, opts ...http.CallOption) (rsp *GetChatHistoryReply, err error)
	// SendMessage 发送消息
	SendMessage(ctx context.Context, req *SendMessageRequest, opts ...http.CallOption) (rsp *SendMessageReply, err error)
}

type ChatServiceHTTPClientImpl struct {
	cc *http.Client
}

func NewChatServiceHTTPClient(client *http.Client) ChatServiceHTTPClient {
	return &ChatServiceHTTPClientImpl{client}
}

// GetChatHistory 获取聊天历史
func (c *ChatServiceHTTPClientImpl) GetChatHistory(ctx context.Context, in *GetChatHistoryRequest, opts ...http.CallOption) (*GetChatHistoryReply, error) {
	var out GetChatHistoryReply
	pattern := "/api/v1/chat/history"
	path := binding.EncodeURL(pattern, in, true)
	opts = append(opts, http.Operation(OperationChatServiceGetChatHistory))
	opts = append(opts, http.PathTemplate(pattern))
	err := c.cc.Invoke(ctx, "GET", path, nil, &out, opts...)
	if err != nil {
		return nil, err
	}
	return &out, nil
}

// SendMessage 发送消息
func (c *ChatServiceHTTPClientImpl) SendMessage(ctx context.Context, in *SendMessageRequest, opts ...http.CallOption) (*SendMessageReply, error) {
	var out SendMessageReply
	pattern := "/api/v1/chat/send"
	path := binding.EncodeURL(pattern, in, false)
	opts = append(opts, http.Operation(OperationChatServiceSendMessage))
	opts = append(opts, http.PathTemplate(pattern))
	err := c.cc.Invoke(ctx, "POST", path, in, &out, opts...)
	if err != nil {
		return nil, err
	}
	return &out, nil
}
