// Code generated by gorm.io/gen. DO NOT EDIT.
// Code generated by gorm.io/gen. DO NOT EDIT.
// Code generated by gorm.io/gen. DO NOT EDIT.

package query

import (
	"context"
	"database/sql"

	"gorm.io/gorm"
	"gorm.io/gorm/clause"
	"gorm.io/gorm/schema"

	"gorm.io/gen"
	"gorm.io/gen/field"

	"gorm.io/plugin/dbresolver"

	"github.com/example/aichat/backend/models/generator/model"
)

func newAIAgent(db *gorm.DB, opts ...gen.DOOption) aIAgent {
	_aIAgent := aIAgent{}

	_aIAgent.aIAgentDo.UseDB(db, opts...)
	_aIAgent.aIAgentDo.UseModel(&model.AIAgent{})

	tableName := _aIAgent.aIAgentDo.TableName()
	_aIAgent.ALL = field.NewAsterisk(tableName)
	_aIAgent.ID = field.NewInt64(tableName, "id")
	_aIAgent.CreatedAt = field.NewField(tableName, "created_at")
	_aIAgent.CreatedBy = field.NewInt64(tableName, "created_by")
	_aIAgent.UpdatedAt = field.NewField(tableName, "updated_at")
	_aIAgent.UpdatedBy = field.NewInt64(tableName, "updated_by")
	_aIAgent.IsDeleted = field.NewUint(tableName, "is_deleted")
	_aIAgent.DeletedAt = field.NewField(tableName, "deleted_at")
	_aIAgent.DeletedBy = field.NewInt64(tableName, "deleted_by")
	_aIAgent.Name = field.NewString(tableName, "name")
	_aIAgent.Code = field.NewString(tableName, "code")
	_aIAgent.Description = field.NewString(tableName, "description")
	_aIAgent.AdapterType = field.NewUint8(tableName, "adapter_type")
	_aIAgent.AIModelID = field.NewInt64(tableName, "ai_model_id")
	_aIAgent.MaxIteration = field.NewInt(tableName, "max_iteration")
	_aIAgent.SystemPrompt = field.NewString(tableName, "system_prompt")
	_aIAgent.UserInputPrompt = field.NewString(tableName, "user_input_prompt")
	_aIAgent.Status = field.NewUint8(tableName, "status")
	_aIAgent.Type = field.NewUint8(tableName, "type")
	_aIAgent.Order_ = field.NewInt(tableName, "order")
	_aIAgent.WithWriteTODOs = field.NewBool(tableName, "with_write_tod_os")
	_aIAgent.WithWebSearchAgent = field.NewBool(tableName, "with_web_search_agent")
	_aIAgent.SystemType = field.NewUint8(tableName, "system_type")
	_aIAgent.AIModel = aIAgentBelongsToAIModel{
		db: db.Session(&gorm.Session{}),

		RelationField: field.NewRelation("AIModel", "model.AIModel"),
	}

	_aIAgent.fillFieldMap()

	return _aIAgent
}

type aIAgent struct {
	aIAgentDo

	ALL                field.Asterisk
	ID                 field.Int64
	CreatedAt          field.Field
	CreatedBy          field.Int64
	UpdatedAt          field.Field
	UpdatedBy          field.Int64
	IsDeleted          field.Uint
	DeletedAt          field.Field
	DeletedBy          field.Int64
	Name               field.String
	Code               field.String
	Description        field.String
	AdapterType        field.Uint8
	AIModelID          field.Int64
	MaxIteration       field.Int    // '最大迭代次数'
	SystemPrompt       field.String // '系统提示词'
	UserInputPrompt    field.String // '用户提示词'
	Status             field.Uint8  // '状态'
	Type               field.Uint8  // '1 根 Agent, 2 子 Agent'
	Order_             field.Int
	WithWriteTODOs     field.Bool
	WithWebSearchAgent field.Bool
	SystemType         field.Uint8
	AIModel            aIAgentBelongsToAIModel

	fieldMap map[string]field.Expr
}

func (a aIAgent) Table(newTableName string) *aIAgent {
	a.aIAgentDo.UseTable(newTableName)
	return a.updateTableName(newTableName)
}

func (a aIAgent) As(alias string) *aIAgent {
	a.aIAgentDo.DO = *(a.aIAgentDo.As(alias).(*gen.DO))
	return a.updateTableName(alias)
}

func (a *aIAgent) updateTableName(table string) *aIAgent {
	a.ALL = field.NewAsterisk(table)
	a.ID = field.NewInt64(table, "id")
	a.CreatedAt = field.NewField(table, "created_at")
	a.CreatedBy = field.NewInt64(table, "created_by")
	a.UpdatedAt = field.NewField(table, "updated_at")
	a.UpdatedBy = field.NewInt64(table, "updated_by")
	a.IsDeleted = field.NewUint(table, "is_deleted")
	a.DeletedAt = field.NewField(table, "deleted_at")
	a.DeletedBy = field.NewInt64(table, "deleted_by")
	a.Name = field.NewString(table, "name")
	a.Code = field.NewString(table, "code")
	a.Description = field.NewString(table, "description")
	a.AdapterType = field.NewUint8(table, "adapter_type")
	a.AIModelID = field.NewInt64(table, "ai_model_id")
	a.MaxIteration = field.NewInt(table, "max_iteration")
	a.SystemPrompt = field.NewString(table, "system_prompt")
	a.UserInputPrompt = field.NewString(table, "user_input_prompt")
	a.Status = field.NewUint8(table, "status")
	a.Type = field.NewUint8(table, "type")
	a.Order_ = field.NewInt(table, "order")
	a.WithWriteTODOs = field.NewBool(table, "with_write_tod_os")
	a.WithWebSearchAgent = field.NewBool(table, "with_web_search_agent")
	a.SystemType = field.NewUint8(table, "system_type")

	a.fillFieldMap()

	return a
}

func (a *aIAgent) GetFieldByName(fieldName string) (field.OrderExpr, bool) {
	_f, ok := a.fieldMap[fieldName]
	if !ok || _f == nil {
		return nil, false
	}
	_oe, ok := _f.(field.OrderExpr)
	return _oe, ok
}

func (a *aIAgent) fillFieldMap() {
	a.fieldMap = make(map[string]field.Expr, 23)
	a.fieldMap["id"] = a.ID
	a.fieldMap["created_at"] = a.CreatedAt
	a.fieldMap["created_by"] = a.CreatedBy
	a.fieldMap["updated_at"] = a.UpdatedAt
	a.fieldMap["updated_by"] = a.UpdatedBy
	a.fieldMap["is_deleted"] = a.IsDeleted
	a.fieldMap["deleted_at"] = a.DeletedAt
	a.fieldMap["deleted_by"] = a.DeletedBy
	a.fieldMap["name"] = a.Name
	a.fieldMap["code"] = a.Code
	a.fieldMap["description"] = a.Description
	a.fieldMap["adapter_type"] = a.AdapterType
	a.fieldMap["ai_model_id"] = a.AIModelID
	a.fieldMap["max_iteration"] = a.MaxIteration
	a.fieldMap["system_prompt"] = a.SystemPrompt
	a.fieldMap["user_input_prompt"] = a.UserInputPrompt
	a.fieldMap["status"] = a.Status
	a.fieldMap["type"] = a.Type
	a.fieldMap["order"] = a.Order_
	a.fieldMap["with_write_tod_os"] = a.WithWriteTODOs
	a.fieldMap["with_web_search_agent"] = a.WithWebSearchAgent
	a.fieldMap["system_type"] = a.SystemType

}

func (a aIAgent) clone(db *gorm.DB) aIAgent {
	a.aIAgentDo.ReplaceConnPool(db.Statement.ConnPool)
	a.AIModel.db = db.Session(&gorm.Session{Initialized: true})
	a.AIModel.db.Statement.ConnPool = db.Statement.ConnPool
	return a
}

func (a aIAgent) replaceDB(db *gorm.DB) aIAgent {
	a.aIAgentDo.ReplaceDB(db)
	a.AIModel.db = db.Session(&gorm.Session{})
	return a
}

type aIAgentBelongsToAIModel struct {
	db *gorm.DB

	field.RelationField
}

func (a aIAgentBelongsToAIModel) Where(conds ...field.Expr) *aIAgentBelongsToAIModel {
	if len(conds) == 0 {
		return &a
	}

	exprs := make([]clause.Expression, 0, len(conds))
	for _, cond := range conds {
		exprs = append(exprs, cond.BeCond().(clause.Expression))
	}
	a.db = a.db.Clauses(clause.Where{Exprs: exprs})
	return &a
}

func (a aIAgentBelongsToAIModel) WithContext(ctx context.Context) *aIAgentBelongsToAIModel {
	a.db = a.db.WithContext(ctx)
	return &a
}

func (a aIAgentBelongsToAIModel) Session(session *gorm.Session) *aIAgentBelongsToAIModel {
	a.db = a.db.Session(session)
	return &a
}

func (a aIAgentBelongsToAIModel) Model(m *model.AIAgent) *aIAgentBelongsToAIModelTx {
	return &aIAgentBelongsToAIModelTx{a.db.Model(m).Association(a.Name())}
}

func (a aIAgentBelongsToAIModel) Unscoped() *aIAgentBelongsToAIModel {
	a.db = a.db.Unscoped()
	return &a
}

type aIAgentBelongsToAIModelTx struct{ tx *gorm.Association }

func (a aIAgentBelongsToAIModelTx) Find() (result *model.AIModel, err error) {
	return result, a.tx.Find(&result)
}

func (a aIAgentBelongsToAIModelTx) Append(values ...*model.AIModel) (err error) {
	targetValues := make([]interface{}, len(values))
	for i, v := range values {
		targetValues[i] = v
	}
	return a.tx.Append(targetValues...)
}

func (a aIAgentBelongsToAIModelTx) Replace(values ...*model.AIModel) (err error) {
	targetValues := make([]interface{}, len(values))
	for i, v := range values {
		targetValues[i] = v
	}
	return a.tx.Replace(targetValues...)
}

func (a aIAgentBelongsToAIModelTx) Delete(values ...*model.AIModel) (err error) {
	targetValues := make([]interface{}, len(values))
	for i, v := range values {
		targetValues[i] = v
	}
	return a.tx.Delete(targetValues...)
}

func (a aIAgentBelongsToAIModelTx) Clear() error {
	return a.tx.Clear()
}

func (a aIAgentBelongsToAIModelTx) Count() int64 {
	return a.tx.Count()
}

func (a aIAgentBelongsToAIModelTx) Unscoped() *aIAgentBelongsToAIModelTx {
	a.tx = a.tx.Unscoped()
	return &a
}

type aIAgentDo struct{ gen.DO }

type IAIAgentDo interface {
	gen.SubQuery
	Debug() IAIAgentDo
	WithContext(ctx context.Context) IAIAgentDo
	WithResult(fc func(tx gen.Dao)) gen.ResultInfo
	ReplaceDB(db *gorm.DB)
	ReadDB() IAIAgentDo
	WriteDB() IAIAgentDo
	As(alias string) gen.Dao
	Session(config *gorm.Session) IAIAgentDo
	Columns(cols ...field.Expr) gen.Columns
	Clauses(conds ...clause.Expression) IAIAgentDo
	Not(conds ...gen.Condition) IAIAgentDo
	Or(conds ...gen.Condition) IAIAgentDo
	Select(conds ...field.Expr) IAIAgentDo
	Where(conds ...gen.Condition) IAIAgentDo
	Order(conds ...field.Expr) IAIAgentDo
	Distinct(cols ...field.Expr) IAIAgentDo
	Omit(cols ...field.Expr) IAIAgentDo
	Join(table schema.Tabler, on ...field.Expr) IAIAgentDo
	LeftJoin(table schema.Tabler, on ...field.Expr) IAIAgentDo
	RightJoin(table schema.Tabler, on ...field.Expr) IAIAgentDo
	Group(cols ...field.Expr) IAIAgentDo
	Having(conds ...gen.Condition) IAIAgentDo
	Limit(limit int) IAIAgentDo
	Offset(offset int) IAIAgentDo
	Count() (count int64, err error)
	Scopes(funcs ...func(gen.Dao) gen.Dao) IAIAgentDo
	Unscoped() IAIAgentDo
	Create(values ...*model.AIAgent) error
	CreateInBatches(values []*model.AIAgent, batchSize int) error
	Save(values ...*model.AIAgent) error
	First() (*model.AIAgent, error)
	Take() (*model.AIAgent, error)
	Last() (*model.AIAgent, error)
	Find() ([]*model.AIAgent, error)
	FindInBatch(batchSize int, fc func(tx gen.Dao, batch int) error) (results []*model.AIAgent, err error)
	FindInBatches(result *[]*model.AIAgent, batchSize int, fc func(tx gen.Dao, batch int) error) error
	Pluck(column field.Expr, dest interface{}) error
	Delete(...*model.AIAgent) (info gen.ResultInfo, err error)
	Update(column field.Expr, value interface{}) (info gen.ResultInfo, err error)
	UpdateSimple(columns ...field.AssignExpr) (info gen.ResultInfo, err error)
	Updates(value interface{}) (info gen.ResultInfo, err error)
	UpdateColumn(column field.Expr, value interface{}) (info gen.ResultInfo, err error)
	UpdateColumnSimple(columns ...field.AssignExpr) (info gen.ResultInfo, err error)
	UpdateColumns(value interface{}) (info gen.ResultInfo, err error)
	UpdateFrom(q gen.SubQuery) gen.Dao
	Attrs(attrs ...field.AssignExpr) IAIAgentDo
	Assign(attrs ...field.AssignExpr) IAIAgentDo
	Joins(fields ...field.RelationField) IAIAgentDo
	Preload(fields ...field.RelationField) IAIAgentDo
	FirstOrInit() (*model.AIAgent, error)
	FirstOrCreate() (*model.AIAgent, error)
	FindByPage(offset int, limit int) (result []*model.AIAgent, count int64, err error)
	ScanByPage(result interface{}, offset int, limit int) (count int64, err error)
	Rows() (*sql.Rows, error)
	Row() *sql.Row
	Scan(result interface{}) (err error)
	Returning(value interface{}, columns ...string) IAIAgentDo
	UnderlyingDB() *gorm.DB
	schema.Tabler
}

func (a aIAgentDo) Debug() IAIAgentDo {
	return a.withDO(a.DO.Debug())
}

func (a aIAgentDo) WithContext(ctx context.Context) IAIAgentDo {
	return a.withDO(a.DO.WithContext(ctx))
}

func (a aIAgentDo) ReadDB() IAIAgentDo {
	return a.Clauses(dbresolver.Read)
}

func (a aIAgentDo) WriteDB() IAIAgentDo {
	return a.Clauses(dbresolver.Write)
}

func (a aIAgentDo) Session(config *gorm.Session) IAIAgentDo {
	return a.withDO(a.DO.Session(config))
}

func (a aIAgentDo) Clauses(conds ...clause.Expression) IAIAgentDo {
	return a.withDO(a.DO.Clauses(conds...))
}

func (a aIAgentDo) Returning(value interface{}, columns ...string) IAIAgentDo {
	return a.withDO(a.DO.Returning(value, columns...))
}

func (a aIAgentDo) Not(conds ...gen.Condition) IAIAgentDo {
	return a.withDO(a.DO.Not(conds...))
}

func (a aIAgentDo) Or(conds ...gen.Condition) IAIAgentDo {
	return a.withDO(a.DO.Or(conds...))
}

func (a aIAgentDo) Select(conds ...field.Expr) IAIAgentDo {
	return a.withDO(a.DO.Select(conds...))
}

func (a aIAgentDo) Where(conds ...gen.Condition) IAIAgentDo {
	return a.withDO(a.DO.Where(conds...))
}

func (a aIAgentDo) Order(conds ...field.Expr) IAIAgentDo {
	return a.withDO(a.DO.Order(conds...))
}

func (a aIAgentDo) Distinct(cols ...field.Expr) IAIAgentDo {
	return a.withDO(a.DO.Distinct(cols...))
}

func (a aIAgentDo) Omit(cols ...field.Expr) IAIAgentDo {
	return a.withDO(a.DO.Omit(cols...))
}

func (a aIAgentDo) Join(table schema.Tabler, on ...field.Expr) IAIAgentDo {
	return a.withDO(a.DO.Join(table, on...))
}

func (a aIAgentDo) LeftJoin(table schema.Tabler, on ...field.Expr) IAIAgentDo {
	return a.withDO(a.DO.LeftJoin(table, on...))
}

func (a aIAgentDo) RightJoin(table schema.Tabler, on ...field.Expr) IAIAgentDo {
	return a.withDO(a.DO.RightJoin(table, on...))
}

func (a aIAgentDo) Group(cols ...field.Expr) IAIAgentDo {
	return a.withDO(a.DO.Group(cols...))
}

func (a aIAgentDo) Having(conds ...gen.Condition) IAIAgentDo {
	return a.withDO(a.DO.Having(conds...))
}

func (a aIAgentDo) Limit(limit int) IAIAgentDo {
	return a.withDO(a.DO.Limit(limit))
}

func (a aIAgentDo) Offset(offset int) IAIAgentDo {
	return a.withDO(a.DO.Offset(offset))
}

func (a aIAgentDo) Scopes(funcs ...func(gen.Dao) gen.Dao) IAIAgentDo {
	return a.withDO(a.DO.Scopes(funcs...))
}

func (a aIAgentDo) Unscoped() IAIAgentDo {
	return a.withDO(a.DO.Unscoped())
}

func (a aIAgentDo) Create(values ...*model.AIAgent) error {
	if len(values) == 0 {
		return nil
	}
	return a.DO.Create(values)
}

func (a aIAgentDo) CreateInBatches(values []*model.AIAgent, batchSize int) error {
	return a.DO.CreateInBatches(values, batchSize)
}

// Save : !!! underlying implementation is different with GORM
// The method is equivalent to executing the statement: db.Clauses(clause.OnConflict{UpdateAll: true}).Create(values)
func (a aIAgentDo) Save(values ...*model.AIAgent) error {
	if len(values) == 0 {
		return nil
	}
	return a.DO.Save(values)
}

func (a aIAgentDo) First() (*model.AIAgent, error) {
	if result, err := a.DO.First(); err != nil {
		return nil, err
	} else {
		return result.(*model.AIAgent), nil
	}
}

func (a aIAgentDo) Take() (*model.AIAgent, error) {
	if result, err := a.DO.Take(); err != nil {
		return nil, err
	} else {
		return result.(*model.AIAgent), nil
	}
}

func (a aIAgentDo) Last() (*model.AIAgent, error) {
	if result, err := a.DO.Last(); err != nil {
		return nil, err
	} else {
		return result.(*model.AIAgent), nil
	}
}

func (a aIAgentDo) Find() ([]*model.AIAgent, error) {
	result, err := a.DO.Find()
	return result.([]*model.AIAgent), err
}

func (a aIAgentDo) FindInBatch(batchSize int, fc func(tx gen.Dao, batch int) error) (results []*model.AIAgent, err error) {
	buf := make([]*model.AIAgent, 0, batchSize)
	err = a.DO.FindInBatches(&buf, batchSize, func(tx gen.Dao, batch int) error {
		defer func() { results = append(results, buf...) }()
		return fc(tx, batch)
	})
	return results, err
}

func (a aIAgentDo) FindInBatches(result *[]*model.AIAgent, batchSize int, fc func(tx gen.Dao, batch int) error) error {
	return a.DO.FindInBatches(result, batchSize, fc)
}

func (a aIAgentDo) Attrs(attrs ...field.AssignExpr) IAIAgentDo {
	return a.withDO(a.DO.Attrs(attrs...))
}

func (a aIAgentDo) Assign(attrs ...field.AssignExpr) IAIAgentDo {
	return a.withDO(a.DO.Assign(attrs...))
}

func (a aIAgentDo) Joins(fields ...field.RelationField) IAIAgentDo {
	for _, _f := range fields {
		a = *a.withDO(a.DO.Joins(_f))
	}
	return &a
}

func (a aIAgentDo) Preload(fields ...field.RelationField) IAIAgentDo {
	for _, _f := range fields {
		a = *a.withDO(a.DO.Preload(_f))
	}
	return &a
}

func (a aIAgentDo) FirstOrInit() (*model.AIAgent, error) {
	if result, err := a.DO.FirstOrInit(); err != nil {
		return nil, err
	} else {
		return result.(*model.AIAgent), nil
	}
}

func (a aIAgentDo) FirstOrCreate() (*model.AIAgent, error) {
	if result, err := a.DO.FirstOrCreate(); err != nil {
		return nil, err
	} else {
		return result.(*model.AIAgent), nil
	}
}

func (a aIAgentDo) FindByPage(offset int, limit int) (result []*model.AIAgent, count int64, err error) {
	result, err = a.Offset(offset).Limit(limit).Find()
	if err != nil {
		return
	}

	if size := len(result); 0 < limit && 0 < size && size < limit {
		count = int64(size + offset)
		return
	}

	count, err = a.Offset(-1).Limit(-1).Count()
	return
}

func (a aIAgentDo) ScanByPage(result interface{}, offset int, limit int) (count int64, err error) {
	count, err = a.Count()
	if err != nil {
		return
	}

	err = a.Offset(offset).Limit(limit).Scan(result)
	return
}

func (a aIAgentDo) Scan(result interface{}) (err error) {
	return a.DO.Scan(result)
}

func (a aIAgentDo) Delete(models ...*model.AIAgent) (result gen.ResultInfo, err error) {
	return a.DO.Delete(models)
}

func (a *aIAgentDo) withDO(do gen.Dao) *aIAgentDo {
	a.DO = *do.(*gen.DO)
	return a
}
