// Code generated by gorm.io/gen. DO NOT EDIT.
// Code generated by gorm.io/gen. DO NOT EDIT.
// Code generated by gorm.io/gen. DO NOT EDIT.

package query

import (
	"context"
	"database/sql"

	"gorm.io/gorm"
	"gorm.io/gorm/clause"
	"gorm.io/gorm/schema"

	"gorm.io/gen"
	"gorm.io/gen/field"

	"gorm.io/plugin/dbresolver"

	"github.com/example/aichat/backend/models/generator/model"
)

func newAgentBind(db *gorm.DB, opts ...gen.DOOption) agentBind {
	_agentBind := agentBind{}

	_agentBind.agentBindDo.UseDB(db, opts...)
	_agentBind.agentBindDo.UseModel(&model.AgentBind{})

	tableName := _agentBind.agentBindDo.TableName()
	_agentBind.ALL = field.NewAsterisk(tableName)
	_agentBind.ID = field.NewInt64(tableName, "id")
	_agentBind.CreatedAt = field.NewField(tableName, "created_at")
	_agentBind.CreatedBy = field.NewInt64(tableName, "created_by")
	_agentBind.UpdatedAt = field.NewField(tableName, "updated_at")
	_agentBind.UpdatedBy = field.NewInt64(tableName, "updated_by")
	_agentBind.IsDeleted = field.NewUint(tableName, "is_deleted")
	_agentBind.DeletedAt = field.NewField(tableName, "deleted_at")
	_agentBind.DeletedBy = field.NewInt64(tableName, "deleted_by")
	_agentBind.AgentID = field.NewInt64(tableName, "agent_id")
	_agentBind.SubAgentID = field.NewInt64(tableName, "sub_agent_id")

	_agentBind.fillFieldMap()

	return _agentBind
}

type agentBind struct {
	agentBindDo

	ALL        field.Asterisk
	ID         field.Int64
	CreatedAt  field.Field
	CreatedBy  field.Int64
	UpdatedAt  field.Field
	UpdatedBy  field.Int64
	IsDeleted  field.Uint
	DeletedAt  field.Field
	DeletedBy  field.Int64
	AgentID    field.Int64
	SubAgentID field.Int64

	fieldMap map[string]field.Expr
}

func (a agentBind) Table(newTableName string) *agentBind {
	a.agentBindDo.UseTable(newTableName)
	return a.updateTableName(newTableName)
}

func (a agentBind) As(alias string) *agentBind {
	a.agentBindDo.DO = *(a.agentBindDo.As(alias).(*gen.DO))
	return a.updateTableName(alias)
}

func (a *agentBind) updateTableName(table string) *agentBind {
	a.ALL = field.NewAsterisk(table)
	a.ID = field.NewInt64(table, "id")
	a.CreatedAt = field.NewField(table, "created_at")
	a.CreatedBy = field.NewInt64(table, "created_by")
	a.UpdatedAt = field.NewField(table, "updated_at")
	a.UpdatedBy = field.NewInt64(table, "updated_by")
	a.IsDeleted = field.NewUint(table, "is_deleted")
	a.DeletedAt = field.NewField(table, "deleted_at")
	a.DeletedBy = field.NewInt64(table, "deleted_by")
	a.AgentID = field.NewInt64(table, "agent_id")
	a.SubAgentID = field.NewInt64(table, "sub_agent_id")

	a.fillFieldMap()

	return a
}

func (a *agentBind) GetFieldByName(fieldName string) (field.OrderExpr, bool) {
	_f, ok := a.fieldMap[fieldName]
	if !ok || _f == nil {
		return nil, false
	}
	_oe, ok := _f.(field.OrderExpr)
	return _oe, ok
}

func (a *agentBind) fillFieldMap() {
	a.fieldMap = make(map[string]field.Expr, 10)
	a.fieldMap["id"] = a.ID
	a.fieldMap["created_at"] = a.CreatedAt
	a.fieldMap["created_by"] = a.CreatedBy
	a.fieldMap["updated_at"] = a.UpdatedAt
	a.fieldMap["updated_by"] = a.UpdatedBy
	a.fieldMap["is_deleted"] = a.IsDeleted
	a.fieldMap["deleted_at"] = a.DeletedAt
	a.fieldMap["deleted_by"] = a.DeletedBy
	a.fieldMap["agent_id"] = a.AgentID
	a.fieldMap["sub_agent_id"] = a.SubAgentID
}

func (a agentBind) clone(db *gorm.DB) agentBind {
	a.agentBindDo.ReplaceConnPool(db.Statement.ConnPool)
	return a
}

func (a agentBind) replaceDB(db *gorm.DB) agentBind {
	a.agentBindDo.ReplaceDB(db)
	return a
}

type agentBindDo struct{ gen.DO }

type IAgentBindDo interface {
	gen.SubQuery
	Debug() IAgentBindDo
	WithContext(ctx context.Context) IAgentBindDo
	WithResult(fc func(tx gen.Dao)) gen.ResultInfo
	ReplaceDB(db *gorm.DB)
	ReadDB() IAgentBindDo
	WriteDB() IAgentBindDo
	As(alias string) gen.Dao
	Session(config *gorm.Session) IAgentBindDo
	Columns(cols ...field.Expr) gen.Columns
	Clauses(conds ...clause.Expression) IAgentBindDo
	Not(conds ...gen.Condition) IAgentBindDo
	Or(conds ...gen.Condition) IAgentBindDo
	Select(conds ...field.Expr) IAgentBindDo
	Where(conds ...gen.Condition) IAgentBindDo
	Order(conds ...field.Expr) IAgentBindDo
	Distinct(cols ...field.Expr) IAgentBindDo
	Omit(cols ...field.Expr) IAgentBindDo
	Join(table schema.Tabler, on ...field.Expr) IAgentBindDo
	LeftJoin(table schema.Tabler, on ...field.Expr) IAgentBindDo
	RightJoin(table schema.Tabler, on ...field.Expr) IAgentBindDo
	Group(cols ...field.Expr) IAgentBindDo
	Having(conds ...gen.Condition) IAgentBindDo
	Limit(limit int) IAgentBindDo
	Offset(offset int) IAgentBindDo
	Count() (count int64, err error)
	Scopes(funcs ...func(gen.Dao) gen.Dao) IAgentBindDo
	Unscoped() IAgentBindDo
	Create(values ...*model.AgentBind) error
	CreateInBatches(values []*model.AgentBind, batchSize int) error
	Save(values ...*model.AgentBind) error
	First() (*model.AgentBind, error)
	Take() (*model.AgentBind, error)
	Last() (*model.AgentBind, error)
	Find() ([]*model.AgentBind, error)
	FindInBatch(batchSize int, fc func(tx gen.Dao, batch int) error) (results []*model.AgentBind, err error)
	FindInBatches(result *[]*model.AgentBind, batchSize int, fc func(tx gen.Dao, batch int) error) error
	Pluck(column field.Expr, dest interface{}) error
	Delete(...*model.AgentBind) (info gen.ResultInfo, err error)
	Update(column field.Expr, value interface{}) (info gen.ResultInfo, err error)
	UpdateSimple(columns ...field.AssignExpr) (info gen.ResultInfo, err error)
	Updates(value interface{}) (info gen.ResultInfo, err error)
	UpdateColumn(column field.Expr, value interface{}) (info gen.ResultInfo, err error)
	UpdateColumnSimple(columns ...field.AssignExpr) (info gen.ResultInfo, err error)
	UpdateColumns(value interface{}) (info gen.ResultInfo, err error)
	UpdateFrom(q gen.SubQuery) gen.Dao
	Attrs(attrs ...field.AssignExpr) IAgentBindDo
	Assign(attrs ...field.AssignExpr) IAgentBindDo
	Joins(fields ...field.RelationField) IAgentBindDo
	Preload(fields ...field.RelationField) IAgentBindDo
	FirstOrInit() (*model.AgentBind, error)
	FirstOrCreate() (*model.AgentBind, error)
	FindByPage(offset int, limit int) (result []*model.AgentBind, count int64, err error)
	ScanByPage(result interface{}, offset int, limit int) (count int64, err error)
	Rows() (*sql.Rows, error)
	Row() *sql.Row
	Scan(result interface{}) (err error)
	Returning(value interface{}, columns ...string) IAgentBindDo
	UnderlyingDB() *gorm.DB
	schema.Tabler
}

func (a agentBindDo) Debug() IAgentBindDo {
	return a.withDO(a.DO.Debug())
}

func (a agentBindDo) WithContext(ctx context.Context) IAgentBindDo {
	return a.withDO(a.DO.WithContext(ctx))
}

func (a agentBindDo) ReadDB() IAgentBindDo {
	return a.Clauses(dbresolver.Read)
}

func (a agentBindDo) WriteDB() IAgentBindDo {
	return a.Clauses(dbresolver.Write)
}

func (a agentBindDo) Session(config *gorm.Session) IAgentBindDo {
	return a.withDO(a.DO.Session(config))
}

func (a agentBindDo) Clauses(conds ...clause.Expression) IAgentBindDo {
	return a.withDO(a.DO.Clauses(conds...))
}

func (a agentBindDo) Returning(value interface{}, columns ...string) IAgentBindDo {
	return a.withDO(a.DO.Returning(value, columns...))
}

func (a agentBindDo) Not(conds ...gen.Condition) IAgentBindDo {
	return a.withDO(a.DO.Not(conds...))
}

func (a agentBindDo) Or(conds ...gen.Condition) IAgentBindDo {
	return a.withDO(a.DO.Or(conds...))
}

func (a agentBindDo) Select(conds ...field.Expr) IAgentBindDo {
	return a.withDO(a.DO.Select(conds...))
}

func (a agentBindDo) Where(conds ...gen.Condition) IAgentBindDo {
	return a.withDO(a.DO.Where(conds...))
}

func (a agentBindDo) Order(conds ...field.Expr) IAgentBindDo {
	return a.withDO(a.DO.Order(conds...))
}

func (a agentBindDo) Distinct(cols ...field.Expr) IAgentBindDo {
	return a.withDO(a.DO.Distinct(cols...))
}

func (a agentBindDo) Omit(cols ...field.Expr) IAgentBindDo {
	return a.withDO(a.DO.Omit(cols...))
}

func (a agentBindDo) Join(table schema.Tabler, on ...field.Expr) IAgentBindDo {
	return a.withDO(a.DO.Join(table, on...))
}

func (a agentBindDo) LeftJoin(table schema.Tabler, on ...field.Expr) IAgentBindDo {
	return a.withDO(a.DO.LeftJoin(table, on...))
}

func (a agentBindDo) RightJoin(table schema.Tabler, on ...field.Expr) IAgentBindDo {
	return a.withDO(a.DO.RightJoin(table, on...))
}

func (a agentBindDo) Group(cols ...field.Expr) IAgentBindDo {
	return a.withDO(a.DO.Group(cols...))
}

func (a agentBindDo) Having(conds ...gen.Condition) IAgentBindDo {
	return a.withDO(a.DO.Having(conds...))
}

func (a agentBindDo) Limit(limit int) IAgentBindDo {
	return a.withDO(a.DO.Limit(limit))
}

func (a agentBindDo) Offset(offset int) IAgentBindDo {
	return a.withDO(a.DO.Offset(offset))
}

func (a agentBindDo) Scopes(funcs ...func(gen.Dao) gen.Dao) IAgentBindDo {
	return a.withDO(a.DO.Scopes(funcs...))
}

func (a agentBindDo) Unscoped() IAgentBindDo {
	return a.withDO(a.DO.Unscoped())
}

func (a agentBindDo) Create(values ...*model.AgentBind) error {
	if len(values) == 0 {
		return nil
	}
	return a.DO.Create(values)
}

func (a agentBindDo) CreateInBatches(values []*model.AgentBind, batchSize int) error {
	return a.DO.CreateInBatches(values, batchSize)
}

// Save : !!! underlying implementation is different with GORM
// The method is equivalent to executing the statement: db.Clauses(clause.OnConflict{UpdateAll: true}).Create(values)
func (a agentBindDo) Save(values ...*model.AgentBind) error {
	if len(values) == 0 {
		return nil
	}
	return a.DO.Save(values)
}

func (a agentBindDo) First() (*model.AgentBind, error) {
	if result, err := a.DO.First(); err != nil {
		return nil, err
	} else {
		return result.(*model.AgentBind), nil
	}
}

func (a agentBindDo) Take() (*model.AgentBind, error) {
	if result, err := a.DO.Take(); err != nil {
		return nil, err
	} else {
		return result.(*model.AgentBind), nil
	}
}

func (a agentBindDo) Last() (*model.AgentBind, error) {
	if result, err := a.DO.Last(); err != nil {
		return nil, err
	} else {
		return result.(*model.AgentBind), nil
	}
}

func (a agentBindDo) Find() ([]*model.AgentBind, error) {
	result, err := a.DO.Find()
	return result.([]*model.AgentBind), err
}

func (a agentBindDo) FindInBatch(batchSize int, fc func(tx gen.Dao, batch int) error) (results []*model.AgentBind, err error) {
	buf := make([]*model.AgentBind, 0, batchSize)
	err = a.DO.FindInBatches(&buf, batchSize, func(tx gen.Dao, batch int) error {
		defer func() { results = append(results, buf...) }()
		return fc(tx, batch)
	})
	return results, err
}

func (a agentBindDo) FindInBatches(result *[]*model.AgentBind, batchSize int, fc func(tx gen.Dao, batch int) error) error {
	return a.DO.FindInBatches(result, batchSize, fc)
}

func (a agentBindDo) Attrs(attrs ...field.AssignExpr) IAgentBindDo {
	return a.withDO(a.DO.Attrs(attrs...))
}

func (a agentBindDo) Assign(attrs ...field.AssignExpr) IAgentBindDo {
	return a.withDO(a.DO.Assign(attrs...))
}

func (a agentBindDo) Joins(fields ...field.RelationField) IAgentBindDo {
	for _, _f := range fields {
		a = *a.withDO(a.DO.Joins(_f))
	}
	return &a
}

func (a agentBindDo) Preload(fields ...field.RelationField) IAgentBindDo {
	for _, _f := range fields {
		a = *a.withDO(a.DO.Preload(_f))
	}
	return &a
}

func (a agentBindDo) FirstOrInit() (*model.AgentBind, error) {
	if result, err := a.DO.FirstOrInit(); err != nil {
		return nil, err
	} else {
		return result.(*model.AgentBind), nil
	}
}

func (a agentBindDo) FirstOrCreate() (*model.AgentBind, error) {
	if result, err := a.DO.FirstOrCreate(); err != nil {
		return nil, err
	} else {
		return result.(*model.AgentBind), nil
	}
}

func (a agentBindDo) FindByPage(offset int, limit int) (result []*model.AgentBind, count int64, err error) {
	result, err = a.Offset(offset).Limit(limit).Find()
	if err != nil {
		return
	}

	if size := len(result); 0 < limit && 0 < size && size < limit {
		count = int64(size + offset)
		return
	}

	count, err = a.Offset(-1).Limit(-1).Count()
	return
}

func (a agentBindDo) ScanByPage(result interface{}, offset int, limit int) (count int64, err error) {
	count, err = a.Count()
	if err != nil {
		return
	}

	err = a.Offset(offset).Limit(limit).Scan(result)
	return
}

func (a agentBindDo) Scan(result interface{}) (err error) {
	return a.DO.Scan(result)
}

func (a agentBindDo) Delete(models ...*model.AgentBind) (result gen.ResultInfo, err error) {
	return a.DO.Delete(models)
}

func (a *agentBindDo) withDO(do gen.Dao) *agentBindDo {
	a.DO = *do.(*gen.DO)
	return a
}
