// Code generated by gorm.io/gen. DO NOT EDIT.
// Code generated by gorm.io/gen. DO NOT EDIT.
// Code generated by gorm.io/gen. DO NOT EDIT.

package query

import (
	"context"
	"database/sql"

	"gorm.io/gorm"
	"gorm.io/gorm/clause"
	"gorm.io/gorm/schema"

	"gorm.io/gen"
	"gorm.io/gen/field"

	"gorm.io/plugin/dbresolver"

	"github.com/example/aichat/backend/models/generator/model"
)

func newAIModel(db *gorm.DB, opts ...gen.DOOption) aIModel {
	_aIModel := aIModel{}

	_aIModel.aIModelDo.UseDB(db, opts...)
	_aIModel.aIModelDo.UseModel(&model.AIModel{})

	tableName := _aIModel.aIModelDo.TableName()
	_aIModel.ALL = field.NewAsterisk(tableName)
	_aIModel.ID = field.NewInt64(tableName, "id")
	_aIModel.CreatedAt = field.NewField(tableName, "created_at")
	_aIModel.CreatedBy = field.NewInt64(tableName, "created_by")
	_aIModel.UpdatedAt = field.NewField(tableName, "updated_at")
	_aIModel.UpdatedBy = field.NewInt64(tableName, "updated_by")
	_aIModel.IsDeleted = field.NewUint(tableName, "is_deleted")
	_aIModel.DeletedAt = field.NewField(tableName, "deleted_at")
	_aIModel.DeletedBy = field.NewInt64(tableName, "deleted_by")
	_aIModel.Category = field.NewUint8(tableName, "category")
	_aIModel.ModelType = field.NewString(tableName, "model_type")
	_aIModel.ModelName = field.NewString(tableName, "model_name")
	_aIModel.APIKey = field.NewString(tableName, "api_key")
	_aIModel.BaseURL = field.NewString(tableName, "base_url")
	_aIModel.MaxTokens = field.NewInt(tableName, "max_tokens")
	_aIModel.Temperature = field.NewFloat32(tableName, "temperature")
	_aIModel.TopP = field.NewFloat32(tableName, "top_p")
	_aIModel.PriceType = field.NewUint8(tableName, "price_type")
	_aIModel.Price = field.NewFloat32(tableName, "price")
	_aIModel.Supplier = field.NewString(tableName, "supplier")
	_aIModel.Description = field.NewString(tableName, "description")
	_aIModel.Status = field.NewUint8(tableName, "status")
	_aIModel.IsDefault = field.NewUint8(tableName, "is_default")

	_aIModel.fillFieldMap()

	return _aIModel
}

type aIModel struct {
	aIModelDo

	ALL         field.Asterisk
	ID          field.Int64
	CreatedAt   field.Field
	CreatedBy   field.Int64
	UpdatedAt   field.Field
	UpdatedBy   field.Int64
	IsDeleted   field.Uint
	DeletedAt   field.Field
	DeletedBy   field.Int64
	Category    field.Uint8
	ModelType   field.String
	ModelName   field.String
	APIKey      field.String
	BaseURL     field.String
	MaxTokens   field.Int
	Temperature field.Float32
	TopP        field.Float32
	PriceType   field.Uint8
	Price       field.Float32
	Supplier    field.String
	Description field.String
	Status      field.Uint8
	IsDefault   field.Uint8

	fieldMap map[string]field.Expr
}

func (a aIModel) Table(newTableName string) *aIModel {
	a.aIModelDo.UseTable(newTableName)
	return a.updateTableName(newTableName)
}

func (a aIModel) As(alias string) *aIModel {
	a.aIModelDo.DO = *(a.aIModelDo.As(alias).(*gen.DO))
	return a.updateTableName(alias)
}

func (a *aIModel) updateTableName(table string) *aIModel {
	a.ALL = field.NewAsterisk(table)
	a.ID = field.NewInt64(table, "id")
	a.CreatedAt = field.NewField(table, "created_at")
	a.CreatedBy = field.NewInt64(table, "created_by")
	a.UpdatedAt = field.NewField(table, "updated_at")
	a.UpdatedBy = field.NewInt64(table, "updated_by")
	a.IsDeleted = field.NewUint(table, "is_deleted")
	a.DeletedAt = field.NewField(table, "deleted_at")
	a.DeletedBy = field.NewInt64(table, "deleted_by")
	a.Category = field.NewUint8(table, "category")
	a.ModelType = field.NewString(table, "model_type")
	a.ModelName = field.NewString(table, "model_name")
	a.APIKey = field.NewString(table, "api_key")
	a.BaseURL = field.NewString(table, "base_url")
	a.MaxTokens = field.NewInt(table, "max_tokens")
	a.Temperature = field.NewFloat32(table, "temperature")
	a.TopP = field.NewFloat32(table, "top_p")
	a.PriceType = field.NewUint8(table, "price_type")
	a.Price = field.NewFloat32(table, "price")
	a.Supplier = field.NewString(table, "supplier")
	a.Description = field.NewString(table, "description")
	a.Status = field.NewUint8(table, "status")
	a.IsDefault = field.NewUint8(table, "is_default")

	a.fillFieldMap()

	return a
}

func (a *aIModel) GetFieldByName(fieldName string) (field.OrderExpr, bool) {
	_f, ok := a.fieldMap[fieldName]
	if !ok || _f == nil {
		return nil, false
	}
	_oe, ok := _f.(field.OrderExpr)
	return _oe, ok
}

func (a *aIModel) fillFieldMap() {
	a.fieldMap = make(map[string]field.Expr, 22)
	a.fieldMap["id"] = a.ID
	a.fieldMap["created_at"] = a.CreatedAt
	a.fieldMap["created_by"] = a.CreatedBy
	a.fieldMap["updated_at"] = a.UpdatedAt
	a.fieldMap["updated_by"] = a.UpdatedBy
	a.fieldMap["is_deleted"] = a.IsDeleted
	a.fieldMap["deleted_at"] = a.DeletedAt
	a.fieldMap["deleted_by"] = a.DeletedBy
	a.fieldMap["category"] = a.Category
	a.fieldMap["model_type"] = a.ModelType
	a.fieldMap["model_name"] = a.ModelName
	a.fieldMap["api_key"] = a.APIKey
	a.fieldMap["base_url"] = a.BaseURL
	a.fieldMap["max_tokens"] = a.MaxTokens
	a.fieldMap["temperature"] = a.Temperature
	a.fieldMap["top_p"] = a.TopP
	a.fieldMap["price_type"] = a.PriceType
	a.fieldMap["price"] = a.Price
	a.fieldMap["supplier"] = a.Supplier
	a.fieldMap["description"] = a.Description
	a.fieldMap["status"] = a.Status
	a.fieldMap["is_default"] = a.IsDefault
}

func (a aIModel) clone(db *gorm.DB) aIModel {
	a.aIModelDo.ReplaceConnPool(db.Statement.ConnPool)
	return a
}

func (a aIModel) replaceDB(db *gorm.DB) aIModel {
	a.aIModelDo.ReplaceDB(db)
	return a
}

type aIModelDo struct{ gen.DO }

type IAIModelDo interface {
	gen.SubQuery
	Debug() IAIModelDo
	WithContext(ctx context.Context) IAIModelDo
	WithResult(fc func(tx gen.Dao)) gen.ResultInfo
	ReplaceDB(db *gorm.DB)
	ReadDB() IAIModelDo
	WriteDB() IAIModelDo
	As(alias string) gen.Dao
	Session(config *gorm.Session) IAIModelDo
	Columns(cols ...field.Expr) gen.Columns
	Clauses(conds ...clause.Expression) IAIModelDo
	Not(conds ...gen.Condition) IAIModelDo
	Or(conds ...gen.Condition) IAIModelDo
	Select(conds ...field.Expr) IAIModelDo
	Where(conds ...gen.Condition) IAIModelDo
	Order(conds ...field.Expr) IAIModelDo
	Distinct(cols ...field.Expr) IAIModelDo
	Omit(cols ...field.Expr) IAIModelDo
	Join(table schema.Tabler, on ...field.Expr) IAIModelDo
	LeftJoin(table schema.Tabler, on ...field.Expr) IAIModelDo
	RightJoin(table schema.Tabler, on ...field.Expr) IAIModelDo
	Group(cols ...field.Expr) IAIModelDo
	Having(conds ...gen.Condition) IAIModelDo
	Limit(limit int) IAIModelDo
	Offset(offset int) IAIModelDo
	Count() (count int64, err error)
	Scopes(funcs ...func(gen.Dao) gen.Dao) IAIModelDo
	Unscoped() IAIModelDo
	Create(values ...*model.AIModel) error
	CreateInBatches(values []*model.AIModel, batchSize int) error
	Save(values ...*model.AIModel) error
	First() (*model.AIModel, error)
	Take() (*model.AIModel, error)
	Last() (*model.AIModel, error)
	Find() ([]*model.AIModel, error)
	FindInBatch(batchSize int, fc func(tx gen.Dao, batch int) error) (results []*model.AIModel, err error)
	FindInBatches(result *[]*model.AIModel, batchSize int, fc func(tx gen.Dao, batch int) error) error
	Pluck(column field.Expr, dest interface{}) error
	Delete(...*model.AIModel) (info gen.ResultInfo, err error)
	Update(column field.Expr, value interface{}) (info gen.ResultInfo, err error)
	UpdateSimple(columns ...field.AssignExpr) (info gen.ResultInfo, err error)
	Updates(value interface{}) (info gen.ResultInfo, err error)
	UpdateColumn(column field.Expr, value interface{}) (info gen.ResultInfo, err error)
	UpdateColumnSimple(columns ...field.AssignExpr) (info gen.ResultInfo, err error)
	UpdateColumns(value interface{}) (info gen.ResultInfo, err error)
	UpdateFrom(q gen.SubQuery) gen.Dao
	Attrs(attrs ...field.AssignExpr) IAIModelDo
	Assign(attrs ...field.AssignExpr) IAIModelDo
	Joins(fields ...field.RelationField) IAIModelDo
	Preload(fields ...field.RelationField) IAIModelDo
	FirstOrInit() (*model.AIModel, error)
	FirstOrCreate() (*model.AIModel, error)
	FindByPage(offset int, limit int) (result []*model.AIModel, count int64, err error)
	ScanByPage(result interface{}, offset int, limit int) (count int64, err error)
	Rows() (*sql.Rows, error)
	Row() *sql.Row
	Scan(result interface{}) (err error)
	Returning(value interface{}, columns ...string) IAIModelDo
	UnderlyingDB() *gorm.DB
	schema.Tabler
}

func (a aIModelDo) Debug() IAIModelDo {
	return a.withDO(a.DO.Debug())
}

func (a aIModelDo) WithContext(ctx context.Context) IAIModelDo {
	return a.withDO(a.DO.WithContext(ctx))
}

func (a aIModelDo) ReadDB() IAIModelDo {
	return a.Clauses(dbresolver.Read)
}

func (a aIModelDo) WriteDB() IAIModelDo {
	return a.Clauses(dbresolver.Write)
}

func (a aIModelDo) Session(config *gorm.Session) IAIModelDo {
	return a.withDO(a.DO.Session(config))
}

func (a aIModelDo) Clauses(conds ...clause.Expression) IAIModelDo {
	return a.withDO(a.DO.Clauses(conds...))
}

func (a aIModelDo) Returning(value interface{}, columns ...string) IAIModelDo {
	return a.withDO(a.DO.Returning(value, columns...))
}

func (a aIModelDo) Not(conds ...gen.Condition) IAIModelDo {
	return a.withDO(a.DO.Not(conds...))
}

func (a aIModelDo) Or(conds ...gen.Condition) IAIModelDo {
	return a.withDO(a.DO.Or(conds...))
}

func (a aIModelDo) Select(conds ...field.Expr) IAIModelDo {
	return a.withDO(a.DO.Select(conds...))
}

func (a aIModelDo) Where(conds ...gen.Condition) IAIModelDo {
	return a.withDO(a.DO.Where(conds...))
}

func (a aIModelDo) Order(conds ...field.Expr) IAIModelDo {
	return a.withDO(a.DO.Order(conds...))
}

func (a aIModelDo) Distinct(cols ...field.Expr) IAIModelDo {
	return a.withDO(a.DO.Distinct(cols...))
}

func (a aIModelDo) Omit(cols ...field.Expr) IAIModelDo {
	return a.withDO(a.DO.Omit(cols...))
}

func (a aIModelDo) Join(table schema.Tabler, on ...field.Expr) IAIModelDo {
	return a.withDO(a.DO.Join(table, on...))
}

func (a aIModelDo) LeftJoin(table schema.Tabler, on ...field.Expr) IAIModelDo {
	return a.withDO(a.DO.LeftJoin(table, on...))
}

func (a aIModelDo) RightJoin(table schema.Tabler, on ...field.Expr) IAIModelDo {
	return a.withDO(a.DO.RightJoin(table, on...))
}

func (a aIModelDo) Group(cols ...field.Expr) IAIModelDo {
	return a.withDO(a.DO.Group(cols...))
}

func (a aIModelDo) Having(conds ...gen.Condition) IAIModelDo {
	return a.withDO(a.DO.Having(conds...))
}

func (a aIModelDo) Limit(limit int) IAIModelDo {
	return a.withDO(a.DO.Limit(limit))
}

func (a aIModelDo) Offset(offset int) IAIModelDo {
	return a.withDO(a.DO.Offset(offset))
}

func (a aIModelDo) Scopes(funcs ...func(gen.Dao) gen.Dao) IAIModelDo {
	return a.withDO(a.DO.Scopes(funcs...))
}

func (a aIModelDo) Unscoped() IAIModelDo {
	return a.withDO(a.DO.Unscoped())
}

func (a aIModelDo) Create(values ...*model.AIModel) error {
	if len(values) == 0 {
		return nil
	}
	return a.DO.Create(values)
}

func (a aIModelDo) CreateInBatches(values []*model.AIModel, batchSize int) error {
	return a.DO.CreateInBatches(values, batchSize)
}

// Save : !!! underlying implementation is different with GORM
// The method is equivalent to executing the statement: db.Clauses(clause.OnConflict{UpdateAll: true}).Create(values)
func (a aIModelDo) Save(values ...*model.AIModel) error {
	if len(values) == 0 {
		return nil
	}
	return a.DO.Save(values)
}

func (a aIModelDo) First() (*model.AIModel, error) {
	if result, err := a.DO.First(); err != nil {
		return nil, err
	} else {
		return result.(*model.AIModel), nil
	}
}

func (a aIModelDo) Take() (*model.AIModel, error) {
	if result, err := a.DO.Take(); err != nil {
		return nil, err
	} else {
		return result.(*model.AIModel), nil
	}
}

func (a aIModelDo) Last() (*model.AIModel, error) {
	if result, err := a.DO.Last(); err != nil {
		return nil, err
	} else {
		return result.(*model.AIModel), nil
	}
}

func (a aIModelDo) Find() ([]*model.AIModel, error) {
	result, err := a.DO.Find()
	return result.([]*model.AIModel), err
}

func (a aIModelDo) FindInBatch(batchSize int, fc func(tx gen.Dao, batch int) error) (results []*model.AIModel, err error) {
	buf := make([]*model.AIModel, 0, batchSize)
	err = a.DO.FindInBatches(&buf, batchSize, func(tx gen.Dao, batch int) error {
		defer func() { results = append(results, buf...) }()
		return fc(tx, batch)
	})
	return results, err
}

func (a aIModelDo) FindInBatches(result *[]*model.AIModel, batchSize int, fc func(tx gen.Dao, batch int) error) error {
	return a.DO.FindInBatches(result, batchSize, fc)
}

func (a aIModelDo) Attrs(attrs ...field.AssignExpr) IAIModelDo {
	return a.withDO(a.DO.Attrs(attrs...))
}

func (a aIModelDo) Assign(attrs ...field.AssignExpr) IAIModelDo {
	return a.withDO(a.DO.Assign(attrs...))
}

func (a aIModelDo) Joins(fields ...field.RelationField) IAIModelDo {
	for _, _f := range fields {
		a = *a.withDO(a.DO.Joins(_f))
	}
	return &a
}

func (a aIModelDo) Preload(fields ...field.RelationField) IAIModelDo {
	for _, _f := range fields {
		a = *a.withDO(a.DO.Preload(_f))
	}
	return &a
}

func (a aIModelDo) FirstOrInit() (*model.AIModel, error) {
	if result, err := a.DO.FirstOrInit(); err != nil {
		return nil, err
	} else {
		return result.(*model.AIModel), nil
	}
}

func (a aIModelDo) FirstOrCreate() (*model.AIModel, error) {
	if result, err := a.DO.FirstOrCreate(); err != nil {
		return nil, err
	} else {
		return result.(*model.AIModel), nil
	}
}

func (a aIModelDo) FindByPage(offset int, limit int) (result []*model.AIModel, count int64, err error) {
	result, err = a.Offset(offset).Limit(limit).Find()
	if err != nil {
		return
	}

	if size := len(result); 0 < limit && 0 < size && size < limit {
		count = int64(size + offset)
		return
	}

	count, err = a.Offset(-1).Limit(-1).Count()
	return
}

func (a aIModelDo) ScanByPage(result interface{}, offset int, limit int) (count int64, err error) {
	count, err = a.Count()
	if err != nil {
		return
	}

	err = a.Offset(offset).Limit(limit).Scan(result)
	return
}

func (a aIModelDo) Scan(result interface{}) (err error) {
	return a.DO.Scan(result)
}

func (a aIModelDo) Delete(models ...*model.AIModel) (result gen.ResultInfo, err error) {
	return a.DO.Delete(models)
}

func (a *aIModelDo) withDO(do gen.Dao) *aIModelDo {
	a.DO = *do.(*gen.DO)
	return a
}
