// Code generated by gorm.io/gen. DO NOT EDIT.
// Code generated by gorm.io/gen. DO NOT EDIT.
// Code generated by gorm.io/gen. DO NOT EDIT.

package query

import (
	"context"
	"database/sql"

	"gorm.io/gorm"
	"gorm.io/gorm/clause"
	"gorm.io/gorm/schema"

	"gorm.io/gen"
	"gorm.io/gen/field"

	"gorm.io/plugin/dbresolver"

	"github.com/example/aichat/backend/models/generator/model"
)

func newAIToolAgentBind(db *gorm.DB, opts ...gen.DOOption) aIToolAgentBind {
	_aIToolAgentBind := aIToolAgentBind{}

	_aIToolAgentBind.aIToolAgentBindDo.UseDB(db, opts...)
	_aIToolAgentBind.aIToolAgentBindDo.UseModel(&model.AIToolAgentBind{})

	tableName := _aIToolAgentBind.aIToolAgentBindDo.TableName()
	_aIToolAgentBind.ALL = field.NewAsterisk(tableName)
	_aIToolAgentBind.ID = field.NewInt64(tableName, "id")
	_aIToolAgentBind.CreatedAt = field.NewField(tableName, "created_at")
	_aIToolAgentBind.CreatedBy = field.NewInt64(tableName, "created_by")
	_aIToolAgentBind.UpdatedAt = field.NewField(tableName, "updated_at")
	_aIToolAgentBind.UpdatedBy = field.NewInt64(tableName, "updated_by")
	_aIToolAgentBind.IsDeleted = field.NewUint(tableName, "is_deleted")
	_aIToolAgentBind.DeletedAt = field.NewField(tableName, "deleted_at")
	_aIToolAgentBind.DeletedBy = field.NewInt64(tableName, "deleted_by")
	_aIToolAgentBind.AgentID = field.NewUint64(tableName, "agent_id")
	_aIToolAgentBind.ToolCode = field.NewString(tableName, "tool_code")

	_aIToolAgentBind.fillFieldMap()

	return _aIToolAgentBind
}

type aIToolAgentBind struct {
	aIToolAgentBindDo

	ALL       field.Asterisk
	ID        field.Int64
	CreatedAt field.Field
	CreatedBy field.Int64
	UpdatedAt field.Field
	UpdatedBy field.Int64
	IsDeleted field.Uint
	DeletedAt field.Field
	DeletedBy field.Int64
	AgentID   field.Uint64 // 'AgentID'
	ToolCode  field.String // '工具Code'

	fieldMap map[string]field.Expr
}

func (a aIToolAgentBind) Table(newTableName string) *aIToolAgentBind {
	a.aIToolAgentBindDo.UseTable(newTableName)
	return a.updateTableName(newTableName)
}

func (a aIToolAgentBind) As(alias string) *aIToolAgentBind {
	a.aIToolAgentBindDo.DO = *(a.aIToolAgentBindDo.As(alias).(*gen.DO))
	return a.updateTableName(alias)
}

func (a *aIToolAgentBind) updateTableName(table string) *aIToolAgentBind {
	a.ALL = field.NewAsterisk(table)
	a.ID = field.NewInt64(table, "id")
	a.CreatedAt = field.NewField(table, "created_at")
	a.CreatedBy = field.NewInt64(table, "created_by")
	a.UpdatedAt = field.NewField(table, "updated_at")
	a.UpdatedBy = field.NewInt64(table, "updated_by")
	a.IsDeleted = field.NewUint(table, "is_deleted")
	a.DeletedAt = field.NewField(table, "deleted_at")
	a.DeletedBy = field.NewInt64(table, "deleted_by")
	a.AgentID = field.NewUint64(table, "agent_id")
	a.ToolCode = field.NewString(table, "tool_code")

	a.fillFieldMap()

	return a
}

func (a *aIToolAgentBind) GetFieldByName(fieldName string) (field.OrderExpr, bool) {
	_f, ok := a.fieldMap[fieldName]
	if !ok || _f == nil {
		return nil, false
	}
	_oe, ok := _f.(field.OrderExpr)
	return _oe, ok
}

func (a *aIToolAgentBind) fillFieldMap() {
	a.fieldMap = make(map[string]field.Expr, 10)
	a.fieldMap["id"] = a.ID
	a.fieldMap["created_at"] = a.CreatedAt
	a.fieldMap["created_by"] = a.CreatedBy
	a.fieldMap["updated_at"] = a.UpdatedAt
	a.fieldMap["updated_by"] = a.UpdatedBy
	a.fieldMap["is_deleted"] = a.IsDeleted
	a.fieldMap["deleted_at"] = a.DeletedAt
	a.fieldMap["deleted_by"] = a.DeletedBy
	a.fieldMap["agent_id"] = a.AgentID
	a.fieldMap["tool_code"] = a.ToolCode
}

func (a aIToolAgentBind) clone(db *gorm.DB) aIToolAgentBind {
	a.aIToolAgentBindDo.ReplaceConnPool(db.Statement.ConnPool)
	return a
}

func (a aIToolAgentBind) replaceDB(db *gorm.DB) aIToolAgentBind {
	a.aIToolAgentBindDo.ReplaceDB(db)
	return a
}

type aIToolAgentBindDo struct{ gen.DO }

type IAIToolAgentBindDo interface {
	gen.SubQuery
	Debug() IAIToolAgentBindDo
	WithContext(ctx context.Context) IAIToolAgentBindDo
	WithResult(fc func(tx gen.Dao)) gen.ResultInfo
	ReplaceDB(db *gorm.DB)
	ReadDB() IAIToolAgentBindDo
	WriteDB() IAIToolAgentBindDo
	As(alias string) gen.Dao
	Session(config *gorm.Session) IAIToolAgentBindDo
	Columns(cols ...field.Expr) gen.Columns
	Clauses(conds ...clause.Expression) IAIToolAgentBindDo
	Not(conds ...gen.Condition) IAIToolAgentBindDo
	Or(conds ...gen.Condition) IAIToolAgentBindDo
	Select(conds ...field.Expr) IAIToolAgentBindDo
	Where(conds ...gen.Condition) IAIToolAgentBindDo
	Order(conds ...field.Expr) IAIToolAgentBindDo
	Distinct(cols ...field.Expr) IAIToolAgentBindDo
	Omit(cols ...field.Expr) IAIToolAgentBindDo
	Join(table schema.Tabler, on ...field.Expr) IAIToolAgentBindDo
	LeftJoin(table schema.Tabler, on ...field.Expr) IAIToolAgentBindDo
	RightJoin(table schema.Tabler, on ...field.Expr) IAIToolAgentBindDo
	Group(cols ...field.Expr) IAIToolAgentBindDo
	Having(conds ...gen.Condition) IAIToolAgentBindDo
	Limit(limit int) IAIToolAgentBindDo
	Offset(offset int) IAIToolAgentBindDo
	Count() (count int64, err error)
	Scopes(funcs ...func(gen.Dao) gen.Dao) IAIToolAgentBindDo
	Unscoped() IAIToolAgentBindDo
	Create(values ...*model.AIToolAgentBind) error
	CreateInBatches(values []*model.AIToolAgentBind, batchSize int) error
	Save(values ...*model.AIToolAgentBind) error
	First() (*model.AIToolAgentBind, error)
	Take() (*model.AIToolAgentBind, error)
	Last() (*model.AIToolAgentBind, error)
	Find() ([]*model.AIToolAgentBind, error)
	FindInBatch(batchSize int, fc func(tx gen.Dao, batch int) error) (results []*model.AIToolAgentBind, err error)
	FindInBatches(result *[]*model.AIToolAgentBind, batchSize int, fc func(tx gen.Dao, batch int) error) error
	Pluck(column field.Expr, dest interface{}) error
	Delete(...*model.AIToolAgentBind) (info gen.ResultInfo, err error)
	Update(column field.Expr, value interface{}) (info gen.ResultInfo, err error)
	UpdateSimple(columns ...field.AssignExpr) (info gen.ResultInfo, err error)
	Updates(value interface{}) (info gen.ResultInfo, err error)
	UpdateColumn(column field.Expr, value interface{}) (info gen.ResultInfo, err error)
	UpdateColumnSimple(columns ...field.AssignExpr) (info gen.ResultInfo, err error)
	UpdateColumns(value interface{}) (info gen.ResultInfo, err error)
	UpdateFrom(q gen.SubQuery) gen.Dao
	Attrs(attrs ...field.AssignExpr) IAIToolAgentBindDo
	Assign(attrs ...field.AssignExpr) IAIToolAgentBindDo
	Joins(fields ...field.RelationField) IAIToolAgentBindDo
	Preload(fields ...field.RelationField) IAIToolAgentBindDo
	FirstOrInit() (*model.AIToolAgentBind, error)
	FirstOrCreate() (*model.AIToolAgentBind, error)
	FindByPage(offset int, limit int) (result []*model.AIToolAgentBind, count int64, err error)
	ScanByPage(result interface{}, offset int, limit int) (count int64, err error)
	Rows() (*sql.Rows, error)
	Row() *sql.Row
	Scan(result interface{}) (err error)
	Returning(value interface{}, columns ...string) IAIToolAgentBindDo
	UnderlyingDB() *gorm.DB
	schema.Tabler
}

func (a aIToolAgentBindDo) Debug() IAIToolAgentBindDo {
	return a.withDO(a.DO.Debug())
}

func (a aIToolAgentBindDo) WithContext(ctx context.Context) IAIToolAgentBindDo {
	return a.withDO(a.DO.WithContext(ctx))
}

func (a aIToolAgentBindDo) ReadDB() IAIToolAgentBindDo {
	return a.Clauses(dbresolver.Read)
}

func (a aIToolAgentBindDo) WriteDB() IAIToolAgentBindDo {
	return a.Clauses(dbresolver.Write)
}

func (a aIToolAgentBindDo) Session(config *gorm.Session) IAIToolAgentBindDo {
	return a.withDO(a.DO.Session(config))
}

func (a aIToolAgentBindDo) Clauses(conds ...clause.Expression) IAIToolAgentBindDo {
	return a.withDO(a.DO.Clauses(conds...))
}

func (a aIToolAgentBindDo) Returning(value interface{}, columns ...string) IAIToolAgentBindDo {
	return a.withDO(a.DO.Returning(value, columns...))
}

func (a aIToolAgentBindDo) Not(conds ...gen.Condition) IAIToolAgentBindDo {
	return a.withDO(a.DO.Not(conds...))
}

func (a aIToolAgentBindDo) Or(conds ...gen.Condition) IAIToolAgentBindDo {
	return a.withDO(a.DO.Or(conds...))
}

func (a aIToolAgentBindDo) Select(conds ...field.Expr) IAIToolAgentBindDo {
	return a.withDO(a.DO.Select(conds...))
}

func (a aIToolAgentBindDo) Where(conds ...gen.Condition) IAIToolAgentBindDo {
	return a.withDO(a.DO.Where(conds...))
}

func (a aIToolAgentBindDo) Order(conds ...field.Expr) IAIToolAgentBindDo {
	return a.withDO(a.DO.Order(conds...))
}

func (a aIToolAgentBindDo) Distinct(cols ...field.Expr) IAIToolAgentBindDo {
	return a.withDO(a.DO.Distinct(cols...))
}

func (a aIToolAgentBindDo) Omit(cols ...field.Expr) IAIToolAgentBindDo {
	return a.withDO(a.DO.Omit(cols...))
}

func (a aIToolAgentBindDo) Join(table schema.Tabler, on ...field.Expr) IAIToolAgentBindDo {
	return a.withDO(a.DO.Join(table, on...))
}

func (a aIToolAgentBindDo) LeftJoin(table schema.Tabler, on ...field.Expr) IAIToolAgentBindDo {
	return a.withDO(a.DO.LeftJoin(table, on...))
}

func (a aIToolAgentBindDo) RightJoin(table schema.Tabler, on ...field.Expr) IAIToolAgentBindDo {
	return a.withDO(a.DO.RightJoin(table, on...))
}

func (a aIToolAgentBindDo) Group(cols ...field.Expr) IAIToolAgentBindDo {
	return a.withDO(a.DO.Group(cols...))
}

func (a aIToolAgentBindDo) Having(conds ...gen.Condition) IAIToolAgentBindDo {
	return a.withDO(a.DO.Having(conds...))
}

func (a aIToolAgentBindDo) Limit(limit int) IAIToolAgentBindDo {
	return a.withDO(a.DO.Limit(limit))
}

func (a aIToolAgentBindDo) Offset(offset int) IAIToolAgentBindDo {
	return a.withDO(a.DO.Offset(offset))
}

func (a aIToolAgentBindDo) Scopes(funcs ...func(gen.Dao) gen.Dao) IAIToolAgentBindDo {
	return a.withDO(a.DO.Scopes(funcs...))
}

func (a aIToolAgentBindDo) Unscoped() IAIToolAgentBindDo {
	return a.withDO(a.DO.Unscoped())
}

func (a aIToolAgentBindDo) Create(values ...*model.AIToolAgentBind) error {
	if len(values) == 0 {
		return nil
	}
	return a.DO.Create(values)
}

func (a aIToolAgentBindDo) CreateInBatches(values []*model.AIToolAgentBind, batchSize int) error {
	return a.DO.CreateInBatches(values, batchSize)
}

// Save : !!! underlying implementation is different with GORM
// The method is equivalent to executing the statement: db.Clauses(clause.OnConflict{UpdateAll: true}).Create(values)
func (a aIToolAgentBindDo) Save(values ...*model.AIToolAgentBind) error {
	if len(values) == 0 {
		return nil
	}
	return a.DO.Save(values)
}

func (a aIToolAgentBindDo) First() (*model.AIToolAgentBind, error) {
	if result, err := a.DO.First(); err != nil {
		return nil, err
	} else {
		return result.(*model.AIToolAgentBind), nil
	}
}

func (a aIToolAgentBindDo) Take() (*model.AIToolAgentBind, error) {
	if result, err := a.DO.Take(); err != nil {
		return nil, err
	} else {
		return result.(*model.AIToolAgentBind), nil
	}
}

func (a aIToolAgentBindDo) Last() (*model.AIToolAgentBind, error) {
	if result, err := a.DO.Last(); err != nil {
		return nil, err
	} else {
		return result.(*model.AIToolAgentBind), nil
	}
}

func (a aIToolAgentBindDo) Find() ([]*model.AIToolAgentBind, error) {
	result, err := a.DO.Find()
	return result.([]*model.AIToolAgentBind), err
}

func (a aIToolAgentBindDo) FindInBatch(batchSize int, fc func(tx gen.Dao, batch int) error) (results []*model.AIToolAgentBind, err error) {
	buf := make([]*model.AIToolAgentBind, 0, batchSize)
	err = a.DO.FindInBatches(&buf, batchSize, func(tx gen.Dao, batch int) error {
		defer func() { results = append(results, buf...) }()
		return fc(tx, batch)
	})
	return results, err
}

func (a aIToolAgentBindDo) FindInBatches(result *[]*model.AIToolAgentBind, batchSize int, fc func(tx gen.Dao, batch int) error) error {
	return a.DO.FindInBatches(result, batchSize, fc)
}

func (a aIToolAgentBindDo) Attrs(attrs ...field.AssignExpr) IAIToolAgentBindDo {
	return a.withDO(a.DO.Attrs(attrs...))
}

func (a aIToolAgentBindDo) Assign(attrs ...field.AssignExpr) IAIToolAgentBindDo {
	return a.withDO(a.DO.Assign(attrs...))
}

func (a aIToolAgentBindDo) Joins(fields ...field.RelationField) IAIToolAgentBindDo {
	for _, _f := range fields {
		a = *a.withDO(a.DO.Joins(_f))
	}
	return &a
}

func (a aIToolAgentBindDo) Preload(fields ...field.RelationField) IAIToolAgentBindDo {
	for _, _f := range fields {
		a = *a.withDO(a.DO.Preload(_f))
	}
	return &a
}

func (a aIToolAgentBindDo) FirstOrInit() (*model.AIToolAgentBind, error) {
	if result, err := a.DO.FirstOrInit(); err != nil {
		return nil, err
	} else {
		return result.(*model.AIToolAgentBind), nil
	}
}

func (a aIToolAgentBindDo) FirstOrCreate() (*model.AIToolAgentBind, error) {
	if result, err := a.DO.FirstOrCreate(); err != nil {
		return nil, err
	} else {
		return result.(*model.AIToolAgentBind), nil
	}
}

func (a aIToolAgentBindDo) FindByPage(offset int, limit int) (result []*model.AIToolAgentBind, count int64, err error) {
	result, err = a.Offset(offset).Limit(limit).Find()
	if err != nil {
		return
	}

	if size := len(result); 0 < limit && 0 < size && size < limit {
		count = int64(size + offset)
		return
	}

	count, err = a.Offset(-1).Limit(-1).Count()
	return
}

func (a aIToolAgentBindDo) ScanByPage(result interface{}, offset int, limit int) (count int64, err error) {
	count, err = a.Count()
	if err != nil {
		return
	}

	err = a.Offset(offset).Limit(limit).Scan(result)
	return
}

func (a aIToolAgentBindDo) Scan(result interface{}) (err error) {
	return a.DO.Scan(result)
}

func (a aIToolAgentBindDo) Delete(models ...*model.AIToolAgentBind) (result gen.ResultInfo, err error) {
	return a.DO.Delete(models)
}

func (a *aIToolAgentBindDo) withDO(do gen.Dao) *aIToolAgentBindDo {
	a.DO = *do.(*gen.DO)
	return a
}
