// Code generated by gorm.io/gen. DO NOT EDIT.
// Code generated by gorm.io/gen. DO NOT EDIT.
// Code generated by gorm.io/gen. DO NOT EDIT.

package query

import (
	"context"
	"database/sql"

	"gorm.io/gorm"

	"gorm.io/gen"

	"gorm.io/plugin/dbresolver"
)

var (
	Q                = new(Query)
	AIAgent          *aIAgent
	AIApplication    *aIApplication
	AIChat           *aIChat
	AIChatMessage    *aIChatMessage
	AIModel          *aIModel
	AIPromptTemplate *aIPromptTemplate
	AITool           *aITool
	AIToolAgentBind  *aIToolAgentBind
	AIWorkflow       *aIWorkflow
	SysDict          *sysDict
	SysDictType      *sysDictType
	SysMenu          *sysMenu
	SysTracker       *sysTracker
	SysUser          *sysUser
)

func SetDefault(db *gorm.DB, opts ...gen.DOOption) {
	*Q = *Use(db, opts...)
	AIAgent = &Q.AIAgent
	AIApplication = &Q.AIApplication
	AIChat = &Q.AIChat
	AIChatMessage = &Q.AIChatMessage
	AIModel = &Q.AIModel
	AIPromptTemplate = &Q.AIPromptTemplate
	AITool = &Q.AITool
	AIToolAgentBind = &Q.AIToolAgentBind
	AIWorkflow = &Q.AIWorkflow
	SysDict = &Q.SysDict
	SysDictType = &Q.SysDictType
	SysMenu = &Q.SysMenu
	SysTracker = &Q.SysTracker
	SysUser = &Q.SysUser
}

func Use(db *gorm.DB, opts ...gen.DOOption) *Query {
	return &Query{
		db:               db,
		AIAgent:          newAIAgent(db, opts...),
		AIApplication:    newAIApplication(db, opts...),
		AIChat:           newAIChat(db, opts...),
		AIChatMessage:    newAIChatMessage(db, opts...),
		AIModel:          newAIModel(db, opts...),
		AIPromptTemplate: newAIPromptTemplate(db, opts...),
		AITool:           newAITool(db, opts...),
		AIToolAgentBind:  newAIToolAgentBind(db, opts...),
		AIWorkflow:       newAIWorkflow(db, opts...),
		SysDict:          newSysDict(db, opts...),
		SysDictType:      newSysDictType(db, opts...),
		SysMenu:          newSysMenu(db, opts...),
		SysTracker:       newSysTracker(db, opts...),
		SysUser:          newSysUser(db, opts...),
	}
}

type Query struct {
	db *gorm.DB

	AIAgent          aIAgent
	AIApplication    aIApplication
	AIChat           aIChat
	AIChatMessage    aIChatMessage
	AIModel          aIModel
	AIPromptTemplate aIPromptTemplate
	AITool           aITool
	AIToolAgentBind  aIToolAgentBind
	AIWorkflow       aIWorkflow
	SysDict          sysDict
	SysDictType      sysDictType
	SysMenu          sysMenu
	SysTracker       sysTracker
	SysUser          sysUser
}

func (q *Query) Available() bool { return q.db != nil }

func (q *Query) clone(db *gorm.DB) *Query {
	return &Query{
		db:               db,
		AIAgent:          q.AIAgent.clone(db),
		AIApplication:    q.AIApplication.clone(db),
		AIChat:           q.AIChat.clone(db),
		AIChatMessage:    q.AIChatMessage.clone(db),
		AIModel:          q.AIModel.clone(db),
		AIPromptTemplate: q.AIPromptTemplate.clone(db),
		AITool:           q.AITool.clone(db),
		AIToolAgentBind:  q.AIToolAgentBind.clone(db),
		AIWorkflow:       q.AIWorkflow.clone(db),
		SysDict:          q.SysDict.clone(db),
		SysDictType:      q.SysDictType.clone(db),
		SysMenu:          q.SysMenu.clone(db),
		SysTracker:       q.SysTracker.clone(db),
		SysUser:          q.SysUser.clone(db),
	}
}

func (q *Query) ReadDB() *Query {
	return q.ReplaceDB(q.db.Clauses(dbresolver.Read))
}

func (q *Query) WriteDB() *Query {
	return q.ReplaceDB(q.db.Clauses(dbresolver.Write))
}

func (q *Query) ReplaceDB(db *gorm.DB) *Query {
	return &Query{
		db:               db,
		AIAgent:          q.AIAgent.replaceDB(db),
		AIApplication:    q.AIApplication.replaceDB(db),
		AIChat:           q.AIChat.replaceDB(db),
		AIChatMessage:    q.AIChatMessage.replaceDB(db),
		AIModel:          q.AIModel.replaceDB(db),
		AIPromptTemplate: q.AIPromptTemplate.replaceDB(db),
		AITool:           q.AITool.replaceDB(db),
		AIToolAgentBind:  q.AIToolAgentBind.replaceDB(db),
		AIWorkflow:       q.AIWorkflow.replaceDB(db),
		SysDict:          q.SysDict.replaceDB(db),
		SysDictType:      q.SysDictType.replaceDB(db),
		SysMenu:          q.SysMenu.replaceDB(db),
		SysTracker:       q.SysTracker.replaceDB(db),
		SysUser:          q.SysUser.replaceDB(db),
	}
}

type queryCtx struct {
	AIAgent          IAIAgentDo
	AIApplication    IAIApplicationDo
	AIChat           IAIChatDo
	AIChatMessage    IAIChatMessageDo
	AIModel          IAIModelDo
	AIPromptTemplate IAIPromptTemplateDo
	AITool           IAIToolDo
	AIToolAgentBind  IAIToolAgentBindDo
	AIWorkflow       IAIWorkflowDo
	SysDict          ISysDictDo
	SysDictType      ISysDictTypeDo
	SysMenu          ISysMenuDo
	SysTracker       ISysTrackerDo
	SysUser          ISysUserDo
}

func (q *Query) WithContext(ctx context.Context) *queryCtx {
	return &queryCtx{
		AIAgent:          q.AIAgent.WithContext(ctx),
		AIApplication:    q.AIApplication.WithContext(ctx),
		AIChat:           q.AIChat.WithContext(ctx),
		AIChatMessage:    q.AIChatMessage.WithContext(ctx),
		AIModel:          q.AIModel.WithContext(ctx),
		AIPromptTemplate: q.AIPromptTemplate.WithContext(ctx),
		AITool:           q.AITool.WithContext(ctx),
		AIToolAgentBind:  q.AIToolAgentBind.WithContext(ctx),
		AIWorkflow:       q.AIWorkflow.WithContext(ctx),
		SysDict:          q.SysDict.WithContext(ctx),
		SysDictType:      q.SysDictType.WithContext(ctx),
		SysMenu:          q.SysMenu.WithContext(ctx),
		SysTracker:       q.SysTracker.WithContext(ctx),
		SysUser:          q.SysUser.WithContext(ctx),
	}
}

func (q *Query) Transaction(fc func(tx *Query) error, opts ...*sql.TxOptions) error {
	return q.db.Transaction(func(tx *gorm.DB) error { return fc(q.clone(tx)) }, opts...)
}

func (q *Query) Begin(opts ...*sql.TxOptions) *QueryTx {
	tx := q.db.Begin(opts...)
	return &QueryTx{Query: q.clone(tx), Error: tx.Error}
}

type QueryTx struct {
	*Query
	Error error
}

func (q *QueryTx) Commit() error {
	return q.db.Commit().Error
}

func (q *QueryTx) Rollback() error {
	return q.db.Rollback().Error
}

func (q *QueryTx) SavePoint(name string) error {
	return q.db.SavePoint(name).Error
}

func (q *QueryTx) RollbackTo(name string) error {
	return q.db.RollbackTo(name).Error
}
