// Code generated by protoc-gen-go-grpc. DO NOT EDIT.
// versions:
// - protoc-gen-go-grpc v1.5.1
// - protoc             v3.21.12
// source: report/v1/report.proto

package v1

import (
	context "context"
	grpc "google.golang.org/grpc"
	codes "google.golang.org/grpc/codes"
	status "google.golang.org/grpc/status"
)

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
// Requires gRPC-Go v1.64.0 or later.
const _ = grpc.SupportPackageIsVersion9

const (
	Report_ExportUserFeedback_FullMethodName = "/report.v1.Report/ExportUserFeedback"
	Report_GetExportStatus_FullMethodName    = "/report.v1.Report/GetExportStatus"
	Report_DownloadExport_FullMethodName     = "/report.v1.Report/DownloadExport"
)

// ReportClient is the client API for Report service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://pkg.go.dev/google.golang.org/grpc/?tab=doc#ClientConn.NewStream.
//
// The report service definition.
type ReportClient interface {
	// Export user feedback data as Excel
	ExportUserFeedback(ctx context.Context, in *ExportUserFeedbackRequest, opts ...grpc.CallOption) (*ExportUserFeedbackReply, error)
	// Get export status
	GetExportStatus(ctx context.Context, in *GetExportStatusRequest, opts ...grpc.CallOption) (*GetExportStatusReply, error)
	// Download exported file
	DownloadExport(ctx context.Context, in *DownloadExportRequest, opts ...grpc.CallOption) (*DownloadExportReply, error)
}

type reportClient struct {
	cc grpc.ClientConnInterface
}

func NewReportClient(cc grpc.ClientConnInterface) ReportClient {
	return &reportClient{cc}
}

func (c *reportClient) ExportUserFeedback(ctx context.Context, in *ExportUserFeedbackRequest, opts ...grpc.CallOption) (*ExportUserFeedbackReply, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(ExportUserFeedbackReply)
	err := c.cc.Invoke(ctx, Report_ExportUserFeedback_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *reportClient) GetExportStatus(ctx context.Context, in *GetExportStatusRequest, opts ...grpc.CallOption) (*GetExportStatusReply, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(GetExportStatusReply)
	err := c.cc.Invoke(ctx, Report_GetExportStatus_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *reportClient) DownloadExport(ctx context.Context, in *DownloadExportRequest, opts ...grpc.CallOption) (*DownloadExportReply, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(DownloadExportReply)
	err := c.cc.Invoke(ctx, Report_DownloadExport_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// ReportServer is the server API for Report service.
// All implementations must embed UnimplementedReportServer
// for forward compatibility.
//
// The report service definition.
type ReportServer interface {
	// Export user feedback data as Excel
	ExportUserFeedback(context.Context, *ExportUserFeedbackRequest) (*ExportUserFeedbackReply, error)
	// Get export status
	GetExportStatus(context.Context, *GetExportStatusRequest) (*GetExportStatusReply, error)
	// Download exported file
	DownloadExport(context.Context, *DownloadExportRequest) (*DownloadExportReply, error)
	mustEmbedUnimplementedReportServer()
}

// UnimplementedReportServer must be embedded to have
// forward compatible implementations.
//
// NOTE: this should be embedded by value instead of pointer to avoid a nil
// pointer dereference when methods are called.
type UnimplementedReportServer struct{}

func (UnimplementedReportServer) ExportUserFeedback(context.Context, *ExportUserFeedbackRequest) (*ExportUserFeedbackReply, error) {
	return nil, status.Errorf(codes.Unimplemented, "method ExportUserFeedback not implemented")
}
func (UnimplementedReportServer) GetExportStatus(context.Context, *GetExportStatusRequest) (*GetExportStatusReply, error) {
	return nil, status.Errorf(codes.Unimplemented, "method GetExportStatus not implemented")
}
func (UnimplementedReportServer) DownloadExport(context.Context, *DownloadExportRequest) (*DownloadExportReply, error) {
	return nil, status.Errorf(codes.Unimplemented, "method DownloadExport not implemented")
}
func (UnimplementedReportServer) mustEmbedUnimplementedReportServer() {}
func (UnimplementedReportServer) testEmbeddedByValue()                {}

// UnsafeReportServer may be embedded to opt out of forward compatibility for this service.
// Use of this interface is not recommended, as added methods to ReportServer will
// result in compilation errors.
type UnsafeReportServer interface {
	mustEmbedUnimplementedReportServer()
}

func RegisterReportServer(s grpc.ServiceRegistrar, srv ReportServer) {
	// If the following call pancis, it indicates UnimplementedReportServer was
	// embedded by pointer and is nil.  This will cause panics if an
	// unimplemented method is ever invoked, so we test this at initialization
	// time to prevent it from happening at runtime later due to I/O.
	if t, ok := srv.(interface{ testEmbeddedByValue() }); ok {
		t.testEmbeddedByValue()
	}
	s.RegisterService(&Report_ServiceDesc, srv)
}

func _Report_ExportUserFeedback_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(ExportUserFeedbackRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(ReportServer).ExportUserFeedback(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: Report_ExportUserFeedback_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(ReportServer).ExportUserFeedback(ctx, req.(*ExportUserFeedbackRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _Report_GetExportStatus_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(GetExportStatusRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(ReportServer).GetExportStatus(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: Report_GetExportStatus_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(ReportServer).GetExportStatus(ctx, req.(*GetExportStatusRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _Report_DownloadExport_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(DownloadExportRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(ReportServer).DownloadExport(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: Report_DownloadExport_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(ReportServer).DownloadExport(ctx, req.(*DownloadExportRequest))
	}
	return interceptor(ctx, in, info, handler)
}

// Report_ServiceDesc is the grpc.ServiceDesc for Report service.
// It's only intended for direct use with grpc.RegisterService,
// and not to be introspected or modified (even as a copy)
var Report_ServiceDesc = grpc.ServiceDesc{
	ServiceName: "report.v1.Report",
	HandlerType: (*ReportServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "ExportUserFeedback",
			Handler:    _Report_ExportUserFeedback_Handler,
		},
		{
			MethodName: "GetExportStatus",
			Handler:    _Report_GetExportStatus_Handler,
		},
		{
			MethodName: "DownloadExport",
			Handler:    _Report_DownloadExport_Handler,
		},
	},
	Streams:  []grpc.StreamDesc{},
	Metadata: "report/v1/report.proto",
}
