// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.10
// 	protoc        v3.21.12
// source: report/v1/report.proto

package v1

import (
	_ "google.golang.org/genproto/googleapis/api/annotations"
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

// Request for exporting user feedback
type ExportUserFeedbackRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	StartDate     string                 `protobuf:"bytes,1,opt,name=start_date,json=startDate,proto3" json:"start_date,omitempty"`
	EndDate       string                 `protobuf:"bytes,2,opt,name=end_date,json=endDate,proto3" json:"end_date,omitempty"`
	Filters       []string               `protobuf:"bytes,3,rep,name=filters,proto3" json:"filters,omitempty"`
	UserId        string                 `protobuf:"bytes,4,opt,name=user_id,json=userId,proto3" json:"user_id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ExportUserFeedbackRequest) Reset() {
	*x = ExportUserFeedbackRequest{}
	mi := &file_report_v1_report_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ExportUserFeedbackRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ExportUserFeedbackRequest) ProtoMessage() {}

func (x *ExportUserFeedbackRequest) ProtoReflect() protoreflect.Message {
	mi := &file_report_v1_report_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ExportUserFeedbackRequest.ProtoReflect.Descriptor instead.
func (*ExportUserFeedbackRequest) Descriptor() ([]byte, []int) {
	return file_report_v1_report_proto_rawDescGZIP(), []int{0}
}

func (x *ExportUserFeedbackRequest) GetStartDate() string {
	if x != nil {
		return x.StartDate
	}
	return ""
}

func (x *ExportUserFeedbackRequest) GetEndDate() string {
	if x != nil {
		return x.EndDate
	}
	return ""
}

func (x *ExportUserFeedbackRequest) GetFilters() []string {
	if x != nil {
		return x.Filters
	}
	return nil
}

func (x *ExportUserFeedbackRequest) GetUserId() string {
	if x != nil {
		return x.UserId
	}
	return ""
}

// Reply for exporting user feedback
type ExportUserFeedbackReply struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	ExportId      string                 `protobuf:"bytes,1,opt,name=export_id,json=exportId,proto3" json:"export_id,omitempty"`
	Status        string                 `protobuf:"bytes,2,opt,name=status,proto3" json:"status,omitempty"`
	Message       string                 `protobuf:"bytes,3,opt,name=message,proto3" json:"message,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ExportUserFeedbackReply) Reset() {
	*x = ExportUserFeedbackReply{}
	mi := &file_report_v1_report_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ExportUserFeedbackReply) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ExportUserFeedbackReply) ProtoMessage() {}

func (x *ExportUserFeedbackReply) ProtoReflect() protoreflect.Message {
	mi := &file_report_v1_report_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ExportUserFeedbackReply.ProtoReflect.Descriptor instead.
func (*ExportUserFeedbackReply) Descriptor() ([]byte, []int) {
	return file_report_v1_report_proto_rawDescGZIP(), []int{1}
}

func (x *ExportUserFeedbackReply) GetExportId() string {
	if x != nil {
		return x.ExportId
	}
	return ""
}

func (x *ExportUserFeedbackReply) GetStatus() string {
	if x != nil {
		return x.Status
	}
	return ""
}

func (x *ExportUserFeedbackReply) GetMessage() string {
	if x != nil {
		return x.Message
	}
	return ""
}

// Request for getting export status
type GetExportStatusRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	ExportId      string                 `protobuf:"bytes,1,opt,name=export_id,json=exportId,proto3" json:"export_id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetExportStatusRequest) Reset() {
	*x = GetExportStatusRequest{}
	mi := &file_report_v1_report_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetExportStatusRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetExportStatusRequest) ProtoMessage() {}

func (x *GetExportStatusRequest) ProtoReflect() protoreflect.Message {
	mi := &file_report_v1_report_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetExportStatusRequest.ProtoReflect.Descriptor instead.
func (*GetExportStatusRequest) Descriptor() ([]byte, []int) {
	return file_report_v1_report_proto_rawDescGZIP(), []int{2}
}

func (x *GetExportStatusRequest) GetExportId() string {
	if x != nil {
		return x.ExportId
	}
	return ""
}

// Reply for getting export status
type GetExportStatusReply struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	ExportId      string                 `protobuf:"bytes,1,opt,name=export_id,json=exportId,proto3" json:"export_id,omitempty"`
	Status        string                 `protobuf:"bytes,2,opt,name=status,proto3" json:"status,omitempty"`
	FileUrl       string                 `protobuf:"bytes,3,opt,name=file_url,json=fileUrl,proto3" json:"file_url,omitempty"`
	ErrorMessage  string                 `protobuf:"bytes,4,opt,name=error_message,json=errorMessage,proto3" json:"error_message,omitempty"`
	CreatedAt     string                 `protobuf:"bytes,5,opt,name=created_at,json=createdAt,proto3" json:"created_at,omitempty"`
	UpdatedAt     string                 `protobuf:"bytes,6,opt,name=updated_at,json=updatedAt,proto3" json:"updated_at,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetExportStatusReply) Reset() {
	*x = GetExportStatusReply{}
	mi := &file_report_v1_report_proto_msgTypes[3]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetExportStatusReply) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetExportStatusReply) ProtoMessage() {}

func (x *GetExportStatusReply) ProtoReflect() protoreflect.Message {
	mi := &file_report_v1_report_proto_msgTypes[3]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetExportStatusReply.ProtoReflect.Descriptor instead.
func (*GetExportStatusReply) Descriptor() ([]byte, []int) {
	return file_report_v1_report_proto_rawDescGZIP(), []int{3}
}

func (x *GetExportStatusReply) GetExportId() string {
	if x != nil {
		return x.ExportId
	}
	return ""
}

func (x *GetExportStatusReply) GetStatus() string {
	if x != nil {
		return x.Status
	}
	return ""
}

func (x *GetExportStatusReply) GetFileUrl() string {
	if x != nil {
		return x.FileUrl
	}
	return ""
}

func (x *GetExportStatusReply) GetErrorMessage() string {
	if x != nil {
		return x.ErrorMessage
	}
	return ""
}

func (x *GetExportStatusReply) GetCreatedAt() string {
	if x != nil {
		return x.CreatedAt
	}
	return ""
}

func (x *GetExportStatusReply) GetUpdatedAt() string {
	if x != nil {
		return x.UpdatedAt
	}
	return ""
}

// Request for downloading export
type DownloadExportRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	ExportId      string                 `protobuf:"bytes,1,opt,name=export_id,json=exportId,proto3" json:"export_id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *DownloadExportRequest) Reset() {
	*x = DownloadExportRequest{}
	mi := &file_report_v1_report_proto_msgTypes[4]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *DownloadExportRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*DownloadExportRequest) ProtoMessage() {}

func (x *DownloadExportRequest) ProtoReflect() protoreflect.Message {
	mi := &file_report_v1_report_proto_msgTypes[4]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use DownloadExportRequest.ProtoReflect.Descriptor instead.
func (*DownloadExportRequest) Descriptor() ([]byte, []int) {
	return file_report_v1_report_proto_rawDescGZIP(), []int{4}
}

func (x *DownloadExportRequest) GetExportId() string {
	if x != nil {
		return x.ExportId
	}
	return ""
}

// Reply for downloading export
type DownloadExportReply struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	FileContent   []byte                 `protobuf:"bytes,1,opt,name=file_content,json=fileContent,proto3" json:"file_content,omitempty"`
	FileName      string                 `protobuf:"bytes,2,opt,name=file_name,json=fileName,proto3" json:"file_name,omitempty"`
	ContentType   string                 `protobuf:"bytes,3,opt,name=content_type,json=contentType,proto3" json:"content_type,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *DownloadExportReply) Reset() {
	*x = DownloadExportReply{}
	mi := &file_report_v1_report_proto_msgTypes[5]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *DownloadExportReply) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*DownloadExportReply) ProtoMessage() {}

func (x *DownloadExportReply) ProtoReflect() protoreflect.Message {
	mi := &file_report_v1_report_proto_msgTypes[5]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use DownloadExportReply.ProtoReflect.Descriptor instead.
func (*DownloadExportReply) Descriptor() ([]byte, []int) {
	return file_report_v1_report_proto_rawDescGZIP(), []int{5}
}

func (x *DownloadExportReply) GetFileContent() []byte {
	if x != nil {
		return x.FileContent
	}
	return nil
}

func (x *DownloadExportReply) GetFileName() string {
	if x != nil {
		return x.FileName
	}
	return ""
}

func (x *DownloadExportReply) GetContentType() string {
	if x != nil {
		return x.ContentType
	}
	return ""
}

var File_report_v1_report_proto protoreflect.FileDescriptor

const file_report_v1_report_proto_rawDesc = "" +
	"\n" +
	"\x16report/v1/report.proto\x12\treport.v1\x1a\x1cgoogle/api/annotations.proto\"\x88\x01\n" +
	"\x19ExportUserFeedbackRequest\x12\x1d\n" +
	"\n" +
	"start_date\x18\x01 \x01(\tR\tstartDate\x12\x19\n" +
	"\bend_date\x18\x02 \x01(\tR\aendDate\x12\x18\n" +
	"\afilters\x18\x03 \x03(\tR\afilters\x12\x17\n" +
	"\auser_id\x18\x04 \x01(\tR\x06userId\"h\n" +
	"\x17ExportUserFeedbackReply\x12\x1b\n" +
	"\texport_id\x18\x01 \x01(\tR\bexportId\x12\x16\n" +
	"\x06status\x18\x02 \x01(\tR\x06status\x12\x18\n" +
	"\amessage\x18\x03 \x01(\tR\amessage\"5\n" +
	"\x16GetExportStatusRequest\x12\x1b\n" +
	"\texport_id\x18\x01 \x01(\tR\bexportId\"\xc9\x01\n" +
	"\x14GetExportStatusReply\x12\x1b\n" +
	"\texport_id\x18\x01 \x01(\tR\bexportId\x12\x16\n" +
	"\x06status\x18\x02 \x01(\tR\x06status\x12\x19\n" +
	"\bfile_url\x18\x03 \x01(\tR\afileUrl\x12#\n" +
	"\rerror_message\x18\x04 \x01(\tR\ferrorMessage\x12\x1d\n" +
	"\n" +
	"created_at\x18\x05 \x01(\tR\tcreatedAt\x12\x1d\n" +
	"\n" +
	"updated_at\x18\x06 \x01(\tR\tupdatedAt\"4\n" +
	"\x15DownloadExportRequest\x12\x1b\n" +
	"\texport_id\x18\x01 \x01(\tR\bexportId\"x\n" +
	"\x13DownloadExportReply\x12!\n" +
	"\ffile_content\x18\x01 \x01(\fR\vfileContent\x12\x1b\n" +
	"\tfile_name\x18\x02 \x01(\tR\bfileName\x12!\n" +
	"\fcontent_type\x18\x03 \x01(\tR\vcontentType2\x9f\x03\n" +
	"\x06Report\x12\x89\x01\n" +
	"\x12ExportUserFeedback\x12$.report.v1.ExportUserFeedbackRequest\x1a\".report.v1.ExportUserFeedbackReply\")\x82\xd3\xe4\x93\x02#:\x01*\"\x1e/v1/report/export/userfeedback\x12\x83\x01\n" +
	"\x0fGetExportStatus\x12!.report.v1.GetExportStatusRequest\x1a\x1f.report.v1.GetExportStatusReply\",\x82\xd3\xe4\x93\x02&\x12$/v1/report/export/status/{export_id}\x12\x82\x01\n" +
	"\x0eDownloadExport\x12 .report.v1.DownloadExportRequest\x1a\x1e.report.v1.DownloadExportReply\".\x82\xd3\xe4\x93\x02(\x12&/v1/report/export/download/{export_id}BE\n" +
	"\x18dev.kratos.api.report.v1B\rReportProtoV1P\x01Z\x18backend/api/report/v1;v1b\x06proto3"

var (
	file_report_v1_report_proto_rawDescOnce sync.Once
	file_report_v1_report_proto_rawDescData []byte
)

func file_report_v1_report_proto_rawDescGZIP() []byte {
	file_report_v1_report_proto_rawDescOnce.Do(func() {
		file_report_v1_report_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_report_v1_report_proto_rawDesc), len(file_report_v1_report_proto_rawDesc)))
	})
	return file_report_v1_report_proto_rawDescData
}

var file_report_v1_report_proto_msgTypes = make([]protoimpl.MessageInfo, 6)
var file_report_v1_report_proto_goTypes = []any{
	(*ExportUserFeedbackRequest)(nil), // 0: report.v1.ExportUserFeedbackRequest
	(*ExportUserFeedbackReply)(nil),   // 1: report.v1.ExportUserFeedbackReply
	(*GetExportStatusRequest)(nil),    // 2: report.v1.GetExportStatusRequest
	(*GetExportStatusReply)(nil),      // 3: report.v1.GetExportStatusReply
	(*DownloadExportRequest)(nil),     // 4: report.v1.DownloadExportRequest
	(*DownloadExportReply)(nil),       // 5: report.v1.DownloadExportReply
}
var file_report_v1_report_proto_depIdxs = []int32{
	0, // 0: report.v1.Report.ExportUserFeedback:input_type -> report.v1.ExportUserFeedbackRequest
	2, // 1: report.v1.Report.GetExportStatus:input_type -> report.v1.GetExportStatusRequest
	4, // 2: report.v1.Report.DownloadExport:input_type -> report.v1.DownloadExportRequest
	1, // 3: report.v1.Report.ExportUserFeedback:output_type -> report.v1.ExportUserFeedbackReply
	3, // 4: report.v1.Report.GetExportStatus:output_type -> report.v1.GetExportStatusReply
	5, // 5: report.v1.Report.DownloadExport:output_type -> report.v1.DownloadExportReply
	3, // [3:6] is the sub-list for method output_type
	0, // [0:3] is the sub-list for method input_type
	0, // [0:0] is the sub-list for extension type_name
	0, // [0:0] is the sub-list for extension extendee
	0, // [0:0] is the sub-list for field type_name
}

func init() { file_report_v1_report_proto_init() }
func file_report_v1_report_proto_init() {
	if File_report_v1_report_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_report_v1_report_proto_rawDesc), len(file_report_v1_report_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   6,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_report_v1_report_proto_goTypes,
		DependencyIndexes: file_report_v1_report_proto_depIdxs,
		MessageInfos:      file_report_v1_report_proto_msgTypes,
	}.Build()
	File_report_v1_report_proto = out.File
	file_report_v1_report_proto_goTypes = nil
	file_report_v1_report_proto_depIdxs = nil
}
