// Code generated by Wire. DO NOT EDIT.

//go:generate go run -mod=mod github.com/google/wire/cmd/wire
//go:build !wireinject
// +build !wireinject

package main

import (
	"github.com/example/aichat/backend/internal/biz"
	"github.com/example/aichat/backend/internal/biz/base"
	"github.com/example/aichat/backend/internal/conf"
	"github.com/example/aichat/backend/internal/data"
	"github.com/example/aichat/backend/internal/server"
	"github.com/example/aichat/backend/internal/service"
	base2 "github.com/example/aichat/backend/internal/service/base"
	"github.com/example/aichat/backend/pkg/auth"
	"github.com/go-kratos/kratos/v2"
	"github.com/go-kratos/kratos/v2/log"
	"go.uber.org/zap"
)

import (
	_ "go.uber.org/automaxprocs"
)

// Injectors from wire.go:

// wireApp init kratos application.
func wireApp(confServer *conf.Server, bootstrap *conf.Bootstrap, logger *zap.Logger, logLogger log.Logger) (*kratos.App, func(), error) {
	dataRepo, cleanup, err := data.NewData(bootstrap, logger)
	if err != nil {
		return nil, nil, err
	}
	sysUserRepo := data.NewSysUserRepo(dataRepo)
	authRepo := auth.NewAuthRepo()
	sysUserUseCase := base.NewSysUserUseCase(sysUserRepo, authRepo)
	authService := base2.NewAuthService(sysUserUseCase)
	chatService := service.NewChatService(logger)
	grpcServer := server.NewGRPCServer(confServer, authService, chatService, logLogger)
	userFeedbackRepo := data.NewUserFeedbackRepo(dataRepo, logger)
	userFeedbackUsecase := biz.NewUserFeedbackUsecase(userFeedbackRepo, logger)
	userFeedbackService := service.NewUserFeedbackService(userFeedbackUsecase, logLogger)
	sysMenuRepo := data.NewSysMenuRepo(dataRepo, logger)
	sysMenuUseCase := base.NewSysMenuUseCase(sysMenuRepo)
	systemService := base2.NewSystemService(sysMenuUseCase)
	httpServer := server.NewHTTPServer(confServer, userFeedbackService, chatService, authService, authRepo, systemService, logLogger)
	webSocketServer := server.NewWebSocketServerWrapper(chatService, logger)
	webSocketApp := server.NewWebSocketAppWrapper(webSocketServer, logger)
	app := newApp(logLogger, grpcServer, httpServer, webSocketApp)
	return app, func() {
		cleanup()
	}, nil
}
