// Code generated by Wire. DO NOT EDIT.

//go:generate go run -mod=mod github.com/google/wire/cmd/wire
//go:build !wireinject
// +build !wireinject

package main

import (
	"github.com/example/aichat/backend/internal/biz"
	"github.com/example/aichat/backend/internal/conf"
	"github.com/example/aichat/backend/internal/data"
	"github.com/example/aichat/backend/internal/server"
	"github.com/example/aichat/backend/internal/service"
	"github.com/example/aichat/backend/internal/service/base"
	"github.com/go-kratos/kratos/v2"
	"github.com/go-kratos/kratos/v2/log"
	"go.uber.org/zap"
)

import (
	_ "go.uber.org/automaxprocs"
)

// Injectors from wire.go:

// wireApp init kratos application.
func wireApp(confServer *conf.Server, bootstrap *conf.Bootstrap, logger *zap.Logger, logLogger log.Logger) (*kratos.App, func(), error) {
	chatService := service.NewChatService(logger)
	grpcServer := server.NewGRPCServer(confServer, chatService, logLogger)
	dataData, cleanup, err := data.NewData(bootstrap, logger)
	if err != nil {
		return nil, nil, err
	}
	userFeedbackRepo := data.NewUserFeedbackRepo(dataData, logger)
	userFeedbackUsecase := biz.NewUserFeedbackUsecase(userFeedbackRepo, logger)
	userFeedbackService := service.NewUserFeedbackService(userFeedbackUsecase, logLogger)
	authService := base.NewAuthService()
	httpServer := server.NewHTTPServer(confServer, userFeedbackService, chatService, authService, logLogger)
	webSocketServer := server.NewWebSocketServerWrapper(chatService, logger)
	webSocketApp := server.NewWebSocketAppWrapper(webSocketServer, logger)
	app := newApp(logLogger, grpcServer, httpServer, webSocketApp)
	return app, func() {
		cleanup()
	}, nil
}
