events {
  worker_connections 4096;
}
http {
  log_format main ' $remote_user [$time_local] $http_x_Forwarded_for $remote_addr $request '
  '$http_x_forwarded_for '
  '$upstream_addr '
  'ups_resp_time: $upstream_response_time '
  'request_time: $request_time';

  log_format upstreamlog '[$time_local] $remote_addr - $remote_user - $server_name $host to: $upstream_addr: $request $status upstream_response_time $upstream_response_time msec $msec request_time $request_time';

  ##
  # Logging Settings
  ##
  access_log /var/log/nginx/access.log main;
  error_log /var/log/nginx/error.log;

  include /etc/nginx/mime.types;
  default_type application/octet-stream;
  client_max_body_size 1000m;
  gzip on;
  gzip_min_length 1k;
  gzip_buffers 16 8k;
  gzip_comp_level 5;
  gzip_vary on;
  gzip_proxied any;
  gzip_types application/atom+xml
  application/javascript
  application/json
  application/rss+xml
  application/vnd.ms-fontobject
  application/x-font-ttf
  application/x-web-app-manifest+json
  application/xhtml+xml
  application/xml
  font/opentype
  image/svg+xml
  image/x-icon
  image/jpeg
  image/gif
  image/png
  text/css
  text/plain
  text/x-component;

  server {
    charset utf-8;
    listen 80;

    proxy_http_version 1.1;
    proxy_set_header Connection "";
    proxy_set_header Host $http_host;
    proxy_set_header X-Real-IP $remote_addr;
    proxy_set_header X-Forward-For $proxy_add_x_forwarded_for;
    proxy_set_header X-Forward-Proto http;

    root /home/litechat/;


    location / {
      try_files $uri $uri/ /index.html;
      add_header Cache-Control no-cache;

      if (!-e $request_filename) {
        rewrite ^/(.*) /index.html last;
        break;
      }
    }

    location ~ /(assets/*|resource/*) {
      # 设置 css 文件的字符集

      if ($request_uri ~* \.css$) {
          add_header Content-Type "text/css; charset=utf-8";
          charset utf-8;
      }

      # 避免别人看到我们的源代码
      location ~* \.map$ {
        # 检查 Cookie 是否包含 pggold-test
        if ($http_cookie !~* "pggold-test") {
            # 如果不包含 pggold-test，返回 404
            return 404;
        }
      }

      expires 365d;
      add_header Cache-Control public;
   	}


    error_page 404 /404.html;
    error_page 500 502 503 504 /50x.html;
    location = /50x.html {
      root /usr/share/nginx/html;
    }
    location /back {
            proxy_pass http://127.0.0.1:8081/pg-gold-backend/v1;
    }
  }
}
