// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.10
// 	protoc        v5.29.3
// source: api/ai/agent.proto

package ai

import (
	_ "github.com/grpc-ecosystem/grpc-gateway/v2/protoc-gen-openapiv2/options"
	_ "google.golang.org/genproto/googleapis/api/annotations"
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	_ "google.golang.org/protobuf/types/known/emptypb"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

// ========== Agent Messages ==========
type AgentModel struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// Category    AIModel_Category `json:"category" gorm:"type:smallint;default:0"` // 模型类别
	Category int32 `protobuf:"varint,1,opt,name=category,proto3" json:"category,omitempty"`
	// ModelType   ModelType         `json:"model_type" gorm:"type:varchar(50);not null"`
	ModelType string `protobuf:"bytes,2,opt,name=model_type,json=modelType,proto3" json:"model_type,omitempty"`
	// ModelName   string           `json:"model_name" gorm:"type:varchar(100);not null"`
	ModelName string `protobuf:"bytes,3,opt,name=model_name,json=modelName,proto3" json:"model_name,omitempty"`
	// APIKey      string           `json:"api_key" gorm:"type:varchar(255)"` // 建议加密存储
	ApiKey string `protobuf:"bytes,4,opt,name=api_key,json=apiKey,proto3" json:"api_key,omitempty"`
	// BaseURL     string           `json:"base_url" gorm:"type:varchar(255)"`
	BaseUrl string `protobuf:"bytes,5,opt,name=base_url,json=baseUrl,proto3" json:"base_url,omitempty"`
	// Temperature float32          `json:"temperature" gorm:"type:float;default:0.7"`
	Temperature float32 `protobuf:"fixed32,6,opt,name=temperature,proto3" json:"temperature,omitempty"`
	// TopP        float32          `json:"top_p" gorm:"type:float;default:0.9"`
	TopP          float32 `protobuf:"fixed32,7,opt,name=top_p,json=topP,proto3" json:"top_p,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *AgentModel) Reset() {
	*x = AgentModel{}
	mi := &file_api_ai_agent_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *AgentModel) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*AgentModel) ProtoMessage() {}

func (x *AgentModel) ProtoReflect() protoreflect.Message {
	mi := &file_api_ai_agent_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use AgentModel.ProtoReflect.Descriptor instead.
func (*AgentModel) Descriptor() ([]byte, []int) {
	return file_api_ai_agent_proto_rawDescGZIP(), []int{0}
}

func (x *AgentModel) GetCategory() int32 {
	if x != nil {
		return x.Category
	}
	return 0
}

func (x *AgentModel) GetModelType() string {
	if x != nil {
		return x.ModelType
	}
	return ""
}

func (x *AgentModel) GetModelName() string {
	if x != nil {
		return x.ModelName
	}
	return ""
}

func (x *AgentModel) GetApiKey() string {
	if x != nil {
		return x.ApiKey
	}
	return ""
}

func (x *AgentModel) GetBaseUrl() string {
	if x != nil {
		return x.BaseUrl
	}
	return ""
}

func (x *AgentModel) GetTemperature() float32 {
	if x != nil {
		return x.Temperature
	}
	return 0
}

func (x *AgentModel) GetTopP() float32 {
	if x != nil {
		return x.TopP
	}
	return 0
}

type AgentInfo struct {
	state              protoimpl.MessageState `protogen:"open.v1"`
	Id                 int64                  `protobuf:"varint,1,opt,name=id,proto3" json:"id,omitempty"`
	Name               string                 `protobuf:"bytes,2,opt,name=name,proto3" json:"name,omitempty"`
	Code               string                 `protobuf:"bytes,3,opt,name=code,proto3" json:"code,omitempty"`
	Description        string                 `protobuf:"bytes,4,opt,name=description,proto3" json:"description,omitempty"`
	AdapterType        int32                  `protobuf:"varint,5,opt,name=adapter_type,json=adapterType,proto3" json:"adapter_type,omitempty"`
	OriginalModelId    int64                  `protobuf:"varint,6,opt,name=original_model_id,json=originalModelId,proto3" json:"original_model_id,omitempty"` // 来源ai模型id: 原始model ID：追溯引用的模型配置。
	AiModel            *AgentModel            `protobuf:"bytes,7,opt,name=ai_model,json=aiModel,proto3" json:"ai_model,omitempty"`                            // 通过original_model_id获取的模型配置，支持修改。
	MaxIteration       int32                  `protobuf:"varint,8,opt,name=max_iteration,json=maxIteration,proto3" json:"max_iteration,omitempty"`
	SystemPrompt       string                 `protobuf:"bytes,9,opt,name=system_prompt,json=systemPrompt,proto3" json:"system_prompt,omitempty"`             // 引用模版提示
	UserInputPrompt    string                 `protobuf:"bytes,10,opt,name=user_input_prompt,json=userInputPrompt,proto3" json:"user_input_prompt,omitempty"` // 引用模版提示
	Status             int32                  `protobuf:"varint,11,opt,name=status,proto3" json:"status,omitempty"`                                           // 2: 禁用, 1: 启用
	Type               int32                  `protobuf:"varint,12,opt,name=type,proto3" json:"type,omitempty"`                                               // 1 根 Agent, 2 子 Agent
	WithWriteTodos     bool                   `protobuf:"varint,13,opt,name=with_write_todos,json=withWriteTodos,proto3" json:"with_write_todos,omitempty"`
	WithWebSearchAgent bool                   `protobuf:"varint,14,opt,name=with_web_search_agent,json=withWebSearchAgent,proto3" json:"with_web_search_agent,omitempty"`
	SystemType         int32                  `protobuf:"varint,15,opt,name=system_type,json=systemType,proto3" json:"system_type,omitempty"` // 1-系统内置(不可删除), 2-用户自定义
	CreatedAt          int64                  `protobuf:"varint,16,opt,name=created_at,json=createdAt,proto3" json:"created_at,omitempty"`
	unknownFields      protoimpl.UnknownFields
	sizeCache          protoimpl.SizeCache
}

func (x *AgentInfo) Reset() {
	*x = AgentInfo{}
	mi := &file_api_ai_agent_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *AgentInfo) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*AgentInfo) ProtoMessage() {}

func (x *AgentInfo) ProtoReflect() protoreflect.Message {
	mi := &file_api_ai_agent_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use AgentInfo.ProtoReflect.Descriptor instead.
func (*AgentInfo) Descriptor() ([]byte, []int) {
	return file_api_ai_agent_proto_rawDescGZIP(), []int{1}
}

func (x *AgentInfo) GetId() int64 {
	if x != nil {
		return x.Id
	}
	return 0
}

func (x *AgentInfo) GetName() string {
	if x != nil {
		return x.Name
	}
	return ""
}

func (x *AgentInfo) GetCode() string {
	if x != nil {
		return x.Code
	}
	return ""
}

func (x *AgentInfo) GetDescription() string {
	if x != nil {
		return x.Description
	}
	return ""
}

func (x *AgentInfo) GetAdapterType() int32 {
	if x != nil {
		return x.AdapterType
	}
	return 0
}

func (x *AgentInfo) GetOriginalModelId() int64 {
	if x != nil {
		return x.OriginalModelId
	}
	return 0
}

func (x *AgentInfo) GetAiModel() *AgentModel {
	if x != nil {
		return x.AiModel
	}
	return nil
}

func (x *AgentInfo) GetMaxIteration() int32 {
	if x != nil {
		return x.MaxIteration
	}
	return 0
}

func (x *AgentInfo) GetSystemPrompt() string {
	if x != nil {
		return x.SystemPrompt
	}
	return ""
}

func (x *AgentInfo) GetUserInputPrompt() string {
	if x != nil {
		return x.UserInputPrompt
	}
	return ""
}

func (x *AgentInfo) GetStatus() int32 {
	if x != nil {
		return x.Status
	}
	return 0
}

func (x *AgentInfo) GetType() int32 {
	if x != nil {
		return x.Type
	}
	return 0
}

func (x *AgentInfo) GetWithWriteTodos() bool {
	if x != nil {
		return x.WithWriteTodos
	}
	return false
}

func (x *AgentInfo) GetWithWebSearchAgent() bool {
	if x != nil {
		return x.WithWebSearchAgent
	}
	return false
}

func (x *AgentInfo) GetSystemType() int32 {
	if x != nil {
		return x.SystemType
	}
	return 0
}

func (x *AgentInfo) GetCreatedAt() int64 {
	if x != nil {
		return x.CreatedAt
	}
	return 0
}

type ListAgentsRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Page          int32                  `protobuf:"varint,1,opt,name=page,proto3" json:"page,omitempty"`
	PageSize      int32                  `protobuf:"varint,2,opt,name=page_size,json=pageSize,proto3" json:"page_size,omitempty"`
	Name          string                 `protobuf:"bytes,3,opt,name=name,proto3" json:"name,omitempty"`
	Status        int32                  `protobuf:"varint,4,opt,name=status,proto3" json:"status,omitempty"`
	Type          int32                  `protobuf:"varint,5,opt,name=type,proto3" json:"type,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ListAgentsRequest) Reset() {
	*x = ListAgentsRequest{}
	mi := &file_api_ai_agent_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ListAgentsRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ListAgentsRequest) ProtoMessage() {}

func (x *ListAgentsRequest) ProtoReflect() protoreflect.Message {
	mi := &file_api_ai_agent_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ListAgentsRequest.ProtoReflect.Descriptor instead.
func (*ListAgentsRequest) Descriptor() ([]byte, []int) {
	return file_api_ai_agent_proto_rawDescGZIP(), []int{2}
}

func (x *ListAgentsRequest) GetPage() int32 {
	if x != nil {
		return x.Page
	}
	return 0
}

func (x *ListAgentsRequest) GetPageSize() int32 {
	if x != nil {
		return x.PageSize
	}
	return 0
}

func (x *ListAgentsRequest) GetName() string {
	if x != nil {
		return x.Name
	}
	return ""
}

func (x *ListAgentsRequest) GetStatus() int32 {
	if x != nil {
		return x.Status
	}
	return 0
}

func (x *ListAgentsRequest) GetType() int32 {
	if x != nil {
		return x.Type
	}
	return 0
}

type ListAgentsReply struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	List          []*AgentInfo           `protobuf:"bytes,1,rep,name=list,proto3" json:"list,omitempty"`
	Total         int64                  `protobuf:"varint,2,opt,name=total,proto3" json:"total,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ListAgentsReply) Reset() {
	*x = ListAgentsReply{}
	mi := &file_api_ai_agent_proto_msgTypes[3]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ListAgentsReply) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ListAgentsReply) ProtoMessage() {}

func (x *ListAgentsReply) ProtoReflect() protoreflect.Message {
	mi := &file_api_ai_agent_proto_msgTypes[3]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ListAgentsReply.ProtoReflect.Descriptor instead.
func (*ListAgentsReply) Descriptor() ([]byte, []int) {
	return file_api_ai_agent_proto_rawDescGZIP(), []int{3}
}

func (x *ListAgentsReply) GetList() []*AgentInfo {
	if x != nil {
		return x.List
	}
	return nil
}

func (x *ListAgentsReply) GetTotal() int64 {
	if x != nil {
		return x.Total
	}
	return 0
}

type CreateAgentRequest struct {
	state              protoimpl.MessageState `protogen:"open.v1"`
	Name               string                 `protobuf:"bytes,1,opt,name=name,proto3" json:"name,omitempty"`
	Code               string                 `protobuf:"bytes,2,opt,name=code,proto3" json:"code,omitempty"`
	Description        string                 `protobuf:"bytes,3,opt,name=description,proto3" json:"description,omitempty"`
	AdapterType        int32                  `protobuf:"varint,4,opt,name=adapter_type,json=adapterType,proto3" json:"adapter_type,omitempty"`
	OriginalModelId    int64                  `protobuf:"varint,5,opt,name=original_model_id,json=originalModelId,proto3" json:"original_model_id,omitempty"` // 来源ai模型id: 原始model ID：追溯引用的模型配置。
	AiModel            *AgentModel            `protobuf:"bytes,6,opt,name=ai_model,json=aiModel,proto3" json:"ai_model,omitempty"`                            // 通过original_model_id获取的模型配置，支持修改。
	MaxIteration       int32                  `protobuf:"varint,7,opt,name=max_iteration,json=maxIteration,proto3" json:"max_iteration,omitempty"`            // 最大迭代次数
	SystemPrompt       string                 `protobuf:"bytes,8,opt,name=system_prompt,json=systemPrompt,proto3" json:"system_prompt,omitempty"`             // 引用模版提示
	UserInputPrompt    string                 `protobuf:"bytes,9,opt,name=user_input_prompt,json=userInputPrompt,proto3" json:"user_input_prompt,omitempty"`  // 引用模版提示
	Status             int32                  `protobuf:"varint,10,opt,name=status,proto3" json:"status,omitempty"`                                           // 2: 禁用, 1: 启用
	Type               int32                  `protobuf:"varint,11,opt,name=type,proto3" json:"type,omitempty"`                                               // 1 根 Agent, 2 子 Agent
	WithWriteTodos     bool                   `protobuf:"varint,12,opt,name=with_write_todos,json=withWriteTodos,proto3" json:"with_write_todos,omitempty"`
	WithWebSearchAgent bool                   `protobuf:"varint,13,opt,name=with_web_search_agent,json=withWebSearchAgent,proto3" json:"with_web_search_agent,omitempty"`
	unknownFields      protoimpl.UnknownFields
	sizeCache          protoimpl.SizeCache
}

func (x *CreateAgentRequest) Reset() {
	*x = CreateAgentRequest{}
	mi := &file_api_ai_agent_proto_msgTypes[4]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *CreateAgentRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CreateAgentRequest) ProtoMessage() {}

func (x *CreateAgentRequest) ProtoReflect() protoreflect.Message {
	mi := &file_api_ai_agent_proto_msgTypes[4]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CreateAgentRequest.ProtoReflect.Descriptor instead.
func (*CreateAgentRequest) Descriptor() ([]byte, []int) {
	return file_api_ai_agent_proto_rawDescGZIP(), []int{4}
}

func (x *CreateAgentRequest) GetName() string {
	if x != nil {
		return x.Name
	}
	return ""
}

func (x *CreateAgentRequest) GetCode() string {
	if x != nil {
		return x.Code
	}
	return ""
}

func (x *CreateAgentRequest) GetDescription() string {
	if x != nil {
		return x.Description
	}
	return ""
}

func (x *CreateAgentRequest) GetAdapterType() int32 {
	if x != nil {
		return x.AdapterType
	}
	return 0
}

func (x *CreateAgentRequest) GetOriginalModelId() int64 {
	if x != nil {
		return x.OriginalModelId
	}
	return 0
}

func (x *CreateAgentRequest) GetAiModel() *AgentModel {
	if x != nil {
		return x.AiModel
	}
	return nil
}

func (x *CreateAgentRequest) GetMaxIteration() int32 {
	if x != nil {
		return x.MaxIteration
	}
	return 0
}

func (x *CreateAgentRequest) GetSystemPrompt() string {
	if x != nil {
		return x.SystemPrompt
	}
	return ""
}

func (x *CreateAgentRequest) GetUserInputPrompt() string {
	if x != nil {
		return x.UserInputPrompt
	}
	return ""
}

func (x *CreateAgentRequest) GetStatus() int32 {
	if x != nil {
		return x.Status
	}
	return 0
}

func (x *CreateAgentRequest) GetType() int32 {
	if x != nil {
		return x.Type
	}
	return 0
}

func (x *CreateAgentRequest) GetWithWriteTodos() bool {
	if x != nil {
		return x.WithWriteTodos
	}
	return false
}

func (x *CreateAgentRequest) GetWithWebSearchAgent() bool {
	if x != nil {
		return x.WithWebSearchAgent
	}
	return false
}

type UpdateAgentRequest struct {
	state              protoimpl.MessageState `protogen:"open.v1"`
	Id                 int64                  `protobuf:"varint,1,opt,name=id,proto3" json:"id,omitempty"`
	Name               string                 `protobuf:"bytes,2,opt,name=name,proto3" json:"name,omitempty"`
	Code               string                 `protobuf:"bytes,3,opt,name=code,proto3" json:"code,omitempty"`
	Description        string                 `protobuf:"bytes,4,opt,name=description,proto3" json:"description,omitempty"`
	AdapterType        int32                  `protobuf:"varint,5,opt,name=adapter_type,json=adapterType,proto3" json:"adapter_type,omitempty"`
	OriginalModelId    int64                  `protobuf:"varint,6,opt,name=original_model_id,json=originalModelId,proto3" json:"original_model_id,omitempty"` // 来源ai模型id: 原始model ID：追溯引用的模型配置。
	AiModel            *AgentModel            `protobuf:"bytes,7,opt,name=ai_model,json=aiModel,proto3" json:"ai_model,omitempty"`                            // 通过original_model_id获取的模型配置，支持修改。
	MaxIteration       int32                  `protobuf:"varint,8,opt,name=max_iteration,json=maxIteration,proto3" json:"max_iteration,omitempty"`            // 最大迭代次数
	SystemPrompt       string                 `protobuf:"bytes,9,opt,name=system_prompt,json=systemPrompt,proto3" json:"system_prompt,omitempty"`             // 引用模版提示
	UserInputPrompt    string                 `protobuf:"bytes,10,opt,name=user_input_prompt,json=userInputPrompt,proto3" json:"user_input_prompt,omitempty"` // 引用模版提示
	Status             int32                  `protobuf:"varint,11,opt,name=status,proto3" json:"status,omitempty"`                                           // 2: 禁用, 1: 启用
	Type               int32                  `protobuf:"varint,12,opt,name=type,proto3" json:"type,omitempty"`                                               // 1 根 Agent, 2 子 Agent
	WithWriteTodos     bool                   `protobuf:"varint,13,opt,name=with_write_todos,json=withWriteTodos,proto3" json:"with_write_todos,omitempty"`
	WithWebSearchAgent bool                   `protobuf:"varint,14,opt,name=with_web_search_agent,json=withWebSearchAgent,proto3" json:"with_web_search_agent,omitempty"`
	unknownFields      protoimpl.UnknownFields
	sizeCache          protoimpl.SizeCache
}

func (x *UpdateAgentRequest) Reset() {
	*x = UpdateAgentRequest{}
	mi := &file_api_ai_agent_proto_msgTypes[5]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *UpdateAgentRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*UpdateAgentRequest) ProtoMessage() {}

func (x *UpdateAgentRequest) ProtoReflect() protoreflect.Message {
	mi := &file_api_ai_agent_proto_msgTypes[5]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use UpdateAgentRequest.ProtoReflect.Descriptor instead.
func (*UpdateAgentRequest) Descriptor() ([]byte, []int) {
	return file_api_ai_agent_proto_rawDescGZIP(), []int{5}
}

func (x *UpdateAgentRequest) GetId() int64 {
	if x != nil {
		return x.Id
	}
	return 0
}

func (x *UpdateAgentRequest) GetName() string {
	if x != nil {
		return x.Name
	}
	return ""
}

func (x *UpdateAgentRequest) GetCode() string {
	if x != nil {
		return x.Code
	}
	return ""
}

func (x *UpdateAgentRequest) GetDescription() string {
	if x != nil {
		return x.Description
	}
	return ""
}

func (x *UpdateAgentRequest) GetAdapterType() int32 {
	if x != nil {
		return x.AdapterType
	}
	return 0
}

func (x *UpdateAgentRequest) GetOriginalModelId() int64 {
	if x != nil {
		return x.OriginalModelId
	}
	return 0
}

func (x *UpdateAgentRequest) GetAiModel() *AgentModel {
	if x != nil {
		return x.AiModel
	}
	return nil
}

func (x *UpdateAgentRequest) GetMaxIteration() int32 {
	if x != nil {
		return x.MaxIteration
	}
	return 0
}

func (x *UpdateAgentRequest) GetSystemPrompt() string {
	if x != nil {
		return x.SystemPrompt
	}
	return ""
}

func (x *UpdateAgentRequest) GetUserInputPrompt() string {
	if x != nil {
		return x.UserInputPrompt
	}
	return ""
}

func (x *UpdateAgentRequest) GetStatus() int32 {
	if x != nil {
		return x.Status
	}
	return 0
}

func (x *UpdateAgentRequest) GetType() int32 {
	if x != nil {
		return x.Type
	}
	return 0
}

func (x *UpdateAgentRequest) GetWithWriteTodos() bool {
	if x != nil {
		return x.WithWriteTodos
	}
	return false
}

func (x *UpdateAgentRequest) GetWithWebSearchAgent() bool {
	if x != nil {
		return x.WithWebSearchAgent
	}
	return false
}

var File_api_ai_agent_proto protoreflect.FileDescriptor

const file_api_ai_agent_proto_rawDesc = "" +
	"\n" +
	"\x12api/ai/agent.proto\x12\x02ai\x1a\x1cgoogle/api/annotations.proto\x1a\x1bgoogle/protobuf/empty.proto\x1a.protoc-gen-openapiv2/options/annotations.proto\"\xd1\x01\n" +
	"\n" +
	"AgentModel\x12\x1a\n" +
	"\bcategory\x18\x01 \x01(\x05R\bcategory\x12\x1d\n" +
	"\n" +
	"model_type\x18\x02 \x01(\tR\tmodelType\x12\x1d\n" +
	"\n" +
	"model_name\x18\x03 \x01(\tR\tmodelName\x12\x17\n" +
	"\aapi_key\x18\x04 \x01(\tR\x06apiKey\x12\x19\n" +
	"\bbase_url\x18\x05 \x01(\tR\abaseUrl\x12 \n" +
	"\vtemperature\x18\x06 \x01(\x02R\vtemperature\x12\x13\n" +
	"\x05top_p\x18\a \x01(\x02R\x04topP\"\x9e\x04\n" +
	"\tAgentInfo\x12\x0e\n" +
	"\x02id\x18\x01 \x01(\x03R\x02id\x12\x12\n" +
	"\x04name\x18\x02 \x01(\tR\x04name\x12\x12\n" +
	"\x04code\x18\x03 \x01(\tR\x04code\x12 \n" +
	"\vdescription\x18\x04 \x01(\tR\vdescription\x12!\n" +
	"\fadapter_type\x18\x05 \x01(\x05R\vadapterType\x12*\n" +
	"\x11original_model_id\x18\x06 \x01(\x03R\x0foriginalModelId\x12)\n" +
	"\bai_model\x18\a \x01(\v2\x0e.ai.AgentModelR\aaiModel\x12#\n" +
	"\rmax_iteration\x18\b \x01(\x05R\fmaxIteration\x12#\n" +
	"\rsystem_prompt\x18\t \x01(\tR\fsystemPrompt\x12*\n" +
	"\x11user_input_prompt\x18\n" +
	" \x01(\tR\x0fuserInputPrompt\x12\x16\n" +
	"\x06status\x18\v \x01(\x05R\x06status\x12\x12\n" +
	"\x04type\x18\f \x01(\x05R\x04type\x12(\n" +
	"\x10with_write_todos\x18\r \x01(\bR\x0ewithWriteTodos\x121\n" +
	"\x15with_web_search_agent\x18\x0e \x01(\bR\x12withWebSearchAgent\x12\x1f\n" +
	"\vsystem_type\x18\x0f \x01(\x05R\n" +
	"systemType\x12\x1d\n" +
	"\n" +
	"created_at\x18\x10 \x01(\x03R\tcreatedAt\"\x84\x01\n" +
	"\x11ListAgentsRequest\x12\x12\n" +
	"\x04page\x18\x01 \x01(\x05R\x04page\x12\x1b\n" +
	"\tpage_size\x18\x02 \x01(\x05R\bpageSize\x12\x12\n" +
	"\x04name\x18\x03 \x01(\tR\x04name\x12\x16\n" +
	"\x06status\x18\x04 \x01(\x05R\x06status\x12\x12\n" +
	"\x04type\x18\x05 \x01(\x05R\x04type\"J\n" +
	"\x0fListAgentsReply\x12!\n" +
	"\x04list\x18\x01 \x03(\v2\r.ai.AgentInfoR\x04list\x12\x14\n" +
	"\x05total\x18\x02 \x01(\x03R\x05total\"\xd7\x03\n" +
	"\x12CreateAgentRequest\x12\x12\n" +
	"\x04name\x18\x01 \x01(\tR\x04name\x12\x12\n" +
	"\x04code\x18\x02 \x01(\tR\x04code\x12 \n" +
	"\vdescription\x18\x03 \x01(\tR\vdescription\x12!\n" +
	"\fadapter_type\x18\x04 \x01(\x05R\vadapterType\x12*\n" +
	"\x11original_model_id\x18\x05 \x01(\x03R\x0foriginalModelId\x12)\n" +
	"\bai_model\x18\x06 \x01(\v2\x0e.ai.AgentModelR\aaiModel\x12#\n" +
	"\rmax_iteration\x18\a \x01(\x05R\fmaxIteration\x12#\n" +
	"\rsystem_prompt\x18\b \x01(\tR\fsystemPrompt\x12*\n" +
	"\x11user_input_prompt\x18\t \x01(\tR\x0fuserInputPrompt\x12\x16\n" +
	"\x06status\x18\n" +
	" \x01(\x05R\x06status\x12\x12\n" +
	"\x04type\x18\v \x01(\x05R\x04type\x12(\n" +
	"\x10with_write_todos\x18\f \x01(\bR\x0ewithWriteTodos\x121\n" +
	"\x15with_web_search_agent\x18\r \x01(\bR\x12withWebSearchAgent\"\xe7\x03\n" +
	"\x12UpdateAgentRequest\x12\x0e\n" +
	"\x02id\x18\x01 \x01(\x03R\x02id\x12\x12\n" +
	"\x04name\x18\x02 \x01(\tR\x04name\x12\x12\n" +
	"\x04code\x18\x03 \x01(\tR\x04code\x12 \n" +
	"\vdescription\x18\x04 \x01(\tR\vdescription\x12!\n" +
	"\fadapter_type\x18\x05 \x01(\x05R\vadapterType\x12*\n" +
	"\x11original_model_id\x18\x06 \x01(\x03R\x0foriginalModelId\x12)\n" +
	"\bai_model\x18\a \x01(\v2\x0e.ai.AgentModelR\aaiModel\x12#\n" +
	"\rmax_iteration\x18\b \x01(\x05R\fmaxIteration\x12#\n" +
	"\rsystem_prompt\x18\t \x01(\tR\fsystemPrompt\x12*\n" +
	"\x11user_input_prompt\x18\n" +
	" \x01(\tR\x0fuserInputPrompt\x12\x16\n" +
	"\x06status\x18\v \x01(\x05R\x06status\x12\x12\n" +
	"\x04type\x18\f \x01(\x05R\x04type\x12(\n" +
	"\x10with_write_todos\x18\r \x01(\bR\x0ewithWriteTodos\x121\n" +
	"\x15with_web_search_agent\x18\x0e \x01(\bR\x12withWebSearchAgentB1\n" +
	"\x11dev.kratos.api.aiB\aAiProtoP\x01Z\x11backend/api/ai;aib\x06proto3"

var (
	file_api_ai_agent_proto_rawDescOnce sync.Once
	file_api_ai_agent_proto_rawDescData []byte
)

func file_api_ai_agent_proto_rawDescGZIP() []byte {
	file_api_ai_agent_proto_rawDescOnce.Do(func() {
		file_api_ai_agent_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_api_ai_agent_proto_rawDesc), len(file_api_ai_agent_proto_rawDesc)))
	})
	return file_api_ai_agent_proto_rawDescData
}

var file_api_ai_agent_proto_msgTypes = make([]protoimpl.MessageInfo, 6)
var file_api_ai_agent_proto_goTypes = []any{
	(*AgentModel)(nil),         // 0: ai.AgentModel
	(*AgentInfo)(nil),          // 1: ai.AgentInfo
	(*ListAgentsRequest)(nil),  // 2: ai.ListAgentsRequest
	(*ListAgentsReply)(nil),    // 3: ai.ListAgentsReply
	(*CreateAgentRequest)(nil), // 4: ai.CreateAgentRequest
	(*UpdateAgentRequest)(nil), // 5: ai.UpdateAgentRequest
}
var file_api_ai_agent_proto_depIdxs = []int32{
	0, // 0: ai.AgentInfo.ai_model:type_name -> ai.AgentModel
	1, // 1: ai.ListAgentsReply.list:type_name -> ai.AgentInfo
	0, // 2: ai.CreateAgentRequest.ai_model:type_name -> ai.AgentModel
	0, // 3: ai.UpdateAgentRequest.ai_model:type_name -> ai.AgentModel
	4, // [4:4] is the sub-list for method output_type
	4, // [4:4] is the sub-list for method input_type
	4, // [4:4] is the sub-list for extension type_name
	4, // [4:4] is the sub-list for extension extendee
	0, // [0:4] is the sub-list for field type_name
}

func init() { file_api_ai_agent_proto_init() }
func file_api_ai_agent_proto_init() {
	if File_api_ai_agent_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_api_ai_agent_proto_rawDesc), len(file_api_ai_agent_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   6,
			NumExtensions: 0,
			NumServices:   0,
		},
		GoTypes:           file_api_ai_agent_proto_goTypes,
		DependencyIndexes: file_api_ai_agent_proto_depIdxs,
		MessageInfos:      file_api_ai_agent_proto_msgTypes,
	}.Build()
	File_api_ai_agent_proto = out.File
	file_api_ai_agent_proto_goTypes = nil
	file_api_ai_agent_proto_depIdxs = nil
}
