// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.10
// 	protoc        v5.29.3
// source: api/ai/ai.proto

package ai

import (
	_ "github.com/grpc-ecosystem/grpc-gateway/v2/protoc-gen-openapiv2/options"
	_ "google.golang.org/genproto/googleapis/api/annotations"
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	emptypb "google.golang.org/protobuf/types/known/emptypb"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

// ========== Common ==========
type IdRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Id            int64                  `protobuf:"varint,1,opt,name=id,proto3" json:"id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *IdRequest) Reset() {
	*x = IdRequest{}
	mi := &file_api_ai_ai_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *IdRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*IdRequest) ProtoMessage() {}

func (x *IdRequest) ProtoReflect() protoreflect.Message {
	mi := &file_api_ai_ai_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use IdRequest.ProtoReflect.Descriptor instead.
func (*IdRequest) Descriptor() ([]byte, []int) {
	return file_api_ai_ai_proto_rawDescGZIP(), []int{0}
}

func (x *IdRequest) GetId() int64 {
	if x != nil {
		return x.Id
	}
	return 0
}

type EmptyReply struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *EmptyReply) Reset() {
	*x = EmptyReply{}
	mi := &file_api_ai_ai_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *EmptyReply) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*EmptyReply) ProtoMessage() {}

func (x *EmptyReply) ProtoReflect() protoreflect.Message {
	mi := &file_api_ai_ai_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use EmptyReply.ProtoReflect.Descriptor instead.
func (*EmptyReply) Descriptor() ([]byte, []int) {
	return file_api_ai_ai_proto_rawDescGZIP(), []int{1}
}

var File_api_ai_ai_proto protoreflect.FileDescriptor

const file_api_ai_ai_proto_rawDesc = "" +
	"\n" +
	"\x0fapi/ai/ai.proto\x12\x02ai\x1a\x1cgoogle/api/annotations.proto\x1a\x1bgoogle/protobuf/empty.proto\x1a.protoc-gen-openapiv2/options/annotations.proto\x1a\x12api/ai/agent.proto\x1a\x12api/ai/model.proto\x1a\x11api/ai/tool.proto\x1a\x13api/ai/prompt.proto\x1a\x18api/ai/application.proto\"\x1b\n" +
	"\tIdRequest\x12\x0e\n" +
	"\x02id\x18\x01 \x01(\x03R\x02id\"\f\n" +
	"\n" +
	"EmptyReply2\xe1\x11\n" +
	"\x02AI\x12P\n" +
	"\n" +
	"ListAgents\x12\x15.ai.ListAgentsRequest\x1a\x13.ai.ListAgentsReply\"\x16\x82\xd3\xe4\x93\x02\x10\x12\x0e/api/ai/agents\x12E\n" +
	"\bGetAgent\x12\r.ai.IdRequest\x1a\r.ai.AgentInfo\"\x1b\x82\xd3\xe4\x93\x02\x15\x12\x13/api/ai/agents/{id}\x12O\n" +
	"\vCreateAgent\x12\x16.ai.CreateAgentRequest\x1a\r.ai.AgentInfo\"\x19\x82\xd3\xe4\x93\x02\x13:\x01*\"\x0e/api/ai/agents\x12]\n" +
	"\vUpdateAgent\x12\x16.ai.UpdateAgentRequest\x1a\x16.google.protobuf.Empty\"\x1e\x82\xd3\xe4\x93\x02\x18:\x01*\x1a\x13/api/ai/agents/{id}\x12Q\n" +
	"\vDeleteAgent\x12\r.ai.IdRequest\x1a\x16.google.protobuf.Empty\"\x1b\x82\xd3\xe4\x93\x02\x15*\x13/api/ai/agents/{id}\x12P\n" +
	"\n" +
	"ListModels\x12\x15.ai.ListModelsRequest\x1a\x13.ai.ListModelsReply\"\x16\x82\xd3\xe4\x93\x02\x10\x12\x0e/api/ai/models\x12E\n" +
	"\bGetModel\x12\r.ai.IdRequest\x1a\r.ai.ModelInfo\"\x1b\x82\xd3\xe4\x93\x02\x15\x12\x13/api/ai/models/{id}\x12O\n" +
	"\vCreateModel\x12\x16.ai.CreateModelRequest\x1a\r.ai.ModelInfo\"\x19\x82\xd3\xe4\x93\x02\x13:\x01*\"\x0e/api/ai/models\x12]\n" +
	"\vUpdateModel\x12\x16.ai.UpdateModelRequest\x1a\x16.google.protobuf.Empty\"\x1e\x82\xd3\xe4\x93\x02\x18:\x01*\x1a\x13/api/ai/models/{id}\x12Q\n" +
	"\vDeleteModel\x12\r.ai.IdRequest\x1a\x16.google.protobuf.Empty\"\x1b\x82\xd3\xe4\x93\x02\x15*\x13/api/ai/models/{id}\x12T\n" +
	"\vListPrompts\x12\x16.ai.ListPromptsRequest\x1a\x14.ai.ListPromptsReply\"\x17\x82\xd3\xe4\x93\x02\x11\x12\x0f/api/ai/prompts\x12H\n" +
	"\tGetPrompt\x12\r.ai.IdRequest\x1a\x0e.ai.PromptInfo\"\x1c\x82\xd3\xe4\x93\x02\x16\x12\x14/api/ai/prompts/{id}\x12S\n" +
	"\fCreatePrompt\x12\x17.ai.CreatePromptRequest\x1a\x0e.ai.PromptInfo\"\x1a\x82\xd3\xe4\x93\x02\x14:\x01*\"\x0f/api/ai/prompts\x12`\n" +
	"\fUpdatePrompt\x12\x17.ai.UpdatePromptRequest\x1a\x16.google.protobuf.Empty\"\x1f\x82\xd3\xe4\x93\x02\x19:\x01*\x1a\x14/api/ai/prompts/{id}\x12S\n" +
	"\fDeletePrompt\x12\r.ai.IdRequest\x1a\x16.google.protobuf.Empty\"\x1c\x82\xd3\xe4\x93\x02\x16*\x14/api/ai/prompts/{id}\x12L\n" +
	"\tListTools\x12\x14.ai.ListToolsRequest\x1a\x12.ai.ListToolsReply\"\x15\x82\xd3\xe4\x93\x02\x0f\x12\r/api/ai/tools\x12B\n" +
	"\aGetTool\x12\r.ai.IdRequest\x1a\f.ai.ToolInfo\"\x1a\x82\xd3\xe4\x93\x02\x14\x12\x12/api/ai/tools/{id}\x12K\n" +
	"\n" +
	"CreateTool\x12\x15.ai.CreateToolRequest\x1a\f.ai.ToolInfo\"\x18\x82\xd3\xe4\x93\x02\x12:\x01*\"\r/api/ai/tools\x12Z\n" +
	"\n" +
	"UpdateTool\x12\x15.ai.UpdateToolRequest\x1a\x16.google.protobuf.Empty\"\x1d\x82\xd3\xe4\x93\x02\x17:\x01*\x1a\x12/api/ai/tools/{id}\x12O\n" +
	"\n" +
	"DeleteTool\x12\r.ai.IdRequest\x1a\x16.google.protobuf.Empty\"\x1a\x82\xd3\xe4\x93\x02\x14*\x12/api/ai/tools/{id}\x12o\n" +
	"\x0eBatchBindTools\x12\x19.ai.BatchBindToolsRequest\x1a\x16.google.protobuf.Empty\"*\x82\xd3\xe4\x93\x02$:\x01*\"\x1f/api/ai/agents/{agent_id}/tools\x12h\n" +
	"\x10ListApplications\x12\x1b.ai.ListApplicationsRequest\x1a\x19.ai.ListApplicationsReply\"\x1c\x82\xd3\xe4\x93\x02\x16\x12\x14/api/ai/applications\x12W\n" +
	"\x0eGetApplication\x12\r.ai.IdRequest\x1a\x13.ai.ApplicationInfo\"!\x82\xd3\xe4\x93\x02\x1b\x12\x19/api/ai/applications/{id}\x12g\n" +
	"\x11CreateApplication\x12\x1c.ai.CreateApplicationRequest\x1a\x13.ai.ApplicationInfo\"\x1f\x82\xd3\xe4\x93\x02\x19:\x01*\"\x14/api/ai/applications\x12o\n" +
	"\x11UpdateApplication\x12\x1c.ai.UpdateApplicationRequest\x1a\x16.google.protobuf.Empty\"$\x82\xd3\xe4\x93\x02\x1e:\x01*\x1a\x19/api/ai/applications/{id}\x12]\n" +
	"\x11DeleteApplication\x12\r.ai.IdRequest\x1a\x16.google.protobuf.Empty\"!\x82\xd3\xe4\x93\x02\x1b*\x19/api/ai/applications/{id}B1\n" +
	"\x11dev.kratos.api.aiB\aAiProtoP\x01Z\x11backend/api/ai;aib\x06proto3"

var (
	file_api_ai_ai_proto_rawDescOnce sync.Once
	file_api_ai_ai_proto_rawDescData []byte
)

func file_api_ai_ai_proto_rawDescGZIP() []byte {
	file_api_ai_ai_proto_rawDescOnce.Do(func() {
		file_api_ai_ai_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_api_ai_ai_proto_rawDesc), len(file_api_ai_ai_proto_rawDesc)))
	})
	return file_api_ai_ai_proto_rawDescData
}

var file_api_ai_ai_proto_msgTypes = make([]protoimpl.MessageInfo, 2)
var file_api_ai_ai_proto_goTypes = []any{
	(*IdRequest)(nil),                // 0: ai.IdRequest
	(*EmptyReply)(nil),               // 1: ai.EmptyReply
	(*ListAgentsRequest)(nil),        // 2: ai.ListAgentsRequest
	(*CreateAgentRequest)(nil),       // 3: ai.CreateAgentRequest
	(*UpdateAgentRequest)(nil),       // 4: ai.UpdateAgentRequest
	(*ListModelsRequest)(nil),        // 5: ai.ListModelsRequest
	(*CreateModelRequest)(nil),       // 6: ai.CreateModelRequest
	(*UpdateModelRequest)(nil),       // 7: ai.UpdateModelRequest
	(*ListPromptsRequest)(nil),       // 8: ai.ListPromptsRequest
	(*CreatePromptRequest)(nil),      // 9: ai.CreatePromptRequest
	(*UpdatePromptRequest)(nil),      // 10: ai.UpdatePromptRequest
	(*ListToolsRequest)(nil),         // 11: ai.ListToolsRequest
	(*CreateToolRequest)(nil),        // 12: ai.CreateToolRequest
	(*UpdateToolRequest)(nil),        // 13: ai.UpdateToolRequest
	(*BatchBindToolsRequest)(nil),    // 14: ai.BatchBindToolsRequest
	(*ListApplicationsRequest)(nil),  // 15: ai.ListApplicationsRequest
	(*CreateApplicationRequest)(nil), // 16: ai.CreateApplicationRequest
	(*UpdateApplicationRequest)(nil), // 17: ai.UpdateApplicationRequest
	(*ListAgentsReply)(nil),          // 18: ai.ListAgentsReply
	(*AgentInfo)(nil),                // 19: ai.AgentInfo
	(*emptypb.Empty)(nil),            // 20: google.protobuf.Empty
	(*ListModelsReply)(nil),          // 21: ai.ListModelsReply
	(*ModelInfo)(nil),                // 22: ai.ModelInfo
	(*ListPromptsReply)(nil),         // 23: ai.ListPromptsReply
	(*PromptInfo)(nil),               // 24: ai.PromptInfo
	(*ListToolsReply)(nil),           // 25: ai.ListToolsReply
	(*ToolInfo)(nil),                 // 26: ai.ToolInfo
	(*ListApplicationsReply)(nil),    // 27: ai.ListApplicationsReply
	(*ApplicationInfo)(nil),          // 28: ai.ApplicationInfo
}
var file_api_ai_ai_proto_depIdxs = []int32{
	2,  // 0: ai.AI.ListAgents:input_type -> ai.ListAgentsRequest
	0,  // 1: ai.AI.GetAgent:input_type -> ai.IdRequest
	3,  // 2: ai.AI.CreateAgent:input_type -> ai.CreateAgentRequest
	4,  // 3: ai.AI.UpdateAgent:input_type -> ai.UpdateAgentRequest
	0,  // 4: ai.AI.DeleteAgent:input_type -> ai.IdRequest
	5,  // 5: ai.AI.ListModels:input_type -> ai.ListModelsRequest
	0,  // 6: ai.AI.GetModel:input_type -> ai.IdRequest
	6,  // 7: ai.AI.CreateModel:input_type -> ai.CreateModelRequest
	7,  // 8: ai.AI.UpdateModel:input_type -> ai.UpdateModelRequest
	0,  // 9: ai.AI.DeleteModel:input_type -> ai.IdRequest
	8,  // 10: ai.AI.ListPrompts:input_type -> ai.ListPromptsRequest
	0,  // 11: ai.AI.GetPrompt:input_type -> ai.IdRequest
	9,  // 12: ai.AI.CreatePrompt:input_type -> ai.CreatePromptRequest
	10, // 13: ai.AI.UpdatePrompt:input_type -> ai.UpdatePromptRequest
	0,  // 14: ai.AI.DeletePrompt:input_type -> ai.IdRequest
	11, // 15: ai.AI.ListTools:input_type -> ai.ListToolsRequest
	0,  // 16: ai.AI.GetTool:input_type -> ai.IdRequest
	12, // 17: ai.AI.CreateTool:input_type -> ai.CreateToolRequest
	13, // 18: ai.AI.UpdateTool:input_type -> ai.UpdateToolRequest
	0,  // 19: ai.AI.DeleteTool:input_type -> ai.IdRequest
	14, // 20: ai.AI.BatchBindTools:input_type -> ai.BatchBindToolsRequest
	15, // 21: ai.AI.ListApplications:input_type -> ai.ListApplicationsRequest
	0,  // 22: ai.AI.GetApplication:input_type -> ai.IdRequest
	16, // 23: ai.AI.CreateApplication:input_type -> ai.CreateApplicationRequest
	17, // 24: ai.AI.UpdateApplication:input_type -> ai.UpdateApplicationRequest
	0,  // 25: ai.AI.DeleteApplication:input_type -> ai.IdRequest
	18, // 26: ai.AI.ListAgents:output_type -> ai.ListAgentsReply
	19, // 27: ai.AI.GetAgent:output_type -> ai.AgentInfo
	19, // 28: ai.AI.CreateAgent:output_type -> ai.AgentInfo
	20, // 29: ai.AI.UpdateAgent:output_type -> google.protobuf.Empty
	20, // 30: ai.AI.DeleteAgent:output_type -> google.protobuf.Empty
	21, // 31: ai.AI.ListModels:output_type -> ai.ListModelsReply
	22, // 32: ai.AI.GetModel:output_type -> ai.ModelInfo
	22, // 33: ai.AI.CreateModel:output_type -> ai.ModelInfo
	20, // 34: ai.AI.UpdateModel:output_type -> google.protobuf.Empty
	20, // 35: ai.AI.DeleteModel:output_type -> google.protobuf.Empty
	23, // 36: ai.AI.ListPrompts:output_type -> ai.ListPromptsReply
	24, // 37: ai.AI.GetPrompt:output_type -> ai.PromptInfo
	24, // 38: ai.AI.CreatePrompt:output_type -> ai.PromptInfo
	20, // 39: ai.AI.UpdatePrompt:output_type -> google.protobuf.Empty
	20, // 40: ai.AI.DeletePrompt:output_type -> google.protobuf.Empty
	25, // 41: ai.AI.ListTools:output_type -> ai.ListToolsReply
	26, // 42: ai.AI.GetTool:output_type -> ai.ToolInfo
	26, // 43: ai.AI.CreateTool:output_type -> ai.ToolInfo
	20, // 44: ai.AI.UpdateTool:output_type -> google.protobuf.Empty
	20, // 45: ai.AI.DeleteTool:output_type -> google.protobuf.Empty
	20, // 46: ai.AI.BatchBindTools:output_type -> google.protobuf.Empty
	27, // 47: ai.AI.ListApplications:output_type -> ai.ListApplicationsReply
	28, // 48: ai.AI.GetApplication:output_type -> ai.ApplicationInfo
	28, // 49: ai.AI.CreateApplication:output_type -> ai.ApplicationInfo
	20, // 50: ai.AI.UpdateApplication:output_type -> google.protobuf.Empty
	20, // 51: ai.AI.DeleteApplication:output_type -> google.protobuf.Empty
	26, // [26:52] is the sub-list for method output_type
	0,  // [0:26] is the sub-list for method input_type
	0,  // [0:0] is the sub-list for extension type_name
	0,  // [0:0] is the sub-list for extension extendee
	0,  // [0:0] is the sub-list for field type_name
}

func init() { file_api_ai_ai_proto_init() }
func file_api_ai_ai_proto_init() {
	if File_api_ai_ai_proto != nil {
		return
	}
	file_api_ai_agent_proto_init()
	file_api_ai_model_proto_init()
	file_api_ai_tool_proto_init()
	file_api_ai_prompt_proto_init()
	file_api_ai_application_proto_init()
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_api_ai_ai_proto_rawDesc), len(file_api_ai_ai_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   2,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_api_ai_ai_proto_goTypes,
		DependencyIndexes: file_api_ai_ai_proto_depIdxs,
		MessageInfos:      file_api_ai_ai_proto_msgTypes,
	}.Build()
	File_api_ai_ai_proto = out.File
	file_api_ai_ai_proto_goTypes = nil
	file_api_ai_ai_proto_depIdxs = nil
}
