// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.10
// 	protoc        v5.29.3
// source: api/ai/application.proto

package ai

import (
	_ "github.com/grpc-ecosystem/grpc-gateway/v2/protoc-gen-openapiv2/options"
	_ "google.golang.org/genproto/googleapis/api/annotations"
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	_ "google.golang.org/protobuf/types/known/emptypb"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

// Name        string        `json:"name" gorm:"type:varchar(100);comment:'名称'"`             // 名称
// Code        string        `json:"code" gorm:"uniqueIndex;type:varchar(100);comment:'编码'"` // 编码
// Description string        `json:"description" gorm:"size:500;comment:'描述'"`
// Version     string        `json:"version" gorm:"size:20;default:'1.0.0';comment:'版本号'"`
// Mode        ProgramMode   `json:"mode" gorm:"default:2;comment:'模式'"`              // 模式：1.单agent模式（只有一个agent，采用Ark原理，支持adk或者普通enio）2. 多agent模式（就是deepadk或者adk）
// Status      models.Status `json:"status" gorm:"default:1;comment:'状态'"`            // 2: 禁用, 1: 启用
// Type        ProgramType   `json:"type" gorm:"default:1;comment:'程序类型'"`            // 1. 预定义，2. 自定义
// Scope       Scope         `json:"scope" gorm:"default:1;comment:'作用粒度'"`           // 作用粒度：1.所有人，2.指定角色，3.指定用户
// SelfAgent   *AIAgent      `json:"self_agent" gorm:"type:json;comment:'自定义 Agent'"` // 自定义 Agent(通过agent列表获取，重新自定义)
type ApplicationInfo struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Id            int64                  `protobuf:"varint,1,opt,name=id,proto3" json:"id,omitempty"`
	Name          string                 `protobuf:"bytes,2,opt,name=name,proto3" json:"name,omitempty"`                              // 名称
	Code          string                 `protobuf:"bytes,3,opt,name=code,proto3" json:"code,omitempty"`                              // 编码
	Description   string                 `protobuf:"bytes,4,opt,name=description,proto3" json:"description,omitempty"`                // 描述
	Version       string                 `protobuf:"bytes,5,opt,name=version,proto3" json:"version,omitempty"`                        // 版本号
	Mode          int32                  `protobuf:"varint,6,opt,name=mode,proto3" json:"mode,omitempty"`                             // 模式 1.单agent模式（只有一个agent，采用Ark原理，支持adk或者普通enio）2. 多agent模式（就是deepadk或者adk）
	Status        int32                  `protobuf:"varint,7,opt,name=status,proto3" json:"status,omitempty"`                         // 状态 2: 禁用, 1: 启用
	Type          int32                  `protobuf:"varint,8,opt,name=type,proto3" json:"type,omitempty"`                             // 程序类型 1. 预定义，2. 自定义
	Scope         int32                  `protobuf:"varint,9,opt,name=scope,proto3" json:"scope,omitempty"`                           // 作用粒度 1.所有人，2.指定角色，3.指定用户
	SelfAgent     *AppAgent              `protobuf:"bytes,10,opt,name=self_agent,json=selfAgent,proto3" json:"self_agent,omitempty"`  // 自定义 Agent (通过agent列表获取，支持重新自定义)
	CreatedAt     int64                  `protobuf:"varint,11,opt,name=created_at,json=createdAt,proto3" json:"created_at,omitempty"` // 创建时间
	Schema        string                 `protobuf:"bytes,12,opt,name=schema,proto3" json:"schema,omitempty"`                         // 拖拽页面布局存档。
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ApplicationInfo) Reset() {
	*x = ApplicationInfo{}
	mi := &file_api_ai_application_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ApplicationInfo) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ApplicationInfo) ProtoMessage() {}

func (x *ApplicationInfo) ProtoReflect() protoreflect.Message {
	mi := &file_api_ai_application_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ApplicationInfo.ProtoReflect.Descriptor instead.
func (*ApplicationInfo) Descriptor() ([]byte, []int) {
	return file_api_ai_application_proto_rawDescGZIP(), []int{0}
}

func (x *ApplicationInfo) GetId() int64 {
	if x != nil {
		return x.Id
	}
	return 0
}

func (x *ApplicationInfo) GetName() string {
	if x != nil {
		return x.Name
	}
	return ""
}

func (x *ApplicationInfo) GetCode() string {
	if x != nil {
		return x.Code
	}
	return ""
}

func (x *ApplicationInfo) GetDescription() string {
	if x != nil {
		return x.Description
	}
	return ""
}

func (x *ApplicationInfo) GetVersion() string {
	if x != nil {
		return x.Version
	}
	return ""
}

func (x *ApplicationInfo) GetMode() int32 {
	if x != nil {
		return x.Mode
	}
	return 0
}

func (x *ApplicationInfo) GetStatus() int32 {
	if x != nil {
		return x.Status
	}
	return 0
}

func (x *ApplicationInfo) GetType() int32 {
	if x != nil {
		return x.Type
	}
	return 0
}

func (x *ApplicationInfo) GetScope() int32 {
	if x != nil {
		return x.Scope
	}
	return 0
}

func (x *ApplicationInfo) GetSelfAgent() *AppAgent {
	if x != nil {
		return x.SelfAgent
	}
	return nil
}

func (x *ApplicationInfo) GetCreatedAt() int64 {
	if x != nil {
		return x.CreatedAt
	}
	return 0
}

func (x *ApplicationInfo) GetSchema() string {
	if x != nil {
		return x.Schema
	}
	return ""
}

type ListApplicationsRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Page          int32                  `protobuf:"varint,1,opt,name=page,proto3" json:"page,omitempty"`
	PageSize      int32                  `protobuf:"varint,2,opt,name=page_size,json=pageSize,proto3" json:"page_size,omitempty"`
	Name          string                 `protobuf:"bytes,3,opt,name=name,proto3" json:"name,omitempty"`
	Status        int32                  `protobuf:"varint,4,opt,name=status,proto3" json:"status,omitempty"`
	Type          int32                  `protobuf:"varint,5,opt,name=type,proto3" json:"type,omitempty"`
	Scope         int32                  `protobuf:"varint,6,opt,name=scope,proto3" json:"scope,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ListApplicationsRequest) Reset() {
	*x = ListApplicationsRequest{}
	mi := &file_api_ai_application_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ListApplicationsRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ListApplicationsRequest) ProtoMessage() {}

func (x *ListApplicationsRequest) ProtoReflect() protoreflect.Message {
	mi := &file_api_ai_application_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ListApplicationsRequest.ProtoReflect.Descriptor instead.
func (*ListApplicationsRequest) Descriptor() ([]byte, []int) {
	return file_api_ai_application_proto_rawDescGZIP(), []int{1}
}

func (x *ListApplicationsRequest) GetPage() int32 {
	if x != nil {
		return x.Page
	}
	return 0
}

func (x *ListApplicationsRequest) GetPageSize() int32 {
	if x != nil {
		return x.PageSize
	}
	return 0
}

func (x *ListApplicationsRequest) GetName() string {
	if x != nil {
		return x.Name
	}
	return ""
}

func (x *ListApplicationsRequest) GetStatus() int32 {
	if x != nil {
		return x.Status
	}
	return 0
}

func (x *ListApplicationsRequest) GetType() int32 {
	if x != nil {
		return x.Type
	}
	return 0
}

func (x *ListApplicationsRequest) GetScope() int32 {
	if x != nil {
		return x.Scope
	}
	return 0
}

type ListApplicationsReply struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	List          []*ApplicationInfo     `protobuf:"bytes,1,rep,name=list,proto3" json:"list,omitempty"`
	Total         int64                  `protobuf:"varint,2,opt,name=total,proto3" json:"total,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ListApplicationsReply) Reset() {
	*x = ListApplicationsReply{}
	mi := &file_api_ai_application_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ListApplicationsReply) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ListApplicationsReply) ProtoMessage() {}

func (x *ListApplicationsReply) ProtoReflect() protoreflect.Message {
	mi := &file_api_ai_application_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ListApplicationsReply.ProtoReflect.Descriptor instead.
func (*ListApplicationsReply) Descriptor() ([]byte, []int) {
	return file_api_ai_application_proto_rawDescGZIP(), []int{2}
}

func (x *ListApplicationsReply) GetList() []*ApplicationInfo {
	if x != nil {
		return x.List
	}
	return nil
}

func (x *ListApplicationsReply) GetTotal() int64 {
	if x != nil {
		return x.Total
	}
	return 0
}

type CreateApplicationRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Name          string                 `protobuf:"bytes,2,opt,name=name,proto3" json:"name,omitempty"`                             // 名称
	Code          string                 `protobuf:"bytes,3,opt,name=code,proto3" json:"code,omitempty"`                             // 编码
	Description   string                 `protobuf:"bytes,4,opt,name=description,proto3" json:"description,omitempty"`               // 描述
	Version       string                 `protobuf:"bytes,5,opt,name=version,proto3" json:"version,omitempty"`                       // 版本号
	Mode          int32                  `protobuf:"varint,6,opt,name=mode,proto3" json:"mode,omitempty"`                            // 模式 1.单agent模式（只有一个agent，采用Ark原理，支持adk或者普通enio）2. 多agent模式（就是deepadk或者adk）
	Status        int32                  `protobuf:"varint,7,opt,name=status,proto3" json:"status,omitempty"`                        // 状态 2: 禁用, 1: 启用
	Type          int32                  `protobuf:"varint,8,opt,name=type,proto3" json:"type,omitempty"`                            // 程序类型 1. 预定义，2. 自定义
	Scope         int32                  `protobuf:"varint,9,opt,name=scope,proto3" json:"scope,omitempty"`                          // 作用粒度 1.所有人，2.指定角色，3.指定用户
	SelfAgent     *AppAgent              `protobuf:"bytes,10,opt,name=self_agent,json=selfAgent,proto3" json:"self_agent,omitempty"` // 自定义 Agent (通过agent列表获取，支持重新自定义)
	Schema        string                 `protobuf:"bytes,11,opt,name=schema,proto3" json:"schema,omitempty"`                        // 拖拽页面布局存档。
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *CreateApplicationRequest) Reset() {
	*x = CreateApplicationRequest{}
	mi := &file_api_ai_application_proto_msgTypes[3]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *CreateApplicationRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CreateApplicationRequest) ProtoMessage() {}

func (x *CreateApplicationRequest) ProtoReflect() protoreflect.Message {
	mi := &file_api_ai_application_proto_msgTypes[3]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CreateApplicationRequest.ProtoReflect.Descriptor instead.
func (*CreateApplicationRequest) Descriptor() ([]byte, []int) {
	return file_api_ai_application_proto_rawDescGZIP(), []int{3}
}

func (x *CreateApplicationRequest) GetName() string {
	if x != nil {
		return x.Name
	}
	return ""
}

func (x *CreateApplicationRequest) GetCode() string {
	if x != nil {
		return x.Code
	}
	return ""
}

func (x *CreateApplicationRequest) GetDescription() string {
	if x != nil {
		return x.Description
	}
	return ""
}

func (x *CreateApplicationRequest) GetVersion() string {
	if x != nil {
		return x.Version
	}
	return ""
}

func (x *CreateApplicationRequest) GetMode() int32 {
	if x != nil {
		return x.Mode
	}
	return 0
}

func (x *CreateApplicationRequest) GetStatus() int32 {
	if x != nil {
		return x.Status
	}
	return 0
}

func (x *CreateApplicationRequest) GetType() int32 {
	if x != nil {
		return x.Type
	}
	return 0
}

func (x *CreateApplicationRequest) GetScope() int32 {
	if x != nil {
		return x.Scope
	}
	return 0
}

func (x *CreateApplicationRequest) GetSelfAgent() *AppAgent {
	if x != nil {
		return x.SelfAgent
	}
	return nil
}

func (x *CreateApplicationRequest) GetSchema() string {
	if x != nil {
		return x.Schema
	}
	return ""
}

type UpdateApplicationRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Id            int64                  `protobuf:"varint,1,opt,name=id,proto3" json:"id,omitempty"`
	Name          string                 `protobuf:"bytes,2,opt,name=name,proto3" json:"name,omitempty"`                             // 名称
	Code          string                 `protobuf:"bytes,3,opt,name=code,proto3" json:"code,omitempty"`                             // 编码
	Description   string                 `protobuf:"bytes,4,opt,name=description,proto3" json:"description,omitempty"`               // 描述
	Version       string                 `protobuf:"bytes,5,opt,name=version,proto3" json:"version,omitempty"`                       // 版本号
	Mode          int32                  `protobuf:"varint,6,opt,name=mode,proto3" json:"mode,omitempty"`                            // 模式 1.单agent模式（只有一个agent，采用Ark原理，支持adk或者普通enio）2. 多agent模式（就是deepadk或者adk）
	Status        int32                  `protobuf:"varint,7,opt,name=status,proto3" json:"status,omitempty"`                        // 状态 2: 禁用, 1: 启用
	Type          int32                  `protobuf:"varint,8,opt,name=type,proto3" json:"type,omitempty"`                            // 程序类型 1. 预定义，2. 自定义
	Scope         int32                  `protobuf:"varint,9,opt,name=scope,proto3" json:"scope,omitempty"`                          // 作用粒度 1.所有人，2.指定角色，3.指定用户
	SelfAgent     *AppAgent              `protobuf:"bytes,10,opt,name=self_agent,json=selfAgent,proto3" json:"self_agent,omitempty"` // 自定义 Agent (通过agent列表获取，支持重新自定义)
	Schema        string                 `protobuf:"bytes,11,opt,name=schema,proto3" json:"schema,omitempty"`                        // 拖拽页面布局存档。
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *UpdateApplicationRequest) Reset() {
	*x = UpdateApplicationRequest{}
	mi := &file_api_ai_application_proto_msgTypes[4]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *UpdateApplicationRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*UpdateApplicationRequest) ProtoMessage() {}

func (x *UpdateApplicationRequest) ProtoReflect() protoreflect.Message {
	mi := &file_api_ai_application_proto_msgTypes[4]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use UpdateApplicationRequest.ProtoReflect.Descriptor instead.
func (*UpdateApplicationRequest) Descriptor() ([]byte, []int) {
	return file_api_ai_application_proto_rawDescGZIP(), []int{4}
}

func (x *UpdateApplicationRequest) GetId() int64 {
	if x != nil {
		return x.Id
	}
	return 0
}

func (x *UpdateApplicationRequest) GetName() string {
	if x != nil {
		return x.Name
	}
	return ""
}

func (x *UpdateApplicationRequest) GetCode() string {
	if x != nil {
		return x.Code
	}
	return ""
}

func (x *UpdateApplicationRequest) GetDescription() string {
	if x != nil {
		return x.Description
	}
	return ""
}

func (x *UpdateApplicationRequest) GetVersion() string {
	if x != nil {
		return x.Version
	}
	return ""
}

func (x *UpdateApplicationRequest) GetMode() int32 {
	if x != nil {
		return x.Mode
	}
	return 0
}

func (x *UpdateApplicationRequest) GetStatus() int32 {
	if x != nil {
		return x.Status
	}
	return 0
}

func (x *UpdateApplicationRequest) GetType() int32 {
	if x != nil {
		return x.Type
	}
	return 0
}

func (x *UpdateApplicationRequest) GetScope() int32 {
	if x != nil {
		return x.Scope
	}
	return 0
}

func (x *UpdateApplicationRequest) GetSelfAgent() *AppAgent {
	if x != nil {
		return x.SelfAgent
	}
	return nil
}

func (x *UpdateApplicationRequest) GetSchema() string {
	if x != nil {
		return x.Schema
	}
	return ""
}

type DeleteApplicationRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Id            int64                  `protobuf:"varint,1,opt,name=id,proto3" json:"id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *DeleteApplicationRequest) Reset() {
	*x = DeleteApplicationRequest{}
	mi := &file_api_ai_application_proto_msgTypes[5]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *DeleteApplicationRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*DeleteApplicationRequest) ProtoMessage() {}

func (x *DeleteApplicationRequest) ProtoReflect() protoreflect.Message {
	mi := &file_api_ai_application_proto_msgTypes[5]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use DeleteApplicationRequest.ProtoReflect.Descriptor instead.
func (*DeleteApplicationRequest) Descriptor() ([]byte, []int) {
	return file_api_ai_application_proto_rawDescGZIP(), []int{5}
}

func (x *DeleteApplicationRequest) GetId() int64 {
	if x != nil {
		return x.Id
	}
	return 0
}

type AppAgent struct {
	state              protoimpl.MessageState `protogen:"open.v1"`
	Id                 int64                  `protobuf:"varint,1,opt,name=id,proto3" json:"id,omitempty"`
	Name               string                 `protobuf:"bytes,2,opt,name=name,proto3" json:"name,omitempty"`
	Code               string                 `protobuf:"bytes,3,opt,name=code,proto3" json:"code,omitempty"`
	Description        string                 `protobuf:"bytes,4,opt,name=description,proto3" json:"description,omitempty"`
	AdapterType        int32                  `protobuf:"varint,5,opt,name=adapter_type,json=adapterType,proto3" json:"adapter_type,omitempty"`
	OriginalModelId    int64                  `protobuf:"varint,6,opt,name=original_model_id,json=originalModelId,proto3" json:"original_model_id,omitempty"` // 来源ai模型id: 原始model ID：追溯引用的模型配置。
	AiModel            *AgentModel            `protobuf:"bytes,7,opt,name=ai_model,json=aiModel,proto3" json:"ai_model,omitempty"`                            // 通过original_model_id获取的模型配置，支持修改。
	MaxIteration       int32                  `protobuf:"varint,8,opt,name=max_iteration,json=maxIteration,proto3" json:"max_iteration,omitempty"`
	SystemPrompt       string                 `protobuf:"bytes,9,opt,name=system_prompt,json=systemPrompt,proto3" json:"system_prompt,omitempty"`             // 引用模版提示
	UserInputPrompt    string                 `protobuf:"bytes,10,opt,name=user_input_prompt,json=userInputPrompt,proto3" json:"user_input_prompt,omitempty"` // 引用模版提示
	Status             int32                  `protobuf:"varint,11,opt,name=status,proto3" json:"status,omitempty"`                                           // 2: 禁用, 1: 启用
	Type               int32                  `protobuf:"varint,12,opt,name=type,proto3" json:"type,omitempty"`                                               // 1 根 Agent, 2 子 Agent
	WithWriteTodos     bool                   `protobuf:"varint,13,opt,name=with_write_todos,json=withWriteTodos,proto3" json:"with_write_todos,omitempty"`
	WithWebSearchAgent bool                   `protobuf:"varint,14,opt,name=with_web_search_agent,json=withWebSearchAgent,proto3" json:"with_web_search_agent,omitempty"`
	SystemType         int32                  `protobuf:"varint,15,opt,name=system_type,json=systemType,proto3" json:"system_type,omitempty"` // 1-系统内置(不可删除), 2-用户自定义
	CreatedAt          int64                  `protobuf:"varint,16,opt,name=created_at,json=createdAt,proto3" json:"created_at,omitempty"`
	SubAgents          []*AppAgent            `protobuf:"bytes,17,rep,name=sub_agents,json=subAgents,proto3" json:"sub_agents,omitempty"` // 子 Agent 列表
	unknownFields      protoimpl.UnknownFields
	sizeCache          protoimpl.SizeCache
}

func (x *AppAgent) Reset() {
	*x = AppAgent{}
	mi := &file_api_ai_application_proto_msgTypes[6]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *AppAgent) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*AppAgent) ProtoMessage() {}

func (x *AppAgent) ProtoReflect() protoreflect.Message {
	mi := &file_api_ai_application_proto_msgTypes[6]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use AppAgent.ProtoReflect.Descriptor instead.
func (*AppAgent) Descriptor() ([]byte, []int) {
	return file_api_ai_application_proto_rawDescGZIP(), []int{6}
}

func (x *AppAgent) GetId() int64 {
	if x != nil {
		return x.Id
	}
	return 0
}

func (x *AppAgent) GetName() string {
	if x != nil {
		return x.Name
	}
	return ""
}

func (x *AppAgent) GetCode() string {
	if x != nil {
		return x.Code
	}
	return ""
}

func (x *AppAgent) GetDescription() string {
	if x != nil {
		return x.Description
	}
	return ""
}

func (x *AppAgent) GetAdapterType() int32 {
	if x != nil {
		return x.AdapterType
	}
	return 0
}

func (x *AppAgent) GetOriginalModelId() int64 {
	if x != nil {
		return x.OriginalModelId
	}
	return 0
}

func (x *AppAgent) GetAiModel() *AgentModel {
	if x != nil {
		return x.AiModel
	}
	return nil
}

func (x *AppAgent) GetMaxIteration() int32 {
	if x != nil {
		return x.MaxIteration
	}
	return 0
}

func (x *AppAgent) GetSystemPrompt() string {
	if x != nil {
		return x.SystemPrompt
	}
	return ""
}

func (x *AppAgent) GetUserInputPrompt() string {
	if x != nil {
		return x.UserInputPrompt
	}
	return ""
}

func (x *AppAgent) GetStatus() int32 {
	if x != nil {
		return x.Status
	}
	return 0
}

func (x *AppAgent) GetType() int32 {
	if x != nil {
		return x.Type
	}
	return 0
}

func (x *AppAgent) GetWithWriteTodos() bool {
	if x != nil {
		return x.WithWriteTodos
	}
	return false
}

func (x *AppAgent) GetWithWebSearchAgent() bool {
	if x != nil {
		return x.WithWebSearchAgent
	}
	return false
}

func (x *AppAgent) GetSystemType() int32 {
	if x != nil {
		return x.SystemType
	}
	return 0
}

func (x *AppAgent) GetCreatedAt() int64 {
	if x != nil {
		return x.CreatedAt
	}
	return 0
}

func (x *AppAgent) GetSubAgents() []*AppAgent {
	if x != nil {
		return x.SubAgents
	}
	return nil
}

var File_api_ai_application_proto protoreflect.FileDescriptor

const file_api_ai_application_proto_rawDesc = "" +
	"\n" +
	"\x18api/ai/application.proto\x12\x02ai\x1a\x1cgoogle/api/annotations.proto\x1a\x1bgoogle/protobuf/empty.proto\x1a.protoc-gen-openapiv2/options/annotations.proto\x1a\x12api/ai/agent.proto\"\xbf\x02\n" +
	"\x0fApplicationInfo\x12\x0e\n" +
	"\x02id\x18\x01 \x01(\x03R\x02id\x12\x12\n" +
	"\x04name\x18\x02 \x01(\tR\x04name\x12\x12\n" +
	"\x04code\x18\x03 \x01(\tR\x04code\x12 \n" +
	"\vdescription\x18\x04 \x01(\tR\vdescription\x12\x18\n" +
	"\aversion\x18\x05 \x01(\tR\aversion\x12\x12\n" +
	"\x04mode\x18\x06 \x01(\x05R\x04mode\x12\x16\n" +
	"\x06status\x18\a \x01(\x05R\x06status\x12\x12\n" +
	"\x04type\x18\b \x01(\x05R\x04type\x12\x14\n" +
	"\x05scope\x18\t \x01(\x05R\x05scope\x12+\n" +
	"\n" +
	"self_agent\x18\n" +
	" \x01(\v2\f.ai.AppAgentR\tselfAgent\x12\x1d\n" +
	"\n" +
	"created_at\x18\v \x01(\x03R\tcreatedAt\x12\x16\n" +
	"\x06schema\x18\f \x01(\tR\x06schema\"\xa0\x01\n" +
	"\x17ListApplicationsRequest\x12\x12\n" +
	"\x04page\x18\x01 \x01(\x05R\x04page\x12\x1b\n" +
	"\tpage_size\x18\x02 \x01(\x05R\bpageSize\x12\x12\n" +
	"\x04name\x18\x03 \x01(\tR\x04name\x12\x16\n" +
	"\x06status\x18\x04 \x01(\x05R\x06status\x12\x12\n" +
	"\x04type\x18\x05 \x01(\x05R\x04type\x12\x14\n" +
	"\x05scope\x18\x06 \x01(\x05R\x05scope\"V\n" +
	"\x15ListApplicationsReply\x12'\n" +
	"\x04list\x18\x01 \x03(\v2\x13.ai.ApplicationInfoR\x04list\x12\x14\n" +
	"\x05total\x18\x02 \x01(\x03R\x05total\"\x99\x02\n" +
	"\x18CreateApplicationRequest\x12\x12\n" +
	"\x04name\x18\x02 \x01(\tR\x04name\x12\x12\n" +
	"\x04code\x18\x03 \x01(\tR\x04code\x12 \n" +
	"\vdescription\x18\x04 \x01(\tR\vdescription\x12\x18\n" +
	"\aversion\x18\x05 \x01(\tR\aversion\x12\x12\n" +
	"\x04mode\x18\x06 \x01(\x05R\x04mode\x12\x16\n" +
	"\x06status\x18\a \x01(\x05R\x06status\x12\x12\n" +
	"\x04type\x18\b \x01(\x05R\x04type\x12\x14\n" +
	"\x05scope\x18\t \x01(\x05R\x05scope\x12+\n" +
	"\n" +
	"self_agent\x18\n" +
	" \x01(\v2\f.ai.AppAgentR\tselfAgent\x12\x16\n" +
	"\x06schema\x18\v \x01(\tR\x06schema\"\xa9\x02\n" +
	"\x18UpdateApplicationRequest\x12\x0e\n" +
	"\x02id\x18\x01 \x01(\x03R\x02id\x12\x12\n" +
	"\x04name\x18\x02 \x01(\tR\x04name\x12\x12\n" +
	"\x04code\x18\x03 \x01(\tR\x04code\x12 \n" +
	"\vdescription\x18\x04 \x01(\tR\vdescription\x12\x18\n" +
	"\aversion\x18\x05 \x01(\tR\aversion\x12\x12\n" +
	"\x04mode\x18\x06 \x01(\x05R\x04mode\x12\x16\n" +
	"\x06status\x18\a \x01(\x05R\x06status\x12\x12\n" +
	"\x04type\x18\b \x01(\x05R\x04type\x12\x14\n" +
	"\x05scope\x18\t \x01(\x05R\x05scope\x12+\n" +
	"\n" +
	"self_agent\x18\n" +
	" \x01(\v2\f.ai.AppAgentR\tselfAgent\x12\x16\n" +
	"\x06schema\x18\v \x01(\tR\x06schema\"*\n" +
	"\x18DeleteApplicationRequest\x12\x0e\n" +
	"\x02id\x18\x01 \x01(\x03R\x02id\"\xca\x04\n" +
	"\bAppAgent\x12\x0e\n" +
	"\x02id\x18\x01 \x01(\x03R\x02id\x12\x12\n" +
	"\x04name\x18\x02 \x01(\tR\x04name\x12\x12\n" +
	"\x04code\x18\x03 \x01(\tR\x04code\x12 \n" +
	"\vdescription\x18\x04 \x01(\tR\vdescription\x12!\n" +
	"\fadapter_type\x18\x05 \x01(\x05R\vadapterType\x12*\n" +
	"\x11original_model_id\x18\x06 \x01(\x03R\x0foriginalModelId\x12)\n" +
	"\bai_model\x18\a \x01(\v2\x0e.ai.AgentModelR\aaiModel\x12#\n" +
	"\rmax_iteration\x18\b \x01(\x05R\fmaxIteration\x12#\n" +
	"\rsystem_prompt\x18\t \x01(\tR\fsystemPrompt\x12*\n" +
	"\x11user_input_prompt\x18\n" +
	" \x01(\tR\x0fuserInputPrompt\x12\x16\n" +
	"\x06status\x18\v \x01(\x05R\x06status\x12\x12\n" +
	"\x04type\x18\f \x01(\x05R\x04type\x12(\n" +
	"\x10with_write_todos\x18\r \x01(\bR\x0ewithWriteTodos\x121\n" +
	"\x15with_web_search_agent\x18\x0e \x01(\bR\x12withWebSearchAgent\x12\x1f\n" +
	"\vsystem_type\x18\x0f \x01(\x05R\n" +
	"systemType\x12\x1d\n" +
	"\n" +
	"created_at\x18\x10 \x01(\x03R\tcreatedAt\x12+\n" +
	"\n" +
	"sub_agents\x18\x11 \x03(\v2\f.ai.AppAgentR\tsubAgentsB1\n" +
	"\x11dev.kratos.api.aiB\aAiProtoP\x01Z\x11backend/api/ai;aib\x06proto3"

var (
	file_api_ai_application_proto_rawDescOnce sync.Once
	file_api_ai_application_proto_rawDescData []byte
)

func file_api_ai_application_proto_rawDescGZIP() []byte {
	file_api_ai_application_proto_rawDescOnce.Do(func() {
		file_api_ai_application_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_api_ai_application_proto_rawDesc), len(file_api_ai_application_proto_rawDesc)))
	})
	return file_api_ai_application_proto_rawDescData
}

var file_api_ai_application_proto_msgTypes = make([]protoimpl.MessageInfo, 7)
var file_api_ai_application_proto_goTypes = []any{
	(*ApplicationInfo)(nil),          // 0: ai.ApplicationInfo
	(*ListApplicationsRequest)(nil),  // 1: ai.ListApplicationsRequest
	(*ListApplicationsReply)(nil),    // 2: ai.ListApplicationsReply
	(*CreateApplicationRequest)(nil), // 3: ai.CreateApplicationRequest
	(*UpdateApplicationRequest)(nil), // 4: ai.UpdateApplicationRequest
	(*DeleteApplicationRequest)(nil), // 5: ai.DeleteApplicationRequest
	(*AppAgent)(nil),                 // 6: ai.AppAgent
	(*AgentModel)(nil),               // 7: ai.AgentModel
}
var file_api_ai_application_proto_depIdxs = []int32{
	6, // 0: ai.ApplicationInfo.self_agent:type_name -> ai.AppAgent
	0, // 1: ai.ListApplicationsReply.list:type_name -> ai.ApplicationInfo
	6, // 2: ai.CreateApplicationRequest.self_agent:type_name -> ai.AppAgent
	6, // 3: ai.UpdateApplicationRequest.self_agent:type_name -> ai.AppAgent
	7, // 4: ai.AppAgent.ai_model:type_name -> ai.AgentModel
	6, // 5: ai.AppAgent.sub_agents:type_name -> ai.AppAgent
	6, // [6:6] is the sub-list for method output_type
	6, // [6:6] is the sub-list for method input_type
	6, // [6:6] is the sub-list for extension type_name
	6, // [6:6] is the sub-list for extension extendee
	0, // [0:6] is the sub-list for field type_name
}

func init() { file_api_ai_application_proto_init() }
func file_api_ai_application_proto_init() {
	if File_api_ai_application_proto != nil {
		return
	}
	file_api_ai_agent_proto_init()
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_api_ai_application_proto_rawDesc), len(file_api_ai_application_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   7,
			NumExtensions: 0,
			NumServices:   0,
		},
		GoTypes:           file_api_ai_application_proto_goTypes,
		DependencyIndexes: file_api_ai_application_proto_depIdxs,
		MessageInfos:      file_api_ai_application_proto_msgTypes,
	}.Build()
	File_api_ai_application_proto = out.File
	file_api_ai_application_proto_goTypes = nil
	file_api_ai_application_proto_depIdxs = nil
}
