// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.10
// 	protoc        v5.29.3
// source: api/ai/prompt.proto

package ai

import (
	_ "github.com/grpc-ecosystem/grpc-gateway/v2/protoc-gen-openapiv2/options"
	_ "google.golang.org/genproto/googleapis/api/annotations"
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	_ "google.golang.org/protobuf/types/known/emptypb"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

// ========== Prompt Messages ==========
type PromptInfo struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Id            int64                  `protobuf:"varint,1,opt,name=id,proto3" json:"id,omitempty"`
	Type          int32                  `protobuf:"varint,2,opt,name=type,proto3" json:"type,omitempty"`
	Name          string                 `protobuf:"bytes,3,opt,name=name,proto3" json:"name,omitempty"`
	Description   string                 `protobuf:"bytes,4,opt,name=description,proto3" json:"description,omitempty"`
	Text          string                 `protobuf:"bytes,5,opt,name=text,proto3" json:"text,omitempty"`
	CreatedAt     int64                  `protobuf:"varint,6,opt,name=created_at,json=createdAt,proto3" json:"created_at,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *PromptInfo) Reset() {
	*x = PromptInfo{}
	mi := &file_api_ai_prompt_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *PromptInfo) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*PromptInfo) ProtoMessage() {}

func (x *PromptInfo) ProtoReflect() protoreflect.Message {
	mi := &file_api_ai_prompt_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use PromptInfo.ProtoReflect.Descriptor instead.
func (*PromptInfo) Descriptor() ([]byte, []int) {
	return file_api_ai_prompt_proto_rawDescGZIP(), []int{0}
}

func (x *PromptInfo) GetId() int64 {
	if x != nil {
		return x.Id
	}
	return 0
}

func (x *PromptInfo) GetType() int32 {
	if x != nil {
		return x.Type
	}
	return 0
}

func (x *PromptInfo) GetName() string {
	if x != nil {
		return x.Name
	}
	return ""
}

func (x *PromptInfo) GetDescription() string {
	if x != nil {
		return x.Description
	}
	return ""
}

func (x *PromptInfo) GetText() string {
	if x != nil {
		return x.Text
	}
	return ""
}

func (x *PromptInfo) GetCreatedAt() int64 {
	if x != nil {
		return x.CreatedAt
	}
	return 0
}

type ListPromptsRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Page          int32                  `protobuf:"varint,1,opt,name=page,proto3" json:"page,omitempty"`
	PageSize      int32                  `protobuf:"varint,2,opt,name=page_size,json=pageSize,proto3" json:"page_size,omitempty"`
	Name          string                 `protobuf:"bytes,3,opt,name=name,proto3" json:"name,omitempty"`
	Type          int32                  `protobuf:"varint,4,opt,name=type,proto3" json:"type,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ListPromptsRequest) Reset() {
	*x = ListPromptsRequest{}
	mi := &file_api_ai_prompt_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ListPromptsRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ListPromptsRequest) ProtoMessage() {}

func (x *ListPromptsRequest) ProtoReflect() protoreflect.Message {
	mi := &file_api_ai_prompt_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ListPromptsRequest.ProtoReflect.Descriptor instead.
func (*ListPromptsRequest) Descriptor() ([]byte, []int) {
	return file_api_ai_prompt_proto_rawDescGZIP(), []int{1}
}

func (x *ListPromptsRequest) GetPage() int32 {
	if x != nil {
		return x.Page
	}
	return 0
}

func (x *ListPromptsRequest) GetPageSize() int32 {
	if x != nil {
		return x.PageSize
	}
	return 0
}

func (x *ListPromptsRequest) GetName() string {
	if x != nil {
		return x.Name
	}
	return ""
}

func (x *ListPromptsRequest) GetType() int32 {
	if x != nil {
		return x.Type
	}
	return 0
}

type ListPromptsReply struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	List          []*PromptInfo          `protobuf:"bytes,1,rep,name=list,proto3" json:"list,omitempty"`
	Total         int64                  `protobuf:"varint,2,opt,name=total,proto3" json:"total,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ListPromptsReply) Reset() {
	*x = ListPromptsReply{}
	mi := &file_api_ai_prompt_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ListPromptsReply) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ListPromptsReply) ProtoMessage() {}

func (x *ListPromptsReply) ProtoReflect() protoreflect.Message {
	mi := &file_api_ai_prompt_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ListPromptsReply.ProtoReflect.Descriptor instead.
func (*ListPromptsReply) Descriptor() ([]byte, []int) {
	return file_api_ai_prompt_proto_rawDescGZIP(), []int{2}
}

func (x *ListPromptsReply) GetList() []*PromptInfo {
	if x != nil {
		return x.List
	}
	return nil
}

func (x *ListPromptsReply) GetTotal() int64 {
	if x != nil {
		return x.Total
	}
	return 0
}

type CreatePromptRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Type          int32                  `protobuf:"varint,1,opt,name=type,proto3" json:"type,omitempty"`
	Name          string                 `protobuf:"bytes,2,opt,name=name,proto3" json:"name,omitempty"`
	Description   string                 `protobuf:"bytes,3,opt,name=description,proto3" json:"description,omitempty"`
	Text          string                 `protobuf:"bytes,4,opt,name=text,proto3" json:"text,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *CreatePromptRequest) Reset() {
	*x = CreatePromptRequest{}
	mi := &file_api_ai_prompt_proto_msgTypes[3]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *CreatePromptRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CreatePromptRequest) ProtoMessage() {}

func (x *CreatePromptRequest) ProtoReflect() protoreflect.Message {
	mi := &file_api_ai_prompt_proto_msgTypes[3]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CreatePromptRequest.ProtoReflect.Descriptor instead.
func (*CreatePromptRequest) Descriptor() ([]byte, []int) {
	return file_api_ai_prompt_proto_rawDescGZIP(), []int{3}
}

func (x *CreatePromptRequest) GetType() int32 {
	if x != nil {
		return x.Type
	}
	return 0
}

func (x *CreatePromptRequest) GetName() string {
	if x != nil {
		return x.Name
	}
	return ""
}

func (x *CreatePromptRequest) GetDescription() string {
	if x != nil {
		return x.Description
	}
	return ""
}

func (x *CreatePromptRequest) GetText() string {
	if x != nil {
		return x.Text
	}
	return ""
}

type UpdatePromptRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Id            int64                  `protobuf:"varint,1,opt,name=id,proto3" json:"id,omitempty"`
	Type          int32                  `protobuf:"varint,2,opt,name=type,proto3" json:"type,omitempty"`
	Name          string                 `protobuf:"bytes,3,opt,name=name,proto3" json:"name,omitempty"`
	Description   string                 `protobuf:"bytes,4,opt,name=description,proto3" json:"description,omitempty"`
	Text          string                 `protobuf:"bytes,5,opt,name=text,proto3" json:"text,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *UpdatePromptRequest) Reset() {
	*x = UpdatePromptRequest{}
	mi := &file_api_ai_prompt_proto_msgTypes[4]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *UpdatePromptRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*UpdatePromptRequest) ProtoMessage() {}

func (x *UpdatePromptRequest) ProtoReflect() protoreflect.Message {
	mi := &file_api_ai_prompt_proto_msgTypes[4]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use UpdatePromptRequest.ProtoReflect.Descriptor instead.
func (*UpdatePromptRequest) Descriptor() ([]byte, []int) {
	return file_api_ai_prompt_proto_rawDescGZIP(), []int{4}
}

func (x *UpdatePromptRequest) GetId() int64 {
	if x != nil {
		return x.Id
	}
	return 0
}

func (x *UpdatePromptRequest) GetType() int32 {
	if x != nil {
		return x.Type
	}
	return 0
}

func (x *UpdatePromptRequest) GetName() string {
	if x != nil {
		return x.Name
	}
	return ""
}

func (x *UpdatePromptRequest) GetDescription() string {
	if x != nil {
		return x.Description
	}
	return ""
}

func (x *UpdatePromptRequest) GetText() string {
	if x != nil {
		return x.Text
	}
	return ""
}

var File_api_ai_prompt_proto protoreflect.FileDescriptor

const file_api_ai_prompt_proto_rawDesc = "" +
	"\n" +
	"\x13api/ai/prompt.proto\x12\x02ai\x1a\x1cgoogle/api/annotations.proto\x1a\x1bgoogle/protobuf/empty.proto\x1a.protoc-gen-openapiv2/options/annotations.proto\"\x99\x01\n" +
	"\n" +
	"PromptInfo\x12\x0e\n" +
	"\x02id\x18\x01 \x01(\x03R\x02id\x12\x12\n" +
	"\x04type\x18\x02 \x01(\x05R\x04type\x12\x12\n" +
	"\x04name\x18\x03 \x01(\tR\x04name\x12 \n" +
	"\vdescription\x18\x04 \x01(\tR\vdescription\x12\x12\n" +
	"\x04text\x18\x05 \x01(\tR\x04text\x12\x1d\n" +
	"\n" +
	"created_at\x18\x06 \x01(\x03R\tcreatedAt\"m\n" +
	"\x12ListPromptsRequest\x12\x12\n" +
	"\x04page\x18\x01 \x01(\x05R\x04page\x12\x1b\n" +
	"\tpage_size\x18\x02 \x01(\x05R\bpageSize\x12\x12\n" +
	"\x04name\x18\x03 \x01(\tR\x04name\x12\x12\n" +
	"\x04type\x18\x04 \x01(\x05R\x04type\"L\n" +
	"\x10ListPromptsReply\x12\"\n" +
	"\x04list\x18\x01 \x03(\v2\x0e.ai.PromptInfoR\x04list\x12\x14\n" +
	"\x05total\x18\x02 \x01(\x03R\x05total\"s\n" +
	"\x13CreatePromptRequest\x12\x12\n" +
	"\x04type\x18\x01 \x01(\x05R\x04type\x12\x12\n" +
	"\x04name\x18\x02 \x01(\tR\x04name\x12 \n" +
	"\vdescription\x18\x03 \x01(\tR\vdescription\x12\x12\n" +
	"\x04text\x18\x04 \x01(\tR\x04text\"\x83\x01\n" +
	"\x13UpdatePromptRequest\x12\x0e\n" +
	"\x02id\x18\x01 \x01(\x03R\x02id\x12\x12\n" +
	"\x04type\x18\x02 \x01(\x05R\x04type\x12\x12\n" +
	"\x04name\x18\x03 \x01(\tR\x04name\x12 \n" +
	"\vdescription\x18\x04 \x01(\tR\vdescription\x12\x12\n" +
	"\x04text\x18\x05 \x01(\tR\x04textB1\n" +
	"\x11dev.kratos.api.aiB\aAiProtoP\x01Z\x11backend/api/ai;aib\x06proto3"

var (
	file_api_ai_prompt_proto_rawDescOnce sync.Once
	file_api_ai_prompt_proto_rawDescData []byte
)

func file_api_ai_prompt_proto_rawDescGZIP() []byte {
	file_api_ai_prompt_proto_rawDescOnce.Do(func() {
		file_api_ai_prompt_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_api_ai_prompt_proto_rawDesc), len(file_api_ai_prompt_proto_rawDesc)))
	})
	return file_api_ai_prompt_proto_rawDescData
}

var file_api_ai_prompt_proto_msgTypes = make([]protoimpl.MessageInfo, 5)
var file_api_ai_prompt_proto_goTypes = []any{
	(*PromptInfo)(nil),          // 0: ai.PromptInfo
	(*ListPromptsRequest)(nil),  // 1: ai.ListPromptsRequest
	(*ListPromptsReply)(nil),    // 2: ai.ListPromptsReply
	(*CreatePromptRequest)(nil), // 3: ai.CreatePromptRequest
	(*UpdatePromptRequest)(nil), // 4: ai.UpdatePromptRequest
}
var file_api_ai_prompt_proto_depIdxs = []int32{
	0, // 0: ai.ListPromptsReply.list:type_name -> ai.PromptInfo
	1, // [1:1] is the sub-list for method output_type
	1, // [1:1] is the sub-list for method input_type
	1, // [1:1] is the sub-list for extension type_name
	1, // [1:1] is the sub-list for extension extendee
	0, // [0:1] is the sub-list for field type_name
}

func init() { file_api_ai_prompt_proto_init() }
func file_api_ai_prompt_proto_init() {
	if File_api_ai_prompt_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_api_ai_prompt_proto_rawDesc), len(file_api_ai_prompt_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   5,
			NumExtensions: 0,
			NumServices:   0,
		},
		GoTypes:           file_api_ai_prompt_proto_goTypes,
		DependencyIndexes: file_api_ai_prompt_proto_depIdxs,
		MessageInfos:      file_api_ai_prompt_proto_msgTypes,
	}.Build()
	File_api_ai_prompt_proto = out.File
	file_api_ai_prompt_proto_goTypes = nil
	file_api_ai_prompt_proto_depIdxs = nil
}
