// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.10
// 	protoc        v5.29.3
// source: api/ai/tool.proto

package ai

import (
	_ "github.com/grpc-ecosystem/grpc-gateway/v2/protoc-gen-openapiv2/options"
	_ "google.golang.org/genproto/googleapis/api/annotations"
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	_ "google.golang.org/protobuf/types/known/emptypb"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

// ========== Tool Messages ==========
type ToolParam struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	ParamName     string                 `protobuf:"bytes,1,opt,name=param_name,json=paramName,proto3" json:"param_name,omitempty"`
	ParamType     string                 `protobuf:"bytes,2,opt,name=param_type,json=paramType,proto3" json:"param_type,omitempty"`
	DefaultValue  string                 `protobuf:"bytes,3,opt,name=default_value,json=defaultValue,proto3" json:"default_value,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ToolParam) Reset() {
	*x = ToolParam{}
	mi := &file_api_ai_tool_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ToolParam) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ToolParam) ProtoMessage() {}

func (x *ToolParam) ProtoReflect() protoreflect.Message {
	mi := &file_api_ai_tool_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ToolParam.ProtoReflect.Descriptor instead.
func (*ToolParam) Descriptor() ([]byte, []int) {
	return file_api_ai_tool_proto_rawDescGZIP(), []int{0}
}

func (x *ToolParam) GetParamName() string {
	if x != nil {
		return x.ParamName
	}
	return ""
}

func (x *ToolParam) GetParamType() string {
	if x != nil {
		return x.ParamType
	}
	return ""
}

func (x *ToolParam) GetDefaultValue() string {
	if x != nil {
		return x.DefaultValue
	}
	return ""
}

type ToolInfo struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Id            int64                  `protobuf:"varint,1,opt,name=id,proto3" json:"id,omitempty"`
	Name          string                 `protobuf:"bytes,2,opt,name=name,proto3" json:"name,omitempty"`
	Code          string                 `protobuf:"bytes,3,opt,name=code,proto3" json:"code,omitempty"`
	Description   string                 `protobuf:"bytes,4,opt,name=description,proto3" json:"description,omitempty"`
	SysType       int32                  `protobuf:"varint,5,opt,name=sys_type,json=sysType,proto3" json:"sys_type,omitempty"`
	Type          int32                  `protobuf:"varint,6,opt,name=type,proto3" json:"type,omitempty"`
	Status        int32                  `protobuf:"varint,7,opt,name=status,proto3" json:"status,omitempty"`
	Params        []*ToolParam           `protobuf:"bytes,8,rep,name=params,proto3" json:"params,omitempty"`
	McpUrl        string                 `protobuf:"bytes,9,opt,name=mcp_url,json=mcpUrl,proto3" json:"mcp_url,omitempty"`
	McpToken      string                 `protobuf:"bytes,10,opt,name=mcp_token,json=mcpToken,proto3" json:"mcp_token,omitempty"`
	CreatedAt     int64                  `protobuf:"varint,11,opt,name=created_at,json=createdAt,proto3" json:"created_at,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ToolInfo) Reset() {
	*x = ToolInfo{}
	mi := &file_api_ai_tool_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ToolInfo) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ToolInfo) ProtoMessage() {}

func (x *ToolInfo) ProtoReflect() protoreflect.Message {
	mi := &file_api_ai_tool_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ToolInfo.ProtoReflect.Descriptor instead.
func (*ToolInfo) Descriptor() ([]byte, []int) {
	return file_api_ai_tool_proto_rawDescGZIP(), []int{1}
}

func (x *ToolInfo) GetId() int64 {
	if x != nil {
		return x.Id
	}
	return 0
}

func (x *ToolInfo) GetName() string {
	if x != nil {
		return x.Name
	}
	return ""
}

func (x *ToolInfo) GetCode() string {
	if x != nil {
		return x.Code
	}
	return ""
}

func (x *ToolInfo) GetDescription() string {
	if x != nil {
		return x.Description
	}
	return ""
}

func (x *ToolInfo) GetSysType() int32 {
	if x != nil {
		return x.SysType
	}
	return 0
}

func (x *ToolInfo) GetType() int32 {
	if x != nil {
		return x.Type
	}
	return 0
}

func (x *ToolInfo) GetStatus() int32 {
	if x != nil {
		return x.Status
	}
	return 0
}

func (x *ToolInfo) GetParams() []*ToolParam {
	if x != nil {
		return x.Params
	}
	return nil
}

func (x *ToolInfo) GetMcpUrl() string {
	if x != nil {
		return x.McpUrl
	}
	return ""
}

func (x *ToolInfo) GetMcpToken() string {
	if x != nil {
		return x.McpToken
	}
	return ""
}

func (x *ToolInfo) GetCreatedAt() int64 {
	if x != nil {
		return x.CreatedAt
	}
	return 0
}

type ListToolsRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Page          int32                  `protobuf:"varint,1,opt,name=page,proto3" json:"page,omitempty"`
	PageSize      int32                  `protobuf:"varint,2,opt,name=page_size,json=pageSize,proto3" json:"page_size,omitempty"`
	Name          string                 `protobuf:"bytes,3,opt,name=name,proto3" json:"name,omitempty"`
	Type          int32                  `protobuf:"varint,4,opt,name=type,proto3" json:"type,omitempty"`
	Status        int32                  `protobuf:"varint,5,opt,name=status,proto3" json:"status,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ListToolsRequest) Reset() {
	*x = ListToolsRequest{}
	mi := &file_api_ai_tool_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ListToolsRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ListToolsRequest) ProtoMessage() {}

func (x *ListToolsRequest) ProtoReflect() protoreflect.Message {
	mi := &file_api_ai_tool_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ListToolsRequest.ProtoReflect.Descriptor instead.
func (*ListToolsRequest) Descriptor() ([]byte, []int) {
	return file_api_ai_tool_proto_rawDescGZIP(), []int{2}
}

func (x *ListToolsRequest) GetPage() int32 {
	if x != nil {
		return x.Page
	}
	return 0
}

func (x *ListToolsRequest) GetPageSize() int32 {
	if x != nil {
		return x.PageSize
	}
	return 0
}

func (x *ListToolsRequest) GetName() string {
	if x != nil {
		return x.Name
	}
	return ""
}

func (x *ListToolsRequest) GetType() int32 {
	if x != nil {
		return x.Type
	}
	return 0
}

func (x *ListToolsRequest) GetStatus() int32 {
	if x != nil {
		return x.Status
	}
	return 0
}

type ListToolsReply struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	List          []*ToolInfo            `protobuf:"bytes,1,rep,name=list,proto3" json:"list,omitempty"`
	Total         int64                  `protobuf:"varint,2,opt,name=total,proto3" json:"total,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ListToolsReply) Reset() {
	*x = ListToolsReply{}
	mi := &file_api_ai_tool_proto_msgTypes[3]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ListToolsReply) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ListToolsReply) ProtoMessage() {}

func (x *ListToolsReply) ProtoReflect() protoreflect.Message {
	mi := &file_api_ai_tool_proto_msgTypes[3]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ListToolsReply.ProtoReflect.Descriptor instead.
func (*ListToolsReply) Descriptor() ([]byte, []int) {
	return file_api_ai_tool_proto_rawDescGZIP(), []int{3}
}

func (x *ListToolsReply) GetList() []*ToolInfo {
	if x != nil {
		return x.List
	}
	return nil
}

func (x *ListToolsReply) GetTotal() int64 {
	if x != nil {
		return x.Total
	}
	return 0
}

type CreateToolRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Name          string                 `protobuf:"bytes,1,opt,name=name,proto3" json:"name,omitempty"`
	Code          string                 `protobuf:"bytes,2,opt,name=code,proto3" json:"code,omitempty"`
	Description   string                 `protobuf:"bytes,3,opt,name=description,proto3" json:"description,omitempty"`
	Type          int32                  `protobuf:"varint,4,opt,name=type,proto3" json:"type,omitempty"`
	Status        int32                  `protobuf:"varint,5,opt,name=status,proto3" json:"status,omitempty"`
	Params        []*ToolParam           `protobuf:"bytes,6,rep,name=params,proto3" json:"params,omitempty"`
	McpUrl        string                 `protobuf:"bytes,7,opt,name=mcp_url,json=mcpUrl,proto3" json:"mcp_url,omitempty"`
	McpToken      string                 `protobuf:"bytes,8,opt,name=mcp_token,json=mcpToken,proto3" json:"mcp_token,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *CreateToolRequest) Reset() {
	*x = CreateToolRequest{}
	mi := &file_api_ai_tool_proto_msgTypes[4]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *CreateToolRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CreateToolRequest) ProtoMessage() {}

func (x *CreateToolRequest) ProtoReflect() protoreflect.Message {
	mi := &file_api_ai_tool_proto_msgTypes[4]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CreateToolRequest.ProtoReflect.Descriptor instead.
func (*CreateToolRequest) Descriptor() ([]byte, []int) {
	return file_api_ai_tool_proto_rawDescGZIP(), []int{4}
}

func (x *CreateToolRequest) GetName() string {
	if x != nil {
		return x.Name
	}
	return ""
}

func (x *CreateToolRequest) GetCode() string {
	if x != nil {
		return x.Code
	}
	return ""
}

func (x *CreateToolRequest) GetDescription() string {
	if x != nil {
		return x.Description
	}
	return ""
}

func (x *CreateToolRequest) GetType() int32 {
	if x != nil {
		return x.Type
	}
	return 0
}

func (x *CreateToolRequest) GetStatus() int32 {
	if x != nil {
		return x.Status
	}
	return 0
}

func (x *CreateToolRequest) GetParams() []*ToolParam {
	if x != nil {
		return x.Params
	}
	return nil
}

func (x *CreateToolRequest) GetMcpUrl() string {
	if x != nil {
		return x.McpUrl
	}
	return ""
}

func (x *CreateToolRequest) GetMcpToken() string {
	if x != nil {
		return x.McpToken
	}
	return ""
}

type UpdateToolRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Id            int64                  `protobuf:"varint,1,opt,name=id,proto3" json:"id,omitempty"`
	Name          string                 `protobuf:"bytes,2,opt,name=name,proto3" json:"name,omitempty"`
	Code          string                 `protobuf:"bytes,3,opt,name=code,proto3" json:"code,omitempty"`
	Description   string                 `protobuf:"bytes,4,opt,name=description,proto3" json:"description,omitempty"`
	Type          int32                  `protobuf:"varint,5,opt,name=type,proto3" json:"type,omitempty"`
	Status        int32                  `protobuf:"varint,6,opt,name=status,proto3" json:"status,omitempty"`
	Params        []*ToolParam           `protobuf:"bytes,7,rep,name=params,proto3" json:"params,omitempty"`
	McpUrl        string                 `protobuf:"bytes,8,opt,name=mcp_url,json=mcpUrl,proto3" json:"mcp_url,omitempty"`
	McpToken      string                 `protobuf:"bytes,9,opt,name=mcp_token,json=mcpToken,proto3" json:"mcp_token,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *UpdateToolRequest) Reset() {
	*x = UpdateToolRequest{}
	mi := &file_api_ai_tool_proto_msgTypes[5]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *UpdateToolRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*UpdateToolRequest) ProtoMessage() {}

func (x *UpdateToolRequest) ProtoReflect() protoreflect.Message {
	mi := &file_api_ai_tool_proto_msgTypes[5]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use UpdateToolRequest.ProtoReflect.Descriptor instead.
func (*UpdateToolRequest) Descriptor() ([]byte, []int) {
	return file_api_ai_tool_proto_rawDescGZIP(), []int{5}
}

func (x *UpdateToolRequest) GetId() int64 {
	if x != nil {
		return x.Id
	}
	return 0
}

func (x *UpdateToolRequest) GetName() string {
	if x != nil {
		return x.Name
	}
	return ""
}

func (x *UpdateToolRequest) GetCode() string {
	if x != nil {
		return x.Code
	}
	return ""
}

func (x *UpdateToolRequest) GetDescription() string {
	if x != nil {
		return x.Description
	}
	return ""
}

func (x *UpdateToolRequest) GetType() int32 {
	if x != nil {
		return x.Type
	}
	return 0
}

func (x *UpdateToolRequest) GetStatus() int32 {
	if x != nil {
		return x.Status
	}
	return 0
}

func (x *UpdateToolRequest) GetParams() []*ToolParam {
	if x != nil {
		return x.Params
	}
	return nil
}

func (x *UpdateToolRequest) GetMcpUrl() string {
	if x != nil {
		return x.McpUrl
	}
	return ""
}

func (x *UpdateToolRequest) GetMcpToken() string {
	if x != nil {
		return x.McpToken
	}
	return ""
}

type BatchBindToolsRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	AgentId       int64                  `protobuf:"varint,1,opt,name=agent_id,json=agentId,proto3" json:"agent_id,omitempty"`
	ToolCodes     []string               `protobuf:"bytes,2,rep,name=tool_codes,json=toolCodes,proto3" json:"tool_codes,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *BatchBindToolsRequest) Reset() {
	*x = BatchBindToolsRequest{}
	mi := &file_api_ai_tool_proto_msgTypes[6]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *BatchBindToolsRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*BatchBindToolsRequest) ProtoMessage() {}

func (x *BatchBindToolsRequest) ProtoReflect() protoreflect.Message {
	mi := &file_api_ai_tool_proto_msgTypes[6]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use BatchBindToolsRequest.ProtoReflect.Descriptor instead.
func (*BatchBindToolsRequest) Descriptor() ([]byte, []int) {
	return file_api_ai_tool_proto_rawDescGZIP(), []int{6}
}

func (x *BatchBindToolsRequest) GetAgentId() int64 {
	if x != nil {
		return x.AgentId
	}
	return 0
}

func (x *BatchBindToolsRequest) GetToolCodes() []string {
	if x != nil {
		return x.ToolCodes
	}
	return nil
}

var File_api_ai_tool_proto protoreflect.FileDescriptor

const file_api_ai_tool_proto_rawDesc = "" +
	"\n" +
	"\x11api/ai/tool.proto\x12\x02ai\x1a\x1cgoogle/api/annotations.proto\x1a\x1bgoogle/protobuf/empty.proto\x1a.protoc-gen-openapiv2/options/annotations.proto\"n\n" +
	"\tToolParam\x12\x1d\n" +
	"\n" +
	"param_name\x18\x01 \x01(\tR\tparamName\x12\x1d\n" +
	"\n" +
	"param_type\x18\x02 \x01(\tR\tparamType\x12#\n" +
	"\rdefault_value\x18\x03 \x01(\tR\fdefaultValue\"\xa7\x02\n" +
	"\bToolInfo\x12\x0e\n" +
	"\x02id\x18\x01 \x01(\x03R\x02id\x12\x12\n" +
	"\x04name\x18\x02 \x01(\tR\x04name\x12\x12\n" +
	"\x04code\x18\x03 \x01(\tR\x04code\x12 \n" +
	"\vdescription\x18\x04 \x01(\tR\vdescription\x12\x19\n" +
	"\bsys_type\x18\x05 \x01(\x05R\asysType\x12\x12\n" +
	"\x04type\x18\x06 \x01(\x05R\x04type\x12\x16\n" +
	"\x06status\x18\a \x01(\x05R\x06status\x12%\n" +
	"\x06params\x18\b \x03(\v2\r.ai.ToolParamR\x06params\x12\x17\n" +
	"\amcp_url\x18\t \x01(\tR\x06mcpUrl\x12\x1b\n" +
	"\tmcp_token\x18\n" +
	" \x01(\tR\bmcpToken\x12\x1d\n" +
	"\n" +
	"created_at\x18\v \x01(\x03R\tcreatedAt\"\x83\x01\n" +
	"\x10ListToolsRequest\x12\x12\n" +
	"\x04page\x18\x01 \x01(\x05R\x04page\x12\x1b\n" +
	"\tpage_size\x18\x02 \x01(\x05R\bpageSize\x12\x12\n" +
	"\x04name\x18\x03 \x01(\tR\x04name\x12\x12\n" +
	"\x04type\x18\x04 \x01(\x05R\x04type\x12\x16\n" +
	"\x06status\x18\x05 \x01(\x05R\x06status\"H\n" +
	"\x0eListToolsReply\x12 \n" +
	"\x04list\x18\x01 \x03(\v2\f.ai.ToolInfoR\x04list\x12\x14\n" +
	"\x05total\x18\x02 \x01(\x03R\x05total\"\xe6\x01\n" +
	"\x11CreateToolRequest\x12\x12\n" +
	"\x04name\x18\x01 \x01(\tR\x04name\x12\x12\n" +
	"\x04code\x18\x02 \x01(\tR\x04code\x12 \n" +
	"\vdescription\x18\x03 \x01(\tR\vdescription\x12\x12\n" +
	"\x04type\x18\x04 \x01(\x05R\x04type\x12\x16\n" +
	"\x06status\x18\x05 \x01(\x05R\x06status\x12%\n" +
	"\x06params\x18\x06 \x03(\v2\r.ai.ToolParamR\x06params\x12\x17\n" +
	"\amcp_url\x18\a \x01(\tR\x06mcpUrl\x12\x1b\n" +
	"\tmcp_token\x18\b \x01(\tR\bmcpToken\"\xf6\x01\n" +
	"\x11UpdateToolRequest\x12\x0e\n" +
	"\x02id\x18\x01 \x01(\x03R\x02id\x12\x12\n" +
	"\x04name\x18\x02 \x01(\tR\x04name\x12\x12\n" +
	"\x04code\x18\x03 \x01(\tR\x04code\x12 \n" +
	"\vdescription\x18\x04 \x01(\tR\vdescription\x12\x12\n" +
	"\x04type\x18\x05 \x01(\x05R\x04type\x12\x16\n" +
	"\x06status\x18\x06 \x01(\x05R\x06status\x12%\n" +
	"\x06params\x18\a \x03(\v2\r.ai.ToolParamR\x06params\x12\x17\n" +
	"\amcp_url\x18\b \x01(\tR\x06mcpUrl\x12\x1b\n" +
	"\tmcp_token\x18\t \x01(\tR\bmcpToken\"Q\n" +
	"\x15BatchBindToolsRequest\x12\x19\n" +
	"\bagent_id\x18\x01 \x01(\x03R\aagentId\x12\x1d\n" +
	"\n" +
	"tool_codes\x18\x02 \x03(\tR\ttoolCodesB1\n" +
	"\x11dev.kratos.api.aiB\aAiProtoP\x01Z\x11backend/api/ai;aib\x06proto3"

var (
	file_api_ai_tool_proto_rawDescOnce sync.Once
	file_api_ai_tool_proto_rawDescData []byte
)

func file_api_ai_tool_proto_rawDescGZIP() []byte {
	file_api_ai_tool_proto_rawDescOnce.Do(func() {
		file_api_ai_tool_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_api_ai_tool_proto_rawDesc), len(file_api_ai_tool_proto_rawDesc)))
	})
	return file_api_ai_tool_proto_rawDescData
}

var file_api_ai_tool_proto_msgTypes = make([]protoimpl.MessageInfo, 7)
var file_api_ai_tool_proto_goTypes = []any{
	(*ToolParam)(nil),             // 0: ai.ToolParam
	(*ToolInfo)(nil),              // 1: ai.ToolInfo
	(*ListToolsRequest)(nil),      // 2: ai.ListToolsRequest
	(*ListToolsReply)(nil),        // 3: ai.ListToolsReply
	(*CreateToolRequest)(nil),     // 4: ai.CreateToolRequest
	(*UpdateToolRequest)(nil),     // 5: ai.UpdateToolRequest
	(*BatchBindToolsRequest)(nil), // 6: ai.BatchBindToolsRequest
}
var file_api_ai_tool_proto_depIdxs = []int32{
	0, // 0: ai.ToolInfo.params:type_name -> ai.ToolParam
	1, // 1: ai.ListToolsReply.list:type_name -> ai.ToolInfo
	0, // 2: ai.CreateToolRequest.params:type_name -> ai.ToolParam
	0, // 3: ai.UpdateToolRequest.params:type_name -> ai.ToolParam
	4, // [4:4] is the sub-list for method output_type
	4, // [4:4] is the sub-list for method input_type
	4, // [4:4] is the sub-list for extension type_name
	4, // [4:4] is the sub-list for extension extendee
	0, // [0:4] is the sub-list for field type_name
}

func init() { file_api_ai_tool_proto_init() }
func file_api_ai_tool_proto_init() {
	if File_api_ai_tool_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_api_ai_tool_proto_rawDesc), len(file_api_ai_tool_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   7,
			NumExtensions: 0,
			NumServices:   0,
		},
		GoTypes:           file_api_ai_tool_proto_goTypes,
		DependencyIndexes: file_api_ai_tool_proto_depIdxs,
		MessageInfos:      file_api_ai_tool_proto_msgTypes,
	}.Build()
	File_api_ai_tool_proto = out.File
	file_api_ai_tool_proto_goTypes = nil
	file_api_ai_tool_proto_depIdxs = nil
}
