// Code generated by gorm.io/gen. DO NOT EDIT.
// Code generated by gorm.io/gen. DO NOT EDIT.
// Code generated by gorm.io/gen. DO NOT EDIT.

package model

import (
	"time"
)

const TableNameFaEnsurePlan = "fa_ensure_plan"

// FaEnsurePlan mapped from table <fa_ensure_plan>
type FaEnsurePlan struct {
	ID             string     `gorm:"column:id;primaryKey" json:"id"`                                                   // 主键id
	Creator        *string    `gorm:"column:creator" json:"creator"`                                                    // 创建时间
	CreateDateTime *time.Time `gorm:"column:create_date_time;type:int unsigned;autoCreateTime" json:"create_date_time"` // 创建人
	Updater        *string    `gorm:"column:updater" json:"updater"`                                                    // 更新时间
	UpdateDateTime *time.Time `gorm:"column:update_date_time;type:int unsigned;autoUpdateTime" json:"update_date_time"` // 更新人
	IsSoftDelete   *int64     `gorm:"soft_delete.DeleteAt" json:"is_soft_delete"`                                       // 是否删除0否1是
	Remarks        *string    `gorm:"column:remarks" json:"remarks"`                                                    // 备注
	EnsureID       *string    `gorm:"column:ensure_id" json:"ensure_id"`                                                // 保障id
	Status         *int64     `gorm:"column:status" json:"status"`                                                      // 是否有效
	KeyPartsID     *string    `gorm:"column:key_parts_id" json:"key_parts_id"`                                          // 关重件id
	EnsureDate     *time.Time `gorm:"column:ensure_date" json:"ensure_date"`                                            // 保障时间
	StructureID    *string    `gorm:"column:structure_id" json:"structure_id"`                                          // 结构件id
	EnsureTypeID   *string    `gorm:"column:ensure_type_id" json:"ensure_type_id"`
}

// TableName FaEnsurePlan's table name
func (*FaEnsurePlan) TableName() string {
	return TableNameFaEnsurePlan
}
