// Code generated by gorm.io/gen. DO NOT EDIT.
// Code generated by gorm.io/gen. DO NOT EDIT.
// Code generated by gorm.io/gen. DO NOT EDIT.

package model

import (
	"time"
)

const TableNameFaEnsure = "fa_ensure"

// FaEnsure mapped from table <fa_ensure>
type FaEnsure struct {
	ID              string     `gorm:"column:id;primaryKey" json:"id"`                                                   // 主键id
	Creator         *string    `gorm:"column:creator" json:"creator"`                                                    // 创建时间
	CreateDateTime  *time.Time `gorm:"column:create_date_time;type:int unsigned;autoCreateTime" json:"create_date_time"` // 创建人
	Updater         *string    `gorm:"column:updater" json:"updater"`                                                    // 更新时间
	UpdateDateTime  *time.Time `gorm:"column:update_date_time;type:int unsigned;autoUpdateTime" json:"update_date_time"` // 更新人
	IsSoftDelete    *int64     `gorm:"soft_delete.DeleteAt" json:"is_soft_delete"`                                       // 是否删除0否1是
	Remarks         *string    `gorm:"column:remarks" json:"remarks"`                                                    // 备注
	Name            *string    `gorm:"column:name" json:"name"`                                                          // 名称
	Content         *string    `gorm:"column:content" json:"content"`                                                    // 内容
	KeyPartsModelID *string    `gorm:"column:key_parts_model_id" json:"key_parts_model_id"`                              // 关重件型号id
	KeyPartsID      *string    `gorm:"column:key_parts_id" json:"key_parts_id"`                                          // 关重件id
	TaskLevelID     *string    `gorm:"column:task_level_id" json:"task_level_id"`                                        // 任务级别id
	EnsureTypeID    *string    `gorm:"column:ensure_type_id" json:"ensure_type_id"`                                      // 保障类型id
	RaExtensionID   *string    `gorm:"column:ra_extension_id" json:"ra_extension_id"`                                    // 雷达分机id
	RaSystemID      *string    `gorm:"column:ra_system_id" json:"ra_system_id"`                                          // 雷达分系统id
	DocumentID      *string    `gorm:"column:document_id" json:"document_id"`                                            // 工卡id
}

// TableName FaEnsure's table name
func (*FaEnsure) TableName() string {
	return TableNameFaEnsure
}
