// Code generated by gorm.io/gen. DO NOT EDIT.
// Code generated by gorm.io/gen. DO NOT EDIT.
// Code generated by gorm.io/gen. DO NOT EDIT.

package model

import (
	"time"
)

const TableNameFaEnsureRecord = "fa_ensure_record"

// FaEnsureRecord mapped from table <fa_ensure_record>
type FaEnsureRecord struct {
	ID              string     `gorm:"column:id;primaryKey" json:"id"`                                                   // 主键id
	Creator         *string    `gorm:"column:creator" json:"creator"`                                                    // 创建时间
	CreateDateTime  *time.Time `gorm:"column:create_date_time;type:int unsigned;autoCreateTime" json:"create_date_time"` // 创建人
	Updater         *string    `gorm:"column:updater" json:"updater"`                                                    // 更新时间
	UpdateDateTime  *time.Time `gorm:"column:update_date_time;type:int unsigned;autoUpdateTime" json:"update_date_time"` // 更新人
	IsSoftDelete    *int64     `gorm:"soft_delete.DeleteAt" json:"is_soft_delete"`                                       // 是否删除0否1是
	Remarks         *string    `gorm:"column:remarks" json:"remarks"`                                                    // 备注
	WayID           *string    `gorm:"column:way_id" json:"way_id"`                                                      // 方法id
	PlanID          *string    `gorm:"column:plan_id" json:"plan_id"`                                                    // 计划id
	DocumentationID *string    `gorm:"column:documentation_id" json:"documentation_id"`                                  // 文档id
	EquipmentID     *string    `gorm:"column:equipment_id" json:"equipment_id"`                                          // 器材id
	Content         *string    `gorm:"column:content" json:"content"`                                                    // 保障内容
	User            *string    `gorm:"column:user" json:"user"`                                                          // 人员
	StructureID     *string    `gorm:"column:structure_id" json:"structure_id"`                                          // 结构件id
	EnsureDate      *time.Time `gorm:"column:ensure_date" json:"ensure_date"`                                            // 保障时间
}

// TableName FaEnsureRecord's table name
func (*FaEnsureRecord) TableName() string {
	return TableNameFaEnsureRecord
}
