// Code generated by gorm.io/gen. DO NOT EDIT.
// Code generated by gorm.io/gen. DO NOT EDIT.
// Code generated by gorm.io/gen. DO NOT EDIT.

package model

import (
	"time"
)

const TableNameFaFaultRecord = "fa_fault_record"

// FaFaultRecord mapped from table <fa_fault_record>
type FaFaultRecord struct {
	ID             string     `gorm:"column:id;primaryKey" json:"id"`                                                   // 主键id
	Creator        *string    `gorm:"column:creator" json:"creator"`                                                    // 创建时间
	CreateDateTime *time.Time `gorm:"column:create_date_time;type:int unsigned;autoCreateTime" json:"create_date_time"` // 创建人
	Updater        *string    `gorm:"column:updater" json:"updater"`                                                    // 更新时间
	UpdateDateTime *time.Time `gorm:"column:update_date_time;type:int unsigned;autoUpdateTime" json:"update_date_time"` // 更新人
	IsSoftDelete   *int64     `gorm:"soft_delete.DeleteAt" json:"is_soft_delete"`                                       // 是否删除0否1是
	Remarks        *string    `gorm:"column:remarks" json:"remarks"`                                                    // 备注
	StructureID    *string    `gorm:"column:structure_id" json:"structure_id"`                                          // 结构件id
	IsDeal         *int64     `gorm:"column:is_deal" json:"is_deal"`                                                    // 是否处理
	FaultResource  *int64     `gorm:"column:fault_resource" json:"fault_resource"`                                      // 故障来源
	DownTime       *time.Time `gorm:"column:down_time" json:"down_time"`                                                // 故障时间
}

// TableName FaFaultRecord's table name
func (*FaFaultRecord) TableName() string {
	return TableNameFaFaultRecord
}
