// Code generated by gorm.io/gen. DO NOT EDIT.
// Code generated by gorm.io/gen. DO NOT EDIT.
// Code generated by gorm.io/gen. DO NOT EDIT.

package model

import (
	"time"
)

const TableNameFaPhenomenonRecord = "fa_phenomenon_record"

// FaPhenomenonRecord mapped from table <fa_phenomenon_record>
type FaPhenomenonRecord struct {
	ID             string     `gorm:"column:id;primaryKey" json:"id"`                                                   // 主键id
	Creator        *string    `gorm:"column:creator" json:"creator"`                                                    // 创建时间
	CreateDateTime *time.Time `gorm:"column:create_date_time;type:int unsigned;autoCreateTime" json:"create_date_time"` // 创建人
	Updater        *string    `gorm:"column:updater" json:"updater"`                                                    // 更新时间
	UpdateDateTime *time.Time `gorm:"column:update_date_time;type:int unsigned;autoUpdateTime" json:"update_date_time"` // 更新人
	IsSoftDelete   *int64     `gorm:"soft_delete.DeleteAt" json:"is_soft_delete"`                                       // 是否删除0否1是
	Remarks        *string    `gorm:"column:remarks" json:"remarks"`                                                    // 备注
	FaultRecordID  *string    `gorm:"column:fault_record_id" json:"fault_record_id"`                                    // 故障记录id
	PhenomenonID   *string    `gorm:"column:phenomenon_id" json:"phenomenon_id"`                                        // 故障现象id
}

// TableName FaPhenomenonRecord's table name
func (*FaPhenomenonRecord) TableName() string {
	return TableNameFaPhenomenonRecord
}
