// Code generated by gorm.io/gen. DO NOT EDIT.
// Code generated by gorm.io/gen. DO NOT EDIT.
// Code generated by gorm.io/gen. DO NOT EDIT.

package model

import (
	"time"
)

const TableNameFaPhenomenon = "fa_phenomenon"

// FaPhenomenon mapped from table <fa_phenomenon>
type FaPhenomenon struct {
	ID             string     `gorm:"column:id;primaryKey" json:"id"`                                                   // 主键id
	Creator        *string    `gorm:"column:creator" json:"creator"`                                                    // 创建时间
	CreateDateTime *time.Time `gorm:"column:create_date_time;type:int unsigned;autoCreateTime" json:"create_date_time"` // 创建人
	Updater        *string    `gorm:"column:updater" json:"updater"`                                                    // 更新时间
	UpdateDateTime *time.Time `gorm:"column:update_date_time;type:int unsigned;autoUpdateTime" json:"update_date_time"` // 更新人
	IsSoftDelete   *int64     `gorm:"soft_delete.DeleteAt" json:"is_soft_delete"`                                       // 是否删除0否1是
	Remarks        *string    `gorm:"column:remarks" json:"remarks"`                                                    // 中文名称
	SpecialID      *string    `gorm:"column:special_id" json:"special_id"`                                              // 现象编号id
	Status         *string    `gorm:"column:status" json:"status"`                                                      // 告警状态：IN表示不可操作，MM表示强制维护，MR表示请求维护，NA表示其他状态
	RadarType      *string    `gorm:"column:radar_type" json:"radar_type"`                                              // 雷达型号
}

// TableName FaPhenomenon's table name
func (*FaPhenomenon) TableName() string {
	return TableNameFaPhenomenon
}
