// Code generated by gorm.io/gen. DO NOT EDIT.
// Code generated by gorm.io/gen. DO NOT EDIT.
// Code generated by gorm.io/gen. DO NOT EDIT.

package model

import (
	"time"
)

const TableNameFiDataType = "fi_data_type"

// FiDataType mapped from table <fi_data_type>
type FiDataType struct {
	ID             int64      `gorm:"column:id;primaryKey;autoIncrement:true" json:"id"`                                // 主键id
	Creator        *string    `gorm:"column:creator" json:"creator"`                                                    // 创建时间
	CreateDateTime *time.Time `gorm:"column:create_date_time;type:int unsigned;autoCreateTime" json:"create_date_time"` // 创建人
	Updater        *string    `gorm:"column:updater" json:"updater"`                                                    // 更新时间
	UpdateDateTime *time.Time `gorm:"column:update_date_time;type:int unsigned;autoUpdateTime" json:"update_date_time"` // 更新人
	IsSoftDelete   *int64     `gorm:"soft_delete.DeleteAt" json:"is_soft_delete"`                                       // 是否删除0否1是
	Remarks        *string    `gorm:"column:remarks" json:"remarks"`                                                    // 备注
	Name           *string    `gorm:"column:name" json:"name"`                                                          // 数据类型名称
	CustomName     *string    `gorm:"column:custom_name" json:"custom_name"`                                            // 自定义类型名称
	BasicByteNum   *int64     `gorm:"column:basic_byte_num" json:"basic_byte_num"`                                      // 基本字节数
	BasicTypeNum   int64      `gorm:"column:basic_type_num;not null" json:"basic_type_num"`                             // 基本类型数目
}

// TableName FiDataType's table name
func (*FiDataType) TableName() string {
	return TableNameFiDataType
}
