// Code generated by gorm.io/gen. DO NOT EDIT.
// Code generated by gorm.io/gen. DO NOT EDIT.
// Code generated by gorm.io/gen. DO NOT EDIT.

package model

import (
	"time"
)

const TableNameFiRealTimeFileStructure = "fi_real_time_file_structure"

// FiRealTimeFileStructure mapped from table <fi_real_time_file_structure>
type FiRealTimeFileStructure struct {
	ID                int64      `gorm:"column:id;primaryKey;autoIncrement:true" json:"id"`                                // 主键id
	FileTypeID        *string    `gorm:"column:file_type_id" json:"file_type_id"`                                          // 文件类型id
	Creator           *string    `gorm:"column:creator" json:"creator"`                                                    // 创建时间
	CreateDateTime    *time.Time `gorm:"column:create_date_time;type:int unsigned;autoCreateTime" json:"create_date_time"` // 创建人
	Updater           *string    `gorm:"column:updater" json:"updater"`                                                    // 更新时间
	UpdateDateTime    *time.Time `gorm:"column:update_date_time;type:int unsigned;autoUpdateTime" json:"update_date_time"` // 更新人
	IsSoftDelete      *int64     `gorm:"soft_delete.DeleteAt" json:"is_soft_delete"`                                       // 是否删除0否1是
	Remarks           *string    `gorm:"column:remarks" json:"remarks"`                                                    // 备注
	IsComplete        *[]uint8   `gorm:"column:is_complete" json:"is_complete"`                                            // 整机否
	DataSerial        *int64     `gorm:"column:data_serial" json:"data_serial"`                                            // 数据序号
	EName             *string    `gorm:"column:e_name" json:"e_name"`                                                      // 英文名称
	CName             *string    `gorm:"column:c_name" json:"c_name"`                                                      // 中文名称
	Unit              *string    `gorm:"column:unit" json:"unit"`                                                          // 单位
	DataTypeID        *int64     `gorm:"column:data_type_id" json:"data_type_id"`                                          // 数据类型id
	Max               *float32   `gorm:"column:max" json:"max"`                                                            // 最大值
	Min               *float32   `gorm:"column:min" json:"min"`                                                            // 最小值
	Length            *int64     `gorm:"column:length" json:"length"`                                                      // 长度
	KeyPartsModelID   *string    `gorm:"column:key_parts_model_id" json:"key_parts_model_id"`                              // 关重件型号
	IsLargeScreen     *int64     `gorm:"column:is_Large_screen" json:"is_Large_screen"`                                    // 大屏是否显示
	IsStatus          *int64     `gorm:"column:is_status" json:"is_status"`                                                // 状态否
	SystemID          *string    `gorm:"column:system_id" json:"system_id"`                                                // 分系统id
	ExtensionID       *string    `gorm:"column:extension_id" json:"extension_id"`                                          // 分机id
	Scale             *int64     `gorm:"column:scale" json:"scale"`                                                        // 数据放大倍数
	ImportantPara     *[]uint8   `gorm:"column:important_para;default:b'0" json:"important_para"`                          // 是否重要参数
	Icon              *string    `gorm:"column:icon" json:"icon"`                                                          // 参数图片
	DisplayLocationID *string    `gorm:"column:display_location_id" json:"display_location_id"`                            // 大屏区域编号
}

// TableName FiRealTimeFileStructure's table name
func (*FiRealTimeFileStructure) TableName() string {
	return TableNameFiRealTimeFileStructure
}
