// Code generated by gorm.io/gen. DO NOT EDIT.
// Code generated by gorm.io/gen. DO NOT EDIT.
// Code generated by gorm.io/gen. DO NOT EDIT.

package model

import (
	"time"
)

const TableNameFiSubsystemStatusDatum = "fi_subsystem_status_data"

// FiSubsystemStatusDatum mapped from table <fi_subsystem_status_data>
type FiSubsystemStatusDatum struct {
	ID             string     `gorm:"column:id;primaryKey" json:"id"`                                                   // 主键id
	Creator        *string    `gorm:"column:creator" json:"creator"`                                                    // 创建时间
	CreateDateTime *time.Time `gorm:"column:create_date_time;type:int unsigned;autoCreateTime" json:"create_date_time"` // 创建人
	Updater        *string    `gorm:"column:updater" json:"updater"`                                                    // 更新时间
	UpdateDateTime *time.Time `gorm:"column:update_date_time;type:int unsigned;autoUpdateTime" json:"update_date_time"` // 更新人
	IsSoftDelete   *int64     `gorm:"soft_delete.DeleteAt" json:"is_soft_delete"`                                       // 是否删除0否1是
	Remarks        *string    `gorm:"column:remarks" json:"remarks"`                                                    // 备注
	StatusSource   *string    `gorm:"column:status_source" json:"status_source"`                                        // 状态字段来源
	FileTypeID     *string    `gorm:"column:file_type_id" json:"file_type_id"`                                          // 文件类型id
	EName          *string    `gorm:"column:e_name" json:"e_name"`                                                      // 英文名称
	CName          *string    `gorm:"column:c_name" json:"c_name"`                                                      // 中文名称
	StatusOrder    *int64     `gorm:"column:status_order" json:"status_order"`                                          // 状态序号
	Length         *int64     `gorm:"column:length" json:"length"`                                                      // 实时文件接口字段名
	ZeroStatusMean *int64     `gorm:"column:zero_status_mean" json:"zero_status_mean"`                                  // 0状态含义
	SubsystemID    *int64     `gorm:"column:subsystem_id" json:"subsystem_id"`                                          // 子系统编号
	BitNumber      *int64     `gorm:"column:bit_number" json:"bit_number"`                                              // bit数目
	RealTimeDataID *string    `gorm:"column:real_time_data_id" json:"real_time_data_id"`                                // 数据结构id
	RaExtensionID  *string    `gorm:"column:ra_extension_id" json:"ra_extension_id"`                                    // 分机id
	KeyPartModelID *string    `gorm:"column:key_part_model_id" json:"key_part_model_id"`                                // 关重件型号id
}

// TableName FiSubsystemStatusDatum's table name
func (*FiSubsystemStatusDatum) TableName() string {
	return TableNameFiSubsystemStatusDatum
}
