// Code generated by gorm.io/gen. DO NOT EDIT.
// Code generated by gorm.io/gen. DO NOT EDIT.
// Code generated by gorm.io/gen. DO NOT EDIT.

package model

import (
	"time"
)

const TableNameFiTaRelation = "fi_ta_relation"

// FiTaRelation mapped from table <fi_ta_relation>
type FiTaRelation struct {
	ID             string     `gorm:"column:id;primaryKey" json:"id"`                                                   // 主键id
	Creator        *string    `gorm:"column:creator" json:"creator"`                                                    // 创建时间
	CreateDateTime *time.Time `gorm:"column:create_date_time;type:int unsigned;autoCreateTime" json:"create_date_time"` // 创建人
	Updater        *string    `gorm:"column:updater" json:"updater"`                                                    // 更新时间
	UpdateDateTime *time.Time `gorm:"column:update_date_time;type:int unsigned;autoUpdateTime" json:"update_date_time"` // 更新人
	IsSoftDelete   *int64     `gorm:"soft_delete.DeleteAt" json:"is_soft_delete"`                                       // 是否删除0否1是
	Remarks        *string    `gorm:"column:remarks" json:"remarks"`                                                    // 备注
	RealID         *string    `gorm:"column:real_id" json:"real_id"`                                                    // 实时文件id
	ModelID        *string    `gorm:"column:model_id" json:"model_id"`                                                  // 算法模型id
	Other          *string    `gorm:"column:other" json:"other"`                                                        // 其他
}

// TableName FiTaRelation's table name
func (*FiTaRelation) TableName() string {
	return TableNameFiTaRelation
}
