// Code generated by gorm.io/gen. DO NOT EDIT.
// Code generated by gorm.io/gen. DO NOT EDIT.
// Code generated by gorm.io/gen. DO NOT EDIT.

package model

import (
	"time"
)

const TableNameRaInterventionType = "ra_intervention_type"

// RaInterventionType mapped from table <ra_intervention_type>
type RaInterventionType struct {
	ID               *string    `gorm:"column:id" json:"id"`                                                              // 主键id
	Creator          *string    `gorm:"column:creator" json:"creator"`                                                    // 创建时间
	CreateDateTime   *time.Time `gorm:"column:create_date_time;type:int unsigned;autoCreateTime" json:"create_date_time"` // 创建人
	Updater          *string    `gorm:"column:updater" json:"updater"`                                                    // 更新时间
	UpdateDateTime   *time.Time `gorm:"column:update_date_time;type:int unsigned;autoUpdateTime" json:"update_date_time"` // 更新人
	IsSoftDelete     *int64     `gorm:"soft_delete.DeleteAt" json:"is_soft_delete"`                                       // 是否删除0否1是
	Remarks          *string    `gorm:"column:remarks" json:"remarks"`                                                    // 备注
	Account          *string    `gorm:"column:account" json:"account"`                                                    // 账号
	Password         *string    `gorm:"column:password" json:"password"`                                                  // 密码
	DataSite         *string    `gorm:"column:data_site" json:"data_site"`                                                // 数据存放位置
	InterventionType *string    `gorm:"column:intervention_type" json:"intervention_type"`                                // 接入方式
	IsIntervention   *int64     `gorm:"column:is_intervention" json:"is_intervention"`                                    // 接入否
	RadarID          *string    `gorm:"column:radar_id" json:"radar_id"`                                                  // 雷达id
}

// TableName RaInterventionType's table name
func (*RaInterventionType) TableName() string {
	return TableNameRaInterventionType
}
