// Code generated by gorm.io/gen. DO NOT EDIT.
// Code generated by gorm.io/gen. DO NOT EDIT.
// Code generated by gorm.io/gen. DO NOT EDIT.

package model

import (
	"time"
)

const TableNameRaSystem = "ra_system"

// RaSystem mapped from table <ra_system>
type RaSystem struct {
	ID               string     `gorm:"column:id;primaryKey" json:"id"`                                                   // 主键id
	Creator          *string    `gorm:"column:creator" json:"creator"`                                                    // 创建时间
	CreateDateTime   *time.Time `gorm:"column:create_date_time;type:int unsigned;autoCreateTime" json:"create_date_time"` // 创建人
	Updater          *string    `gorm:"column:updater" json:"updater"`                                                    // 更新时间
	UpdateDateTime   *time.Time `gorm:"column:update_date_time;type:int unsigned;autoUpdateTime" json:"update_date_time"` // 更新人
	IsSoftDelete     *int64     `gorm:"soft_delete.DeleteAt" json:"is_soft_delete"`                                       // 是否删除0否1是
	Remarks          *string    `gorm:"column:remarks" json:"remarks"`                                                    // 备注
	Name             *string    `gorm:"column:name" json:"name"`                                                          // 名称
	Describetion     *string    `gorm:"column:describetion" json:"describetion"`                                          // 描述
	Weight           *float32   `gorm:"column:weight" json:"weight"`                                                      // 分系统在整机中的权重
	PerfectIcon      *string    `gorm:"column:perfect_icon" json:"perfect_icon"`                                          // 健康状态图片
	FaultIcon        *string    `gorm:"column:fault_icon" json:"fault_icon"`                                              // 故障图片
	LowIcon          *string    `gorm:"column:low_icon" json:"low_icon"`                                                  // 低效图片
	DisplaySerialNum *int64     `gorm:"column:display_serial_num" json:"display_serial_num"`                              // 显示序号
}

// TableName RaSystem's table name
func (*RaSystem) TableName() string {
	return TableNameRaSystem
}
