// Code generated by gorm.io/gen. DO NOT EDIT.
// Code generated by gorm.io/gen. DO NOT EDIT.
// Code generated by gorm.io/gen. DO NOT EDIT.

package model

import (
	"time"
)

const TableNameRaStorage = "ra_storage"

// RaStorage mapped from table <ra_storage>
type RaStorage struct {
	ID              string     `gorm:"column:id;primaryKey" json:"id"`                                                   // 主键id
	Creator         *string    `gorm:"column:creator" json:"creator"`                                                    // 创建时间
	CreateDateTime  *time.Time `gorm:"column:create_date_time;type:int unsigned;autoCreateTime" json:"create_date_time"` // 创建人
	Updater         *string    `gorm:"column:updater" json:"updater"`                                                    // 更新时间
	UpdateDateTime  *time.Time `gorm:"column:update_date_time;type:int unsigned;autoUpdateTime" json:"update_date_time"` // 更新人
	IsSoftDelete    *int64     `gorm:"soft_delete.DeleteAt" json:"is_soft_delete"`                                       // 是否删除0否1是
	Remarks         *string    `gorm:"column:remarks" json:"remarks"`                                                    // 备注
	KeyPartsModelID *string    `gorm:"column:key_parts_model_id" json:"key_parts_model_id"`                              // 关重件型号id
	StorageHomeID   *string    `gorm:"column:storage_home_id" json:"storage_home_id"`                                    // 库房id
	StorageNum      *int64     `gorm:"column:storage_num" json:"storage_num"`                                            // 库存数量
	ManufactureDate *time.Time `gorm:"column:manufacture_date" json:"manufacture_date"`                                  // 生产日期
	AddDate         *time.Time `gorm:"column:add_date" json:"add_date"`                                                  // 入库日期
	ValidityDate    *int64     `gorm:"column:validity_date" json:"validity_date"`                                        // 有效期（月）
	AreaID          *string    `gorm:"column:area_id" json:"area_id"`
}

// TableName RaStorage's table name
func (*RaStorage) TableName() string {
	return TableNameRaStorage
}
