// Code generated by gorm.io/gen. DO NOT EDIT.
// Code generated by gorm.io/gen. DO NOT EDIT.
// Code generated by gorm.io/gen. DO NOT EDIT.

package model

import (
	"time"
)

const TableNameScTeachDatum = "sc_teach_data"

// ScTeachDatum mapped from table <sc_teach_data>
type ScTeachDatum struct {
	ID             string     `gorm:"column:id;primaryKey" json:"id"`                                                   // 主键id
	Creator        *string    `gorm:"column:creator" json:"creator"`                                                    // 创建时间
	CreateDateTime *time.Time `gorm:"column:create_date_time;type:int unsigned;autoCreateTime" json:"create_date_time"` // 创建人
	Updater        *string    `gorm:"column:updater" json:"updater"`                                                    // 更新时间
	UpdateDateTime *time.Time `gorm:"column:update_date_time;type:int unsigned;autoUpdateTime" json:"update_date_time"` // 更新人
	IsSoftDelete   *int64     `gorm:"soft_delete.DeleteAt" json:"is_soft_delete"`                                       // 是否删除0否1是
	Remarks        *string    `gorm:"column:remarks" json:"remarks"`                                                    // 备注
	ViewNum        *int64     `gorm:"column:view_num" json:"view_num"`                                                  // 浏览次数
	DataTypeID     *string    `gorm:"column:data_type_id" json:"data_type_id"`                                          // 类别id
	Name           *string    `gorm:"column:name" json:"name"`                                                          // 资料名称
	Describetion   *string    `gorm:"column:describetion" json:"describetion"`                                          // 资料描述
	URL            *string    `gorm:"column:url" json:"url"`                                                            // 地址
	DownNum        *int64     `gorm:"column:down_num" json:"down_num"`                                                  // 下载次数
}

// TableName ScTeachDatum's table name
func (*ScTeachDatum) TableName() string {
	return TableNameScTeachDatum
}
