// Code generated by gorm.io/gen. DO NOT EDIT.
// Code generated by gorm.io/gen. DO NOT EDIT.
// Code generated by gorm.io/gen. DO NOT EDIT.

package model

import (
	"time"
)

const TableNameSysParameterType = "sys_parameter_type"

// SysParameterType mapped from table <sys_parameter_type>
type SysParameterType struct {
	ID             *string    `gorm:"column:id" json:"id"`                                                              // 主键id
	Creator        *string    `gorm:"column:creator" json:"creator"`                                                    // 创建时间
	CreateDateTime *time.Time `gorm:"column:create_date_time;type:int unsigned;autoCreateTime" json:"create_date_time"` // 创建人
	Updater        *string    `gorm:"column:updater" json:"updater"`                                                    // 更新时间
	UpdateDateTime *time.Time `gorm:"column:update_date_time;type:int unsigned;autoUpdateTime" json:"update_date_time"` // 更新人
	IsSoftDelete   *int64     `gorm:"soft_delete.DeleteAt" json:"is_soft_delete"`                                       // 是否删除0否1是
	Remarks        *string    `gorm:"column:remarks" json:"remarks"`                                                    // 备注
	CodeName       *string    `gorm:"column:code_name" json:"code_name"`                                                // 代码名称
	ChineseName    *string    `gorm:"column:chinese_name" json:"chinese_name"`                                          // 代码中文名称
}

// TableName SysParameterType's table name
func (*SysParameterType) TableName() string {
	return TableNameSysParameterType
}
