// Code generated by gorm.io/gen. DO NOT EDIT.
// Code generated by gorm.io/gen. DO NOT EDIT.
// Code generated by gorm.io/gen. DO NOT EDIT.

package model

import (
	"time"
)

const TableNameSysRole = "sys_role"

// SysRole mapped from table <sys_role>
type SysRole struct {
	ID             string     `gorm:"column:id;primaryKey" json:"id"`                                                   // 主键Id
	Creator        *string    `gorm:"column:creator" json:"creator"`                                                    // 创建者
	CreateDateTime *time.Time `gorm:"column:create_date_time;type:int unsigned;autoCreateTime" json:"create_date_time"` // 创建时间
	Updater        *string    `gorm:"column:updater" json:"updater"`                                                    // 修改者
	UpdateDateTime *time.Time `gorm:"column:update_date_time;type:int unsigned;autoUpdateTime" json:"update_date_time"` // 修改时间
	IsSoftDelete   *int64     `gorm:"soft_delete.DeleteAt" json:"is_soft_delete"`                                       // 是否删除0否1是
	RoleName       *string    `gorm:"column:role_name" json:"role_name"`                                                // 角色名称
	Description    *string    `gorm:"column:description" json:"description"`                                            // 角色描述
	Remarks        *string    `gorm:"column:remarks" json:"remarks"`                                                    // 备注
}

// TableName SysRole's table name
func (*SysRole) TableName() string {
	return TableNameSysRole
}
