// Code generated by gorm.io/gen. DO NOT EDIT.
// Code generated by gorm.io/gen. DO NOT EDIT.
// Code generated by gorm.io/gen. DO NOT EDIT.

package model

import (
	"time"
)

const TableNameSysMessageProcess = "sys_message_process"

// SysMessageProcess mapped from table <sys_message_process>
type SysMessageProcess struct {
	ID             string     `gorm:"column:id;primaryKey" json:"id"`                                                   // 主键id
	Creator        *string    `gorm:"column:creator" json:"creator"`                                                    // 创建时间
	CreateDateTime *time.Time `gorm:"column:create_date_time;type:int unsigned;autoCreateTime" json:"create_date_time"` // 创建人
	Updater        *string    `gorm:"column:updater" json:"updater"`                                                    // 更新时间
	UpdateDateTime *time.Time `gorm:"column:update_date_time;type:int unsigned;autoUpdateTime" json:"update_date_time"` // 更新人
	IsSoftDelete   *int64     `gorm:"soft_delete.DeleteAt" json:"is_soft_delete"`                                       // 是否删除0否1是
	Remarks        *string    `gorm:"column:remarks" json:"remarks"`                                                    // 备注
	Recipient      *string    `gorm:"column:recipient" json:"recipient"`                                                // 接收者
	MessageID      *string    `gorm:"column:message_id" json:"message_id"`                                              // 消息id
}

// TableName SysMessageProcess's table name
func (*SysMessageProcess) TableName() string {
	return TableNameSysMessageProcess
}
