// Code generated by gorm.io/gen. DO NOT EDIT.
// Code generated by gorm.io/gen. DO NOT EDIT.
// Code generated by gorm.io/gen. DO NOT EDIT.

package model

import (
	"time"
)

const TableNameSysParameter = "sys_parameter"

// SysParameter mapped from table <sys_parameter>
type SysParameter struct {
	ID              *string    `gorm:"column:id" json:"id"`                                                              // 主键id
	Creator         *string    `gorm:"column:creator" json:"creator"`                                                    // 创建时间
	CreateDateTime  *time.Time `gorm:"column:create_date_time;type:int unsigned;autoCreateTime" json:"create_date_time"` // 创建人
	Updater         *string    `gorm:"column:updater" json:"updater"`                                                    // 更新时间
	UpdateDateTime  *time.Time `gorm:"column:update_date_time;type:int unsigned;autoUpdateTime" json:"update_date_time"` // 更新人
	IsSoftDelete    *int64     `gorm:"soft_delete.DeleteAt" json:"is_soft_delete"`                                       // 是否删除0否1是
	Remarks         *string    `gorm:"column:remarks" json:"remarks"`                                                    // 备注
	ParameterName   *string    `gorm:"column:parameter_name" json:"parameter_name"`                                      // 参数名称
	ParameterCode   *string    `gorm:"column:parameter_code" json:"parameter_code"`                                      // 参数代码
	ParameterTypeID *string    `gorm:"column:parameter_type_id" json:"parameter_type_id"`                                // 参数类型id
}

// TableName SysParameter's table name
func (*SysParameter) TableName() string {
	return TableNameSysParameter
}
