// Code generated by gorm.io/gen. DO NOT EDIT.
// Code generated by gorm.io/gen. DO NOT EDIT.
// Code generated by gorm.io/gen. DO NOT EDIT.

package model

import (
	"time"
)

const TableNameSysOperationRole = "sys_operation_role"

// SysOperationRole mapped from table <sys_operation_role>
type SysOperationRole struct {
	ID             string     `gorm:"column:id;primaryKey" json:"id"`                                                   // 主键
	RoleID         *string    `gorm:"column:role_id" json:"role_id"`                                                    // 角色id
	OperationID    *string    `gorm:"column:operation_id" json:"operation_id"`                                          // 操作id
	Remarks        *string    `gorm:"column:remarks" json:"remarks"`                                                    // 备注
	IsSoftDelete   *int64     `gorm:"soft_delete.DeleteAt" json:"is_soft_delete"`                                       // 是否删除
	Creator        *string    `gorm:"column:creator" json:"creator"`                                                    // 创建者
	CreateDateTime *time.Time `gorm:"column:create_date_time;type:int unsigned;autoCreateTime" json:"create_date_time"` // 创建时间
	Updater        *string    `gorm:"column:updater" json:"updater"`                                                    // 更新者
	UpdateDateTime *time.Time `gorm:"column:update_date_time;type:int unsigned;autoUpdateTime" json:"update_date_time"` // 更新时间
}

// TableName SysOperationRole's table name
func (*SysOperationRole) TableName() string {
	return TableNameSysOperationRole
}
