// Code generated by gorm.io/gen. DO NOT EDIT.
// Code generated by gorm.io/gen. DO NOT EDIT.
// Code generated by gorm.io/gen. DO NOT EDIT.

package model

import (
	"time"
)

const TableNameSysUser = "sys_user"

// SysUser mapped from table <sys_user>
type SysUser struct {
	ID             string     `gorm:"column:id;primaryKey" json:"id"`                                                   // 主键Id
	Creator        *string    `gorm:"column:creator" json:"creator"`                                                    // 创建者
	CreateDateTime *time.Time `gorm:"column:create_date_time;type:int unsigned;autoCreateTime" json:"create_date_time"` // 创建时间
	Updater        *string    `gorm:"column:updater" json:"updater"`                                                    // 修改者
	UpdateDateTime *time.Time `gorm:"column:update_date_time;type:int unsigned;autoUpdateTime" json:"update_date_time"` // 修改时间
	IsSoftDelete   *int64     `gorm:"soft_delete.DeleteAt" json:"is_soft_delete"`                                       // 是否删除0否1是
	Username       *string    `gorm:"column:username" json:"username"`                                                  // 用户名
	Password       *string    `gorm:"column:password" json:"password"`                                                  // 密码
	Salt           *string    `gorm:"column:salt" json:"salt"`                                                          // 盐
	RealName       *string    `gorm:"column:real_name" json:"real_name"`                                                // 真实姓名
	Mobile         *string    `gorm:"column:mobile" json:"mobile"`                                                      // 手机号
	Mailbox        *string    `gorm:"column:mailbox" json:"mailbox"`                                                    // 邮箱
	JobName        *string    `gorm:"column:job_name" json:"job_name"`                                                  // 职业
	CertificatesID *string    `gorm:"column:certificates_id" json:"certificates_id"`                                    // 证件id
	UserType       *string    `gorm:"column:user_type" json:"user_type"`                                                // 用户类型00政府用户01企业用户02政府后台用户03企业后台用户
	Token          *string    `gorm:"column:token" json:"token"`                                                        // 用户的token
	Remarks        *string    `gorm:"column:remarks" json:"remarks"`                                                    // 备注
}

// TableName SysUser's table name
func (*SysUser) TableName() string {
	return TableNameSysUser
}
