// Code generated by gorm.io/gen. DO NOT EDIT.
// Code generated by gorm.io/gen. DO NOT EDIT.
// Code generated by gorm.io/gen. DO NOT EDIT.

package model

import (
	"time"
)

const TableNameSysOperation = "sys_operation"

// SysOperation mapped from table <sys_operation>
type SysOperation struct {
	ID               string     `gorm:"column:id;primaryKey" json:"id"`                                                   // 主键
	InterfaceURL     *string    `gorm:"column:interface_url" json:"interface_url"`                                        // 接口url
	ButtonPictureURL *string    `gorm:"column:button_picture_url" json:"button_picture_url"`                              // 按钮图片url
	PageID           *string    `gorm:"column:page_id" json:"page_id"`                                                    // 页面id
	Name             *string    `gorm:"column:name" json:"name"`                                                          // 名称
	Description      *string    `gorm:"column:description" json:"description"`                                            // 描述
	Remarks          *string    `gorm:"column:remarks" json:"remarks"`                                                    // 备注
	IsSoftDelete     *int64     `gorm:"soft_delete.DeleteAt" json:"is_soft_delete"`                                       // 是否删除
	Creator          *string    `gorm:"column:creator" json:"creator"`                                                    // 创建者
	CreateDateTime   *time.Time `gorm:"column:create_date_time;type:int unsigned;autoCreateTime" json:"create_date_time"` // 创建时间
	Updater          *string    `gorm:"column:updater" json:"updater"`                                                    // 更新者
	UpdateDateTime   *time.Time `gorm:"column:update_date_time;type:int unsigned;autoUpdateTime" json:"update_date_time"` // 更新时间
	Router           *string    `gorm:"column:router" json:"router"`                                                      // 标识
}

// TableName SysOperation's table name
func (*SysOperation) TableName() string {
	return TableNameSysOperation
}
