// Code generated by gorm.io/gen. DO NOT EDIT.
// Code generated by gorm.io/gen. DO NOT EDIT.
// Code generated by gorm.io/gen. DO NOT EDIT.

package model

import (
	"time"
)

const TableNameSysMessage = "sys_message"

// SysMessage mapped from table <sys_message>
type SysMessage struct {
	ID             *string    `gorm:"column:id" json:"id"`                                                              // 主键id
	Creator        *string    `gorm:"column:creator" json:"creator"`                                                    // 创建时间
	CreateDateTime *time.Time `gorm:"column:create_date_time;type:int unsigned;autoCreateTime" json:"create_date_time"` // 创建人
	Updater        *string    `gorm:"column:updater" json:"updater"`                                                    // 更新时间
	UpdateDateTime *time.Time `gorm:"column:update_date_time;type:int unsigned;autoUpdateTime" json:"update_date_time"` // 更新人
	IsSoftDelete   *int64     `gorm:"soft_delete.DeleteAt" json:"is_soft_delete"`                                       // 是否删除0否1是
	Remakes        *string    `gorm:"column:remakes" json:"remakes"`                                                    // 备注
	Source         *string    `gorm:"column:source" json:"source"`                                                      // 来源
	Describetion   *string    `gorm:"column:describetion" json:"describetion"`                                          // 描述
	Type           *int64     `gorm:"column:type" json:"type"`                                                          // 类别故障0维修1保障2
	Content        *string    `gorm:"column:content" json:"content"`                                                    // 内容
	AreaID         *string    `gorm:"column:area_id" json:"area_id"`                                                    // 区域id
}

// TableName SysMessage's table name
func (*SysMessage) TableName() string {
	return TableNameSysMessage
}
