// Code generated by gorm.io/gen. DO NOT EDIT.
// Code generated by gorm.io/gen. DO NOT EDIT.
// Code generated by gorm.io/gen. DO NOT EDIT.

package model

import (
	"time"
)

const TableNameTaAlgorithmExpertKnowledge = "ta_algorithm_expert_knowledge"

// TaAlgorithmExpertKnowledge mapped from table <ta_algorithm_expert_knowledge>
type TaAlgorithmExpertKnowledge struct {
	ID                string     `gorm:"column:id;primaryKey" json:"id"`                                                   // 主键id
	Creator           *string    `gorm:"column:creator" json:"creator"`                                                    // 创建时间
	CreateDateTime    *time.Time `gorm:"column:create_date_time;type:int unsigned;autoCreateTime" json:"create_date_time"` // 创建人
	Updater           *string    `gorm:"column:updater" json:"updater"`                                                    // 更新时间
	UpdateDateTime    *time.Time `gorm:"column:update_date_time;type:int unsigned;autoUpdateTime" json:"update_date_time"` // 更新人
	IsSoftDelete      *int64     `gorm:"soft_delete.DeleteAt" json:"is_soft_delete"`                                       // 是否删除0否1是
	Remarks           *string    `gorm:"column:remarks" json:"remarks"`                                                    // 备注
	ExpertKnowledgeID *string    `gorm:"column:expert_knowledge_id" json:"expert_knowledge_id"`                            // 知识id
	AlgorithmID       *string    `gorm:"column:algorithm_id" json:"algorithm_id"`                                          // 算法id
}

// TableName TaAlgorithmExpertKnowledge's table name
func (*TaAlgorithmExpertKnowledge) TableName() string {
	return TableNameTaAlgorithmExpertKnowledge
}
