// Code generated by gorm.io/gen. DO NOT EDIT.
// Code generated by gorm.io/gen. DO NOT EDIT.
// Code generated by gorm.io/gen. DO NOT EDIT.

package model

import (
	"time"
)

const TableNameTaExpertKnowledgeLibrary = "ta_expert_knowledge_library"

// TaExpertKnowledgeLibrary mapped from table <ta_expert_knowledge_library>
type TaExpertKnowledgeLibrary struct {
	ID             string     `gorm:"column:id;primaryKey" json:"id"`                                                   // 主键id
	Creator        *string    `gorm:"column:creator" json:"creator"`                                                    // 创建时间
	CreateDateTime *time.Time `gorm:"column:create_date_time;type:int unsigned;autoCreateTime" json:"create_date_time"` // 创建人
	Updater        *string    `gorm:"column:updater" json:"updater"`                                                    // 更新时间
	UpdateDateTime *time.Time `gorm:"column:update_date_time;type:int unsigned;autoUpdateTime" json:"update_date_time"` // 更新人
	IsSoftDelete   *int64     `gorm:"soft_delete.DeleteAt" json:"is_soft_delete"`                                       // 是否删除0否1是
	Remarks        *string    `gorm:"column:remarks" json:"remarks"`                                                    // 备注
	Value          *string    `gorm:"column:value" json:"value"`                                                        // value
	Key            *string    `gorm:"column:key" json:"key"`                                                            // value
	Name           *string    `gorm:"column:name" json:"name"`                                                          // 名称
	Describetion   *string    `gorm:"column:describetion" json:"describetion"`                                          // 描述
}

// TableName TaExpertKnowledgeLibrary's table name
func (*TaExpertKnowledgeLibrary) TableName() string {
	return TableNameTaExpertKnowledgeLibrary
}
