// Code generated by gorm.io/gen. DO NOT EDIT.
// Code generated by gorm.io/gen. DO NOT EDIT.
// Code generated by gorm.io/gen. DO NOT EDIT.

package model

import (
	"time"
)

const TableNameTaIntelligencelLibrary = "ta_intelligencel_library"

// TaIntelligencelLibrary mapped from table <ta_intelligencel_library>
type TaIntelligencelLibrary struct {
	ID             string     `gorm:"column:id;primaryKey" json:"id"`                                                   // 主键id
	Creator        *string    `gorm:"column:creator" json:"creator"`                                                    // 创建时间
	CreateDateTime *time.Time `gorm:"column:create_date_time;type:int unsigned;autoCreateTime" json:"create_date_time"` // 创建人
	Updater        *string    `gorm:"column:updater" json:"updater"`                                                    // 更新时间
	UpdateDateTime *time.Time `gorm:"column:update_date_time;type:int unsigned;autoUpdateTime" json:"update_date_time"` // 更新人
	IsSoftDelete   *int64     `gorm:"soft_delete.DeleteAt" json:"is_soft_delete"`                                       // 是否删除0否1是
	Remarks        *string    `gorm:"column:remarks" json:"remarks"`                                                    // 备注
	EName          *string    `gorm:"column:e_name" json:"e_name"`                                                      // 英文名称
	CName          *string    `gorm:"column:c_name" json:"c_name"`                                                      // 中文名称
	IsUse          *int64     `gorm:"column:is_use" json:"is_use"`                                                      // 是否启用
	Describetion   *string    `gorm:"column:describetion" json:"describetion"`                                          // 模型说明
	Version        *string    `gorm:"column:version" json:"version"`                                                    // 版本
	URLFileName    *string    `gorm:"column:url_file_name" json:"url_file_name"`                                        // url\文件名
}

// TableName TaIntelligencelLibrary's table name
func (*TaIntelligencelLibrary) TableName() string {
	return TableNameTaIntelligencelLibrary
}
