// Code generated by gorm.io/gen. DO NOT EDIT.
// Code generated by gorm.io/gen. DO NOT EDIT.
// Code generated by gorm.io/gen. DO NOT EDIT.

package model

import (
	"time"
)

const TableNameTaRulSimulationDatum = "ta_rul_simulation_data"

// TaRulSimulationDatum mapped from table <ta_rul_simulation_data>
type TaRulSimulationDatum struct {
	ID                string     `gorm:"column:id;primaryKey" json:"id"`                                                   // 主键id
	Creator           *string    `gorm:"column:creator" json:"creator"`                                                    // 创建时间
	CreateDateTime    *time.Time `gorm:"column:create_date_time;type:int unsigned;autoCreateTime" json:"create_date_time"` // 创建人
	Updater           *string    `gorm:"column:updater" json:"updater"`                                                    // 更新时间
	UpdateDateTime    *time.Time `gorm:"column:update_date_time;type:int unsigned;autoUpdateTime" json:"update_date_time"` // 更新人
	IsSoftDelete      *int64     `gorm:"soft_delete.DeleteAt" json:"is_soft_delete"`                                       // 是否删除0否1是
	Remarks           *string    `gorm:"column:remarks" json:"remarks"`                                                    // 备注
	Type              *int64     `gorm:"column:type" json:"type"`                                                          // 0算法模型演示1量化指标计算2历史数据复用
	RadarTypeID       *string    `gorm:"column:radar_type_id" json:"radar_type_id"`                                        // 雷达类型id
	RadarID           *string    `gorm:"column:radar_id" json:"radar_id"`                                                  // 雷达id
	DataSourceName    *string    `gorm:"column:data_source_name" json:"data_source_name"`                                  // 数据源名称
	StartDataTime     *time.Time `gorm:"column:start_data_time" json:"start_data_time"`                                    // 开始时间
	EndDataTime       *time.Time `gorm:"column:end_data_time" json:"end_data_time"`                                        // 结束时间
	State             *int64     `gorm:"column:state" json:"state"`                                                        // 状态（是否正在进行算法）
	RaKeyPartsModelID *string    `gorm:"column:ra_key_parts_model_id" json:"ra_key_parts_model_id"`                        // 寿命件
}

// TableName TaRulSimulationDatum's table name
func (*TaRulSimulationDatum) TableName() string {
	return TableNameTaRulSimulationDatum
}
