// Code generated by gorm.io/gen. DO NOT EDIT.
// Code generated by gorm.io/gen. DO NOT EDIT.
// Code generated by gorm.io/gen. DO NOT EDIT.

package model

import (
	"time"
)

const TableNameTaTask = "ta_task"

// TaTask mapped from table <ta_task>
type TaTask struct {
	ID               string     `gorm:"column:id;primaryKey" json:"id"`                                                   // 主键id
	Creator          *string    `gorm:"column:creator" json:"creator"`                                                    // 创建时间
	CreateDateTime   *time.Time `gorm:"column:create_date_time;type:int unsigned;autoCreateTime" json:"create_date_time"` // 创建人
	Updater          *string    `gorm:"column:updater" json:"updater"`                                                    // 更新时间
	UpdateDateTime   *time.Time `gorm:"column:update_date_time;type:int unsigned;autoUpdateTime" json:"update_date_time"` // 更新人
	IsSoftDelete     *int64     `gorm:"soft_delete.DeleteAt" json:"is_soft_delete"`                                       // 是否删除0否1是
	Remarks          *string    `gorm:"column:remarks" json:"remarks"`                                                    // 备注
	TypeID           *string    `gorm:"column:type_id" json:"type_id"`                                                    // 类别id
	TreeID           *string    `gorm:"column:tree_id" json:"tree_id"`                                                    // 结构id
	EndTime          *time.Time `gorm:"column:end_time" json:"end_time"`                                                  // 任务截止时间
	StartTime        *time.Time `gorm:"column:start_time" json:"start_time"`                                              // 任务开始时间
	AlgorithmModelID *string    `gorm:"column:algorithm_model_id" json:"algorithm_model_id"`                              // 算法模型id
	Describetion     *string    `gorm:"column:describetion" json:"describetion"`                                          // 描述
	Status           *int64     `gorm:"column:status" json:"status"`                                                      // 状态
	Cycle            *float32   `gorm:"column:cycle" json:"cycle"`                                                        // 任务周期
}

// TableName TaTask's table name
func (*TaTask) TableName() string {
	return TableNameTaTask
}
