// Code generated by protoc-gen-go-http. DO NOT EDIT.
// versions:
// - protoc-gen-go-http v2.9.0
// - protoc             v3.21.12
// source: api/chat/v1/chat.proto

package v1

import (
	context "context"
	http "github.com/go-kratos/kratos/v2/transport/http"
	binding "github.com/go-kratos/kratos/v2/transport/http/binding"
	emptypb "google.golang.org/protobuf/types/known/emptypb"
)

// This is a compile-time assertion to ensure that this generated file
// is compatible with the kratos package it is being compiled against.
var _ = new(context.Context)
var _ = binding.EncodeURL

const _ = http.SupportPackageIsVersion1

const OperationChatCreateMessage = "/chat.v1.Chat/CreateMessage"
const OperationChatCreateSession = "/chat.v1.Chat/CreateSession"
const OperationChatHistory = "/chat.v1.Chat/History"
const OperationChatHistoryById = "/chat.v1.Chat/HistoryById"
const OperationChatHistoryDeleteById = "/chat.v1.Chat/HistoryDeleteById"
const OperationChatHistoryRenameById = "/chat.v1.Chat/HistoryRenameById"

type ChatHTTPServer interface {
	// CreateMessage Create a new message in a session
	CreateMessage(context.Context, *CreateMessageRequest) (*Message, error)
	// CreateSession Create a new chat session
	CreateSession(context.Context, *CreateSessionRequest) (*HistorySession, error)
	// History History
	History(context.Context, *HistoryRequest) (*HistoryReply, error)
	// HistoryById history by id
	HistoryById(context.Context, *HistoryRequest) (*MessagesReply, error)
	// HistoryDeleteById delete history by id
	HistoryDeleteById(context.Context, *HistoryRequest) (*emptypb.Empty, error)
	// HistoryRenameById history rename by id
	HistoryRenameById(context.Context, *HistoryRequest) (*emptypb.Empty, error)
}

func RegisterChatHTTPServer(s *http.Server, srv ChatHTTPServer) {
	r := s.Route("/")
	r.GET("/chat/history", _Chat_History0_HTTP_Handler(srv))
	r.GET("/chat/history/{session_id}", _Chat_HistoryById0_HTTP_Handler(srv))
	r.PUT("/chat/history/{session_id}", _Chat_HistoryRenameById0_HTTP_Handler(srv))
	r.DELETE("/chat/history/{session_id}", _Chat_HistoryDeleteById0_HTTP_Handler(srv))
	r.POST("/chat/session", _Chat_CreateSession0_HTTP_Handler(srv))
	r.POST("/chat/message", _Chat_CreateMessage0_HTTP_Handler(srv))
}

func _Chat_History0_HTTP_Handler(srv ChatHTTPServer) func(ctx http.Context) error {
	return func(ctx http.Context) error {
		var in HistoryRequest
		if err := ctx.BindQuery(&in); err != nil {
			return err
		}
		http.SetOperation(ctx, OperationChatHistory)
		h := ctx.Middleware(func(ctx context.Context, req interface{}) (interface{}, error) {
			return srv.History(ctx, req.(*HistoryRequest))
		})
		out, err := h(ctx, &in)
		if err != nil {
			return err
		}
		reply := out.(*HistoryReply)
		return ctx.Result(200, reply)
	}
}

func _Chat_HistoryById0_HTTP_Handler(srv ChatHTTPServer) func(ctx http.Context) error {
	return func(ctx http.Context) error {
		var in HistoryRequest
		if err := ctx.BindQuery(&in); err != nil {
			return err
		}
		if err := ctx.BindVars(&in); err != nil {
			return err
		}
		http.SetOperation(ctx, OperationChatHistoryById)
		h := ctx.Middleware(func(ctx context.Context, req interface{}) (interface{}, error) {
			return srv.HistoryById(ctx, req.(*HistoryRequest))
		})
		out, err := h(ctx, &in)
		if err != nil {
			return err
		}
		reply := out.(*MessagesReply)
		return ctx.Result(200, reply)
	}
}

func _Chat_HistoryRenameById0_HTTP_Handler(srv ChatHTTPServer) func(ctx http.Context) error {
	return func(ctx http.Context) error {
		var in HistoryRequest
		if err := ctx.Bind(&in); err != nil {
			return err
		}
		if err := ctx.BindQuery(&in); err != nil {
			return err
		}
		if err := ctx.BindVars(&in); err != nil {
			return err
		}
		http.SetOperation(ctx, OperationChatHistoryRenameById)
		h := ctx.Middleware(func(ctx context.Context, req interface{}) (interface{}, error) {
			return srv.HistoryRenameById(ctx, req.(*HistoryRequest))
		})
		out, err := h(ctx, &in)
		if err != nil {
			return err
		}
		reply := out.(*emptypb.Empty)
		return ctx.Result(200, reply)
	}
}

func _Chat_HistoryDeleteById0_HTTP_Handler(srv ChatHTTPServer) func(ctx http.Context) error {
	return func(ctx http.Context) error {
		var in HistoryRequest
		if err := ctx.BindQuery(&in); err != nil {
			return err
		}
		if err := ctx.BindVars(&in); err != nil {
			return err
		}
		http.SetOperation(ctx, OperationChatHistoryDeleteById)
		h := ctx.Middleware(func(ctx context.Context, req interface{}) (interface{}, error) {
			return srv.HistoryDeleteById(ctx, req.(*HistoryRequest))
		})
		out, err := h(ctx, &in)
		if err != nil {
			return err
		}
		reply := out.(*emptypb.Empty)
		return ctx.Result(200, reply)
	}
}

func _Chat_CreateSession0_HTTP_Handler(srv ChatHTTPServer) func(ctx http.Context) error {
	return func(ctx http.Context) error {
		var in CreateSessionRequest
		if err := ctx.Bind(&in); err != nil {
			return err
		}
		if err := ctx.BindQuery(&in); err != nil {
			return err
		}
		http.SetOperation(ctx, OperationChatCreateSession)
		h := ctx.Middleware(func(ctx context.Context, req interface{}) (interface{}, error) {
			return srv.CreateSession(ctx, req.(*CreateSessionRequest))
		})
		out, err := h(ctx, &in)
		if err != nil {
			return err
		}
		reply := out.(*HistorySession)
		return ctx.Result(200, reply)
	}
}

func _Chat_CreateMessage0_HTTP_Handler(srv ChatHTTPServer) func(ctx http.Context) error {
	return func(ctx http.Context) error {
		var in CreateMessageRequest
		if err := ctx.Bind(&in); err != nil {
			return err
		}
		if err := ctx.BindQuery(&in); err != nil {
			return err
		}
		http.SetOperation(ctx, OperationChatCreateMessage)
		h := ctx.Middleware(func(ctx context.Context, req interface{}) (interface{}, error) {
			return srv.CreateMessage(ctx, req.(*CreateMessageRequest))
		})
		out, err := h(ctx, &in)
		if err != nil {
			return err
		}
		reply := out.(*Message)
		return ctx.Result(200, reply)
	}
}

type ChatHTTPClient interface {
	// CreateMessage Create a new message in a session
	CreateMessage(ctx context.Context, req *CreateMessageRequest, opts ...http.CallOption) (rsp *Message, err error)
	// CreateSession Create a new chat session
	CreateSession(ctx context.Context, req *CreateSessionRequest, opts ...http.CallOption) (rsp *HistorySession, err error)
	// History History
	History(ctx context.Context, req *HistoryRequest, opts ...http.CallOption) (rsp *HistoryReply, err error)
	// HistoryById history by id
	HistoryById(ctx context.Context, req *HistoryRequest, opts ...http.CallOption) (rsp *MessagesReply, err error)
	// HistoryDeleteById delete history by id
	HistoryDeleteById(ctx context.Context, req *HistoryRequest, opts ...http.CallOption) (rsp *emptypb.Empty, err error)
	// HistoryRenameById history rename by id
	HistoryRenameById(ctx context.Context, req *HistoryRequest, opts ...http.CallOption) (rsp *emptypb.Empty, err error)
}

type ChatHTTPClientImpl struct {
	cc *http.Client
}

func NewChatHTTPClient(client *http.Client) ChatHTTPClient {
	return &ChatHTTPClientImpl{client}
}

// CreateMessage Create a new message in a session
func (c *ChatHTTPClientImpl) CreateMessage(ctx context.Context, in *CreateMessageRequest, opts ...http.CallOption) (*Message, error) {
	var out Message
	pattern := "/chat/message"
	path := binding.EncodeURL(pattern, in, false)
	opts = append(opts, http.Operation(OperationChatCreateMessage))
	opts = append(opts, http.PathTemplate(pattern))
	err := c.cc.Invoke(ctx, "POST", path, in, &out, opts...)
	if err != nil {
		return nil, err
	}
	return &out, nil
}

// CreateSession Create a new chat session
func (c *ChatHTTPClientImpl) CreateSession(ctx context.Context, in *CreateSessionRequest, opts ...http.CallOption) (*HistorySession, error) {
	var out HistorySession
	pattern := "/chat/session"
	path := binding.EncodeURL(pattern, in, false)
	opts = append(opts, http.Operation(OperationChatCreateSession))
	opts = append(opts, http.PathTemplate(pattern))
	err := c.cc.Invoke(ctx, "POST", path, in, &out, opts...)
	if err != nil {
		return nil, err
	}
	return &out, nil
}

// History History
func (c *ChatHTTPClientImpl) History(ctx context.Context, in *HistoryRequest, opts ...http.CallOption) (*HistoryReply, error) {
	var out HistoryReply
	pattern := "/chat/history"
	path := binding.EncodeURL(pattern, in, true)
	opts = append(opts, http.Operation(OperationChatHistory))
	opts = append(opts, http.PathTemplate(pattern))
	err := c.cc.Invoke(ctx, "GET", path, nil, &out, opts...)
	if err != nil {
		return nil, err
	}
	return &out, nil
}

// HistoryById history by id
func (c *ChatHTTPClientImpl) HistoryById(ctx context.Context, in *HistoryRequest, opts ...http.CallOption) (*MessagesReply, error) {
	var out MessagesReply
	pattern := "/chat/history/{session_id}"
	path := binding.EncodeURL(pattern, in, true)
	opts = append(opts, http.Operation(OperationChatHistoryById))
	opts = append(opts, http.PathTemplate(pattern))
	err := c.cc.Invoke(ctx, "GET", path, nil, &out, opts...)
	if err != nil {
		return nil, err
	}
	return &out, nil
}

// HistoryDeleteById delete history by id
func (c *ChatHTTPClientImpl) HistoryDeleteById(ctx context.Context, in *HistoryRequest, opts ...http.CallOption) (*emptypb.Empty, error) {
	var out emptypb.Empty
	pattern := "/chat/history/{session_id}"
	path := binding.EncodeURL(pattern, in, true)
	opts = append(opts, http.Operation(OperationChatHistoryDeleteById))
	opts = append(opts, http.PathTemplate(pattern))
	err := c.cc.Invoke(ctx, "DELETE", path, nil, &out, opts...)
	if err != nil {
		return nil, err
	}
	return &out, nil
}

// HistoryRenameById history rename by id
func (c *ChatHTTPClientImpl) HistoryRenameById(ctx context.Context, in *HistoryRequest, opts ...http.CallOption) (*emptypb.Empty, error) {
	var out emptypb.Empty
	pattern := "/chat/history/{session_id}"
	path := binding.EncodeURL(pattern, in, false)
	opts = append(opts, http.Operation(OperationChatHistoryRenameById))
	opts = append(opts, http.PathTemplate(pattern))
	err := c.cc.Invoke(ctx, "PUT", path, in, &out, opts...)
	if err != nil {
		return nil, err
	}
	return &out, nil
}
