// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.10
// 	protoc        v3.21.12
// source: api/chat/v1/chat.proto

package v1

import (
	_ "google.golang.org/genproto/googleapis/api/annotations"
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

// Request for sending a message
type SendMessageRequest struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// // 用户输入的内容
	// string content = 1;
	// // 用户唯一标识符
	// string user_id = 2;
	// // 会话唯一标识符
	// string session_id = 3;
	// 最大生成令牌数
	MaxTokens int32 `protobuf:"varint,4,opt,name=max_tokens,json=maxTokens,proto3" json:"max_tokens,omitempty"`
	// 使用的AI模型名称
	Model string `protobuf:"bytes,5,opt,name=model,proto3" json:"model,omitempty"`
	// 控制生成文本随机性的参数，值越高结果越随机
	Temperature float32 `protobuf:"fixed32,6,opt,name=temperature,proto3" json:"temperature,omitempty"`
	// 控制生成文本多样性的参数，0-1之间
	TopP float32 `protobuf:"fixed32,7,opt,name=top_p,json=topP,proto3" json:"top_p,omitempty"`
	// 存在惩罚因子，防止重复话题
	PresencePenalty float32 `protobuf:"fixed32,8,opt,name=presence_penalty,json=presencePenalty,proto3" json:"presence_penalty,omitempty"`
	// 频率惩罚因子，防止重复词汇
	FrequencyPenalty float32 `protobuf:"fixed32,9,opt,name=frequency_penalty,json=frequencyPenalty,proto3" json:"frequency_penalty,omitempty"`
	// 聊天历史记录消息列表
	Messages []*Message `protobuf:"bytes,10,rep,name=messages,proto3" json:"messages,omitempty"`
	// 是否启用流式响应
	Stream bool `protobuf:"varint,11,opt,name=stream,proto3" json:"stream,omitempty"`
	// 密钥标识符
	Kid string `protobuf:"bytes,12,opt,name=kid,proto3" json:"kid,omitempty"`
	// 应用程序标识符
	AppId string `protobuf:"bytes,13,opt,name=app_id,json=appId,proto3" json:"app_id,omitempty"`
	// 是否包含附件
	HasAttachment bool `protobuf:"varint,14,opt,name=has_attachment,json=hasAttachment,proto3" json:"has_attachment,omitempty"`
	// 是否自动选择模型
	AutoSelectModel bool `protobuf:"varint,15,opt,name=auto_select_model,json=autoSelectModel,proto3" json:"auto_select_model,omitempty"`
	unknownFields   protoimpl.UnknownFields
	sizeCache       protoimpl.SizeCache
}

func (x *SendMessageRequest) Reset() {
	*x = SendMessageRequest{}
	mi := &file_api_chat_v1_chat_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *SendMessageRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*SendMessageRequest) ProtoMessage() {}

func (x *SendMessageRequest) ProtoReflect() protoreflect.Message {
	mi := &file_api_chat_v1_chat_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use SendMessageRequest.ProtoReflect.Descriptor instead.
func (*SendMessageRequest) Descriptor() ([]byte, []int) {
	return file_api_chat_v1_chat_proto_rawDescGZIP(), []int{0}
}

func (x *SendMessageRequest) GetMaxTokens() int32 {
	if x != nil {
		return x.MaxTokens
	}
	return 0
}

func (x *SendMessageRequest) GetModel() string {
	if x != nil {
		return x.Model
	}
	return ""
}

func (x *SendMessageRequest) GetTemperature() float32 {
	if x != nil {
		return x.Temperature
	}
	return 0
}

func (x *SendMessageRequest) GetTopP() float32 {
	if x != nil {
		return x.TopP
	}
	return 0
}

func (x *SendMessageRequest) GetPresencePenalty() float32 {
	if x != nil {
		return x.PresencePenalty
	}
	return 0
}

func (x *SendMessageRequest) GetFrequencyPenalty() float32 {
	if x != nil {
		return x.FrequencyPenalty
	}
	return 0
}

func (x *SendMessageRequest) GetMessages() []*Message {
	if x != nil {
		return x.Messages
	}
	return nil
}

func (x *SendMessageRequest) GetStream() bool {
	if x != nil {
		return x.Stream
	}
	return false
}

func (x *SendMessageRequest) GetKid() string {
	if x != nil {
		return x.Kid
	}
	return ""
}

func (x *SendMessageRequest) GetAppId() string {
	if x != nil {
		return x.AppId
	}
	return ""
}

func (x *SendMessageRequest) GetHasAttachment() bool {
	if x != nil {
		return x.HasAttachment
	}
	return false
}

func (x *SendMessageRequest) GetAutoSelectModel() bool {
	if x != nil {
		return x.AutoSelectModel
	}
	return false
}

// Message structure for chat history
type Message struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// 消息发送者角色 ("system", "user", "assistant")
	Role string `protobuf:"bytes,1,opt,name=role,proto3" json:"role,omitempty"`
	// 消息内容
	Content       string `protobuf:"bytes,2,opt,name=content,proto3" json:"content,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *Message) Reset() {
	*x = Message{}
	mi := &file_api_chat_v1_chat_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Message) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Message) ProtoMessage() {}

func (x *Message) ProtoReflect() protoreflect.Message {
	mi := &file_api_chat_v1_chat_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Message.ProtoReflect.Descriptor instead.
func (*Message) Descriptor() ([]byte, []int) {
	return file_api_chat_v1_chat_proto_rawDescGZIP(), []int{1}
}

func (x *Message) GetRole() string {
	if x != nil {
		return x.Role
	}
	return ""
}

func (x *Message) GetContent() string {
	if x != nil {
		return x.Content
	}
	return ""
}

// Reply for sending a message
type SendMessageReply struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	MessageId     string                 `protobuf:"bytes,1,opt,name=message_id,json=messageId,proto3" json:"message_id,omitempty"`
	Success       bool                   `protobuf:"varint,2,opt,name=success,proto3" json:"success,omitempty"`
	ErrorMessage  string                 `protobuf:"bytes,3,opt,name=error_message,json=errorMessage,proto3" json:"error_message,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *SendMessageReply) Reset() {
	*x = SendMessageReply{}
	mi := &file_api_chat_v1_chat_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *SendMessageReply) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*SendMessageReply) ProtoMessage() {}

func (x *SendMessageReply) ProtoReflect() protoreflect.Message {
	mi := &file_api_chat_v1_chat_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use SendMessageReply.ProtoReflect.Descriptor instead.
func (*SendMessageReply) Descriptor() ([]byte, []int) {
	return file_api_chat_v1_chat_proto_rawDescGZIP(), []int{2}
}

func (x *SendMessageReply) GetMessageId() string {
	if x != nil {
		return x.MessageId
	}
	return ""
}

func (x *SendMessageReply) GetSuccess() bool {
	if x != nil {
		return x.Success
	}
	return false
}

func (x *SendMessageReply) GetErrorMessage() string {
	if x != nil {
		return x.ErrorMessage
	}
	return ""
}

// Request for getting messages
type GetMessagesRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	SessionId     string                 `protobuf:"bytes,1,opt,name=session_id,json=sessionId,proto3" json:"session_id,omitempty"`
	Page          int32                  `protobuf:"varint,2,opt,name=page,proto3" json:"page,omitempty"`
	PageSize      int32                  `protobuf:"varint,3,opt,name=page_size,json=pageSize,proto3" json:"page_size,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetMessagesRequest) Reset() {
	*x = GetMessagesRequest{}
	mi := &file_api_chat_v1_chat_proto_msgTypes[3]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetMessagesRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetMessagesRequest) ProtoMessage() {}

func (x *GetMessagesRequest) ProtoReflect() protoreflect.Message {
	mi := &file_api_chat_v1_chat_proto_msgTypes[3]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetMessagesRequest.ProtoReflect.Descriptor instead.
func (*GetMessagesRequest) Descriptor() ([]byte, []int) {
	return file_api_chat_v1_chat_proto_rawDescGZIP(), []int{3}
}

func (x *GetMessagesRequest) GetSessionId() string {
	if x != nil {
		return x.SessionId
	}
	return ""
}

func (x *GetMessagesRequest) GetPage() int32 {
	if x != nil {
		return x.Page
	}
	return 0
}

func (x *GetMessagesRequest) GetPageSize() int32 {
	if x != nil {
		return x.PageSize
	}
	return 0
}

// Reply for getting messages
type GetMessagesReply struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Messages      []*ChatMessage         `protobuf:"bytes,1,rep,name=messages,proto3" json:"messages,omitempty"`
	Total         int32                  `protobuf:"varint,2,opt,name=total,proto3" json:"total,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetMessagesReply) Reset() {
	*x = GetMessagesReply{}
	mi := &file_api_chat_v1_chat_proto_msgTypes[4]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetMessagesReply) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetMessagesReply) ProtoMessage() {}

func (x *GetMessagesReply) ProtoReflect() protoreflect.Message {
	mi := &file_api_chat_v1_chat_proto_msgTypes[4]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetMessagesReply.ProtoReflect.Descriptor instead.
func (*GetMessagesReply) Descriptor() ([]byte, []int) {
	return file_api_chat_v1_chat_proto_rawDescGZIP(), []int{4}
}

func (x *GetMessagesReply) GetMessages() []*ChatMessage {
	if x != nil {
		return x.Messages
	}
	return nil
}

func (x *GetMessagesReply) GetTotal() int32 {
	if x != nil {
		return x.Total
	}
	return 0
}

// Request for streaming messages
type StreamMessagesRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	SessionId     string                 `protobuf:"bytes,1,opt,name=session_id,json=sessionId,proto3" json:"session_id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *StreamMessagesRequest) Reset() {
	*x = StreamMessagesRequest{}
	mi := &file_api_chat_v1_chat_proto_msgTypes[5]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *StreamMessagesRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*StreamMessagesRequest) ProtoMessage() {}

func (x *StreamMessagesRequest) ProtoReflect() protoreflect.Message {
	mi := &file_api_chat_v1_chat_proto_msgTypes[5]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use StreamMessagesRequest.ProtoReflect.Descriptor instead.
func (*StreamMessagesRequest) Descriptor() ([]byte, []int) {
	return file_api_chat_v1_chat_proto_rawDescGZIP(), []int{5}
}

func (x *StreamMessagesRequest) GetSessionId() string {
	if x != nil {
		return x.SessionId
	}
	return ""
}

// Reply for streaming messages
type StreamMessagesReply struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Message       *ChatMessage           `protobuf:"bytes,1,opt,name=message,proto3" json:"message,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *StreamMessagesReply) Reset() {
	*x = StreamMessagesReply{}
	mi := &file_api_chat_v1_chat_proto_msgTypes[6]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *StreamMessagesReply) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*StreamMessagesReply) ProtoMessage() {}

func (x *StreamMessagesReply) ProtoReflect() protoreflect.Message {
	mi := &file_api_chat_v1_chat_proto_msgTypes[6]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use StreamMessagesReply.ProtoReflect.Descriptor instead.
func (*StreamMessagesReply) Descriptor() ([]byte, []int) {
	return file_api_chat_v1_chat_proto_rawDescGZIP(), []int{6}
}

func (x *StreamMessagesReply) GetMessage() *ChatMessage {
	if x != nil {
		return x.Message
	}
	return nil
}

// Chat message structure
type ChatMessage struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Id            string                 `protobuf:"bytes,1,opt,name=id,proto3" json:"id,omitempty"`
	Content       string                 `protobuf:"bytes,2,opt,name=content,proto3" json:"content,omitempty"`
	UserId        string                 `protobuf:"bytes,3,opt,name=user_id,json=userId,proto3" json:"user_id,omitempty"`
	SessionId     string                 `protobuf:"bytes,4,opt,name=session_id,json=sessionId,proto3" json:"session_id,omitempty"`
	Timestamp     string                 `protobuf:"bytes,5,opt,name=timestamp,proto3" json:"timestamp,omitempty"`
	Type          string                 `protobuf:"bytes,6,opt,name=type,proto3" json:"type,omitempty"` // e.g., "user", "assistant"
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ChatMessage) Reset() {
	*x = ChatMessage{}
	mi := &file_api_chat_v1_chat_proto_msgTypes[7]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ChatMessage) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ChatMessage) ProtoMessage() {}

func (x *ChatMessage) ProtoReflect() protoreflect.Message {
	mi := &file_api_chat_v1_chat_proto_msgTypes[7]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ChatMessage.ProtoReflect.Descriptor instead.
func (*ChatMessage) Descriptor() ([]byte, []int) {
	return file_api_chat_v1_chat_proto_rawDescGZIP(), []int{7}
}

func (x *ChatMessage) GetId() string {
	if x != nil {
		return x.Id
	}
	return ""
}

func (x *ChatMessage) GetContent() string {
	if x != nil {
		return x.Content
	}
	return ""
}

func (x *ChatMessage) GetUserId() string {
	if x != nil {
		return x.UserId
	}
	return ""
}

func (x *ChatMessage) GetSessionId() string {
	if x != nil {
		return x.SessionId
	}
	return ""
}

func (x *ChatMessage) GetTimestamp() string {
	if x != nil {
		return x.Timestamp
	}
	return ""
}

func (x *ChatMessage) GetType() string {
	if x != nil {
		return x.Type
	}
	return ""
}

var File_api_chat_v1_chat_proto protoreflect.FileDescriptor

const file_api_chat_v1_chat_proto_rawDesc = "" +
	"\n" +
	"\x16api/chat/v1/chat.proto\x12\achat.v1\x1a\x1cgoogle/api/annotations.proto\"\x9a\x03\n" +
	"\x12SendMessageRequest\x12\x1d\n" +
	"\n" +
	"max_tokens\x18\x04 \x01(\x05R\tmaxTokens\x12\x14\n" +
	"\x05model\x18\x05 \x01(\tR\x05model\x12 \n" +
	"\vtemperature\x18\x06 \x01(\x02R\vtemperature\x12\x13\n" +
	"\x05top_p\x18\a \x01(\x02R\x04topP\x12)\n" +
	"\x10presence_penalty\x18\b \x01(\x02R\x0fpresencePenalty\x12+\n" +
	"\x11frequency_penalty\x18\t \x01(\x02R\x10frequencyPenalty\x12,\n" +
	"\bmessages\x18\n" +
	" \x03(\v2\x10.chat.v1.MessageR\bmessages\x12\x16\n" +
	"\x06stream\x18\v \x01(\bR\x06stream\x12\x10\n" +
	"\x03kid\x18\f \x01(\tR\x03kid\x12\x15\n" +
	"\x06app_id\x18\r \x01(\tR\x05appId\x12%\n" +
	"\x0ehas_attachment\x18\x0e \x01(\bR\rhasAttachment\x12*\n" +
	"\x11auto_select_model\x18\x0f \x01(\bR\x0fautoSelectModel\"7\n" +
	"\aMessage\x12\x12\n" +
	"\x04role\x18\x01 \x01(\tR\x04role\x12\x18\n" +
	"\acontent\x18\x02 \x01(\tR\acontent\"p\n" +
	"\x10SendMessageReply\x12\x1d\n" +
	"\n" +
	"message_id\x18\x01 \x01(\tR\tmessageId\x12\x18\n" +
	"\asuccess\x18\x02 \x01(\bR\asuccess\x12#\n" +
	"\rerror_message\x18\x03 \x01(\tR\ferrorMessage\"d\n" +
	"\x12GetMessagesRequest\x12\x1d\n" +
	"\n" +
	"session_id\x18\x01 \x01(\tR\tsessionId\x12\x12\n" +
	"\x04page\x18\x02 \x01(\x05R\x04page\x12\x1b\n" +
	"\tpage_size\x18\x03 \x01(\x05R\bpageSize\"Z\n" +
	"\x10GetMessagesReply\x120\n" +
	"\bmessages\x18\x01 \x03(\v2\x14.chat.v1.ChatMessageR\bmessages\x12\x14\n" +
	"\x05total\x18\x02 \x01(\x05R\x05total\"6\n" +
	"\x15StreamMessagesRequest\x12\x1d\n" +
	"\n" +
	"session_id\x18\x01 \x01(\tR\tsessionId\"E\n" +
	"\x13StreamMessagesReply\x12.\n" +
	"\amessage\x18\x01 \x01(\v2\x14.chat.v1.ChatMessageR\amessage\"\xa1\x01\n" +
	"\vChatMessage\x12\x0e\n" +
	"\x02id\x18\x01 \x01(\tR\x02id\x12\x18\n" +
	"\acontent\x18\x02 \x01(\tR\acontent\x12\x17\n" +
	"\auser_id\x18\x03 \x01(\tR\x06userId\x12\x1d\n" +
	"\n" +
	"session_id\x18\x04 \x01(\tR\tsessionId\x12\x1c\n" +
	"\ttimestamp\x18\x05 \x01(\tR\ttimestamp\x12\x12\n" +
	"\x04type\x18\x06 \x01(\tR\x04type2\xae\x02\n" +
	"\x04Chat\x12[\n" +
	"\vSendMessage\x12\x1b.chat.v1.SendMessageRequest\x1a\x19.chat.v1.SendMessageReply\"\x14\x82\xd3\xe4\x93\x02\x0e:\x01*\"\t/chat/msg\x12`\n" +
	"\vGetMessages\x12\x1b.chat.v1.GetMessagesRequest\x1a\x19.chat.v1.GetMessagesReply\"\x19\x82\xd3\xe4\x93\x02\x13\x12\x11/v1/chat/messages\x12g\n" +
	"\x0eStreamMessages\x12\x1e.chat.v1.StreamMessagesRequest\x1a\x1c.chat.v1.StreamMessagesReply\"\x15\x82\xd3\xe4\x93\x02\x0f:\x01*\"\n" +
	"/chat/send0\x01B?\n" +
	"\x16dev.kratos.api.chat.v1B\vChatProtoV1P\x01Z\x16backend/api/chat/v1;v1b\x06proto3"

var (
	file_api_chat_v1_chat_proto_rawDescOnce sync.Once
	file_api_chat_v1_chat_proto_rawDescData []byte
)

func file_api_chat_v1_chat_proto_rawDescGZIP() []byte {
	file_api_chat_v1_chat_proto_rawDescOnce.Do(func() {
		file_api_chat_v1_chat_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_api_chat_v1_chat_proto_rawDesc), len(file_api_chat_v1_chat_proto_rawDesc)))
	})
	return file_api_chat_v1_chat_proto_rawDescData
}

var file_api_chat_v1_chat_proto_msgTypes = make([]protoimpl.MessageInfo, 8)
var file_api_chat_v1_chat_proto_goTypes = []any{
	(*SendMessageRequest)(nil),    // 0: chat.v1.SendMessageRequest
	(*Message)(nil),               // 1: chat.v1.Message
	(*SendMessageReply)(nil),      // 2: chat.v1.SendMessageReply
	(*GetMessagesRequest)(nil),    // 3: chat.v1.GetMessagesRequest
	(*GetMessagesReply)(nil),      // 4: chat.v1.GetMessagesReply
	(*StreamMessagesRequest)(nil), // 5: chat.v1.StreamMessagesRequest
	(*StreamMessagesReply)(nil),   // 6: chat.v1.StreamMessagesReply
	(*ChatMessage)(nil),           // 7: chat.v1.ChatMessage
}
var file_api_chat_v1_chat_proto_depIdxs = []int32{
	1, // 0: chat.v1.SendMessageRequest.messages:type_name -> chat.v1.Message
	7, // 1: chat.v1.GetMessagesReply.messages:type_name -> chat.v1.ChatMessage
	7, // 2: chat.v1.StreamMessagesReply.message:type_name -> chat.v1.ChatMessage
	0, // 3: chat.v1.Chat.SendMessage:input_type -> chat.v1.SendMessageRequest
	3, // 4: chat.v1.Chat.GetMessages:input_type -> chat.v1.GetMessagesRequest
	5, // 5: chat.v1.Chat.StreamMessages:input_type -> chat.v1.StreamMessagesRequest
	2, // 6: chat.v1.Chat.SendMessage:output_type -> chat.v1.SendMessageReply
	4, // 7: chat.v1.Chat.GetMessages:output_type -> chat.v1.GetMessagesReply
	6, // 8: chat.v1.Chat.StreamMessages:output_type -> chat.v1.StreamMessagesReply
	6, // [6:9] is the sub-list for method output_type
	3, // [3:6] is the sub-list for method input_type
	3, // [3:3] is the sub-list for extension type_name
	3, // [3:3] is the sub-list for extension extendee
	0, // [0:3] is the sub-list for field type_name
}

func init() { file_api_chat_v1_chat_proto_init() }
func file_api_chat_v1_chat_proto_init() {
	if File_api_chat_v1_chat_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_api_chat_v1_chat_proto_rawDesc), len(file_api_chat_v1_chat_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   8,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_api_chat_v1_chat_proto_goTypes,
		DependencyIndexes: file_api_chat_v1_chat_proto_depIdxs,
		MessageInfos:      file_api_chat_v1_chat_proto_msgTypes,
	}.Build()
	File_api_chat_v1_chat_proto = out.File
	file_api_chat_v1_chat_proto_goTypes = nil
	file_api_chat_v1_chat_proto_depIdxs = nil
}
