// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.10
// 	protoc        v3.21.12
// source: api/base/system.proto

package base

import (
	_ "google.golang.org/genproto/googleapis/api/annotations"
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	emptypb "google.golang.org/protobuf/types/known/emptypb"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type MenuReply struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Menu          []*Menu                `protobuf:"bytes,1,rep,name=menu,proto3" json:"menu,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *MenuReply) Reset() {
	*x = MenuReply{}
	mi := &file_api_base_system_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *MenuReply) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*MenuReply) ProtoMessage() {}

func (x *MenuReply) ProtoReflect() protoreflect.Message {
	mi := &file_api_base_system_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use MenuReply.ProtoReflect.Descriptor instead.
func (*MenuReply) Descriptor() ([]byte, []int) {
	return file_api_base_system_proto_rawDescGZIP(), []int{0}
}

func (x *MenuReply) GetMenu() []*Menu {
	if x != nil {
		return x.Menu
	}
	return nil
}

type MenuMeta struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Icon          string                 `protobuf:"bytes,1,opt,name=icon,proto3" json:"icon,omitempty"`
	Link          string                 `protobuf:"bytes,2,opt,name=link,proto3" json:"link,omitempty"`
	NoCache       bool                   `protobuf:"varint,3,opt,name=noCache,proto3" json:"noCache,omitempty"`
	Title         string                 `protobuf:"bytes,4,opt,name=title,proto3" json:"title,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *MenuMeta) Reset() {
	*x = MenuMeta{}
	mi := &file_api_base_system_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *MenuMeta) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*MenuMeta) ProtoMessage() {}

func (x *MenuMeta) ProtoReflect() protoreflect.Message {
	mi := &file_api_base_system_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use MenuMeta.ProtoReflect.Descriptor instead.
func (*MenuMeta) Descriptor() ([]byte, []int) {
	return file_api_base_system_proto_rawDescGZIP(), []int{1}
}

func (x *MenuMeta) GetIcon() string {
	if x != nil {
		return x.Icon
	}
	return ""
}

func (x *MenuMeta) GetLink() string {
	if x != nil {
		return x.Link
	}
	return ""
}

func (x *MenuMeta) GetNoCache() bool {
	if x != nil {
		return x.NoCache
	}
	return false
}

func (x *MenuMeta) GetTitle() string {
	if x != nil {
		return x.Title
	}
	return ""
}

type Menu struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	AlwaysShow    bool                   `protobuf:"varint,1,opt,name=alwaysShow,proto3" json:"alwaysShow,omitempty"`
	Children      []*Menu                `protobuf:"bytes,2,rep,name=children,proto3" json:"children,omitempty"`
	Component     string                 `protobuf:"bytes,3,opt,name=component,proto3" json:"component,omitempty"`
	Hidden        bool                   `protobuf:"varint,4,opt,name=hidden,proto3" json:"hidden,omitempty"`
	Meta          *MenuMeta              `protobuf:"bytes,5,opt,name=meta,proto3" json:"meta,omitempty"`
	Name          string                 `protobuf:"bytes,6,opt,name=name,proto3" json:"name,omitempty"`
	Path          string                 `protobuf:"bytes,7,opt,name=path,proto3" json:"path,omitempty"`
	Query         string                 `protobuf:"bytes,8,opt,name=query,proto3" json:"query,omitempty"`
	Redirect      string                 `protobuf:"bytes,9,opt,name=redirect,proto3" json:"redirect,omitempty"`
	Id            int64                  `protobuf:"varint,10,opt,name=id,proto3" json:"id,omitempty"`
	ParentID      int64                  `protobuf:"varint,11,opt,name=parentID,proto3" json:"parentID,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *Menu) Reset() {
	*x = Menu{}
	mi := &file_api_base_system_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Menu) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Menu) ProtoMessage() {}

func (x *Menu) ProtoReflect() protoreflect.Message {
	mi := &file_api_base_system_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Menu.ProtoReflect.Descriptor instead.
func (*Menu) Descriptor() ([]byte, []int) {
	return file_api_base_system_proto_rawDescGZIP(), []int{2}
}

func (x *Menu) GetAlwaysShow() bool {
	if x != nil {
		return x.AlwaysShow
	}
	return false
}

func (x *Menu) GetChildren() []*Menu {
	if x != nil {
		return x.Children
	}
	return nil
}

func (x *Menu) GetComponent() string {
	if x != nil {
		return x.Component
	}
	return ""
}

func (x *Menu) GetHidden() bool {
	if x != nil {
		return x.Hidden
	}
	return false
}

func (x *Menu) GetMeta() *MenuMeta {
	if x != nil {
		return x.Meta
	}
	return nil
}

func (x *Menu) GetName() string {
	if x != nil {
		return x.Name
	}
	return ""
}

func (x *Menu) GetPath() string {
	if x != nil {
		return x.Path
	}
	return ""
}

func (x *Menu) GetQuery() string {
	if x != nil {
		return x.Query
	}
	return ""
}

func (x *Menu) GetRedirect() string {
	if x != nil {
		return x.Redirect
	}
	return ""
}

func (x *Menu) GetId() int64 {
	if x != nil {
		return x.Id
	}
	return 0
}

func (x *Menu) GetParentID() int64 {
	if x != nil {
		return x.ParentID
	}
	return 0
}

type AddSysMenuRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	MenuId        int64                  `protobuf:"varint,1,opt,name=menuId,proto3" json:"menuId,omitempty"`
	MenuName      string                 `protobuf:"bytes,2,opt,name=menuName,proto3" json:"menuName,omitempty"`
	ParentName    string                 `protobuf:"bytes,3,opt,name=parentName,proto3" json:"parentName,omitempty"`
	ParentId      int64                  `protobuf:"varint,4,opt,name=parentId,proto3" json:"parentId,omitempty"`
	OrderNum      int32                  `protobuf:"varint,5,opt,name=orderNum,proto3" json:"orderNum,omitempty"`
	Path          string                 `protobuf:"bytes,6,opt,name=path,proto3" json:"path,omitempty"`
	Component     string                 `protobuf:"bytes,7,opt,name=component,proto3" json:"component,omitempty"`
	Query         string                 `protobuf:"bytes,8,opt,name=query,proto3" json:"query,omitempty"`
	IsFrame       string                 `protobuf:"bytes,9,opt,name=isFrame,proto3" json:"isFrame,omitempty"`
	IsCache       string                 `protobuf:"bytes,10,opt,name=isCache,proto3" json:"isCache,omitempty"`
	MenuType      string                 `protobuf:"bytes,11,opt,name=menuType,proto3" json:"menuType,omitempty"`
	Visible       string                 `protobuf:"bytes,12,opt,name=visible,proto3" json:"visible,omitempty"`
	Status        string                 `protobuf:"bytes,13,opt,name=status,proto3" json:"status,omitempty"`
	Perms         string                 `protobuf:"bytes,14,opt,name=perms,proto3" json:"perms,omitempty"`
	Icon          string                 `protobuf:"bytes,15,opt,name=icon,proto3" json:"icon,omitempty"`
	Children      []*MenuItem            `protobuf:"bytes,16,rep,name=children,proto3" json:"children,omitempty"`
	CreateTime    string                 `protobuf:"bytes,17,opt,name=createTime,proto3" json:"createTime,omitempty"`
	UpdateTime    string                 `protobuf:"bytes,18,opt,name=updateTime,proto3" json:"updateTime,omitempty"`
	CreateBy      string                 `protobuf:"bytes,19,opt,name=createBy,proto3" json:"createBy,omitempty"`
	UpdateBy      string                 `protobuf:"bytes,20,opt,name=updateBy,proto3" json:"updateBy,omitempty"`
	Remark        string                 `protobuf:"bytes,21,opt,name=remark,proto3" json:"remark,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *AddSysMenuRequest) Reset() {
	*x = AddSysMenuRequest{}
	mi := &file_api_base_system_proto_msgTypes[3]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *AddSysMenuRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*AddSysMenuRequest) ProtoMessage() {}

func (x *AddSysMenuRequest) ProtoReflect() protoreflect.Message {
	mi := &file_api_base_system_proto_msgTypes[3]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use AddSysMenuRequest.ProtoReflect.Descriptor instead.
func (*AddSysMenuRequest) Descriptor() ([]byte, []int) {
	return file_api_base_system_proto_rawDescGZIP(), []int{3}
}

func (x *AddSysMenuRequest) GetMenuId() int64 {
	if x != nil {
		return x.MenuId
	}
	return 0
}

func (x *AddSysMenuRequest) GetMenuName() string {
	if x != nil {
		return x.MenuName
	}
	return ""
}

func (x *AddSysMenuRequest) GetParentName() string {
	if x != nil {
		return x.ParentName
	}
	return ""
}

func (x *AddSysMenuRequest) GetParentId() int64 {
	if x != nil {
		return x.ParentId
	}
	return 0
}

func (x *AddSysMenuRequest) GetOrderNum() int32 {
	if x != nil {
		return x.OrderNum
	}
	return 0
}

func (x *AddSysMenuRequest) GetPath() string {
	if x != nil {
		return x.Path
	}
	return ""
}

func (x *AddSysMenuRequest) GetComponent() string {
	if x != nil {
		return x.Component
	}
	return ""
}

func (x *AddSysMenuRequest) GetQuery() string {
	if x != nil {
		return x.Query
	}
	return ""
}

func (x *AddSysMenuRequest) GetIsFrame() string {
	if x != nil {
		return x.IsFrame
	}
	return ""
}

func (x *AddSysMenuRequest) GetIsCache() string {
	if x != nil {
		return x.IsCache
	}
	return ""
}

func (x *AddSysMenuRequest) GetMenuType() string {
	if x != nil {
		return x.MenuType
	}
	return ""
}

func (x *AddSysMenuRequest) GetVisible() string {
	if x != nil {
		return x.Visible
	}
	return ""
}

func (x *AddSysMenuRequest) GetStatus() string {
	if x != nil {
		return x.Status
	}
	return ""
}

func (x *AddSysMenuRequest) GetPerms() string {
	if x != nil {
		return x.Perms
	}
	return ""
}

func (x *AddSysMenuRequest) GetIcon() string {
	if x != nil {
		return x.Icon
	}
	return ""
}

func (x *AddSysMenuRequest) GetChildren() []*MenuItem {
	if x != nil {
		return x.Children
	}
	return nil
}

func (x *AddSysMenuRequest) GetCreateTime() string {
	if x != nil {
		return x.CreateTime
	}
	return ""
}

func (x *AddSysMenuRequest) GetUpdateTime() string {
	if x != nil {
		return x.UpdateTime
	}
	return ""
}

func (x *AddSysMenuRequest) GetCreateBy() string {
	if x != nil {
		return x.CreateBy
	}
	return ""
}

func (x *AddSysMenuRequest) GetUpdateBy() string {
	if x != nil {
		return x.UpdateBy
	}
	return ""
}

func (x *AddSysMenuRequest) GetRemark() string {
	if x != nil {
		return x.Remark
	}
	return ""
}

type DeleteSysMenuRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Id            int64                  `protobuf:"varint,1,opt,name=id,proto3" json:"id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *DeleteSysMenuRequest) Reset() {
	*x = DeleteSysMenuRequest{}
	mi := &file_api_base_system_proto_msgTypes[4]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *DeleteSysMenuRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*DeleteSysMenuRequest) ProtoMessage() {}

func (x *DeleteSysMenuRequest) ProtoReflect() protoreflect.Message {
	mi := &file_api_base_system_proto_msgTypes[4]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use DeleteSysMenuRequest.ProtoReflect.Descriptor instead.
func (*DeleteSysMenuRequest) Descriptor() ([]byte, []int) {
	return file_api_base_system_proto_rawDescGZIP(), []int{4}
}

func (x *DeleteSysMenuRequest) GetId() int64 {
	if x != nil {
		return x.Id
	}
	return 0
}

type GetSysMenuRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Id            int64                  `protobuf:"varint,1,opt,name=id,proto3" json:"id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetSysMenuRequest) Reset() {
	*x = GetSysMenuRequest{}
	mi := &file_api_base_system_proto_msgTypes[5]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetSysMenuRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetSysMenuRequest) ProtoMessage() {}

func (x *GetSysMenuRequest) ProtoReflect() protoreflect.Message {
	mi := &file_api_base_system_proto_msgTypes[5]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetSysMenuRequest.ProtoReflect.Descriptor instead.
func (*GetSysMenuRequest) Descriptor() ([]byte, []int) {
	return file_api_base_system_proto_rawDescGZIP(), []int{5}
}

func (x *GetSysMenuRequest) GetId() int64 {
	if x != nil {
		return x.Id
	}
	return 0
}

type AllMenuReply struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Menus         []*MenuItem            `protobuf:"bytes,1,rep,name=menus,proto3" json:"menus,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *AllMenuReply) Reset() {
	*x = AllMenuReply{}
	mi := &file_api_base_system_proto_msgTypes[6]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *AllMenuReply) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*AllMenuReply) ProtoMessage() {}

func (x *AllMenuReply) ProtoReflect() protoreflect.Message {
	mi := &file_api_base_system_proto_msgTypes[6]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use AllMenuReply.ProtoReflect.Descriptor instead.
func (*AllMenuReply) Descriptor() ([]byte, []int) {
	return file_api_base_system_proto_rawDescGZIP(), []int{6}
}

func (x *AllMenuReply) GetMenus() []*MenuItem {
	if x != nil {
		return x.Menus
	}
	return nil
}

type MenuItem struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	MenuId        int64                  `protobuf:"varint,1,opt,name=menuId,proto3" json:"menuId,omitempty"`
	MenuName      string                 `protobuf:"bytes,2,opt,name=menuName,proto3" json:"menuName,omitempty"`
	ParentName    string                 `protobuf:"bytes,3,opt,name=parentName,proto3" json:"parentName,omitempty"`
	ParentId      int64                  `protobuf:"varint,4,opt,name=parentId,proto3" json:"parentId,omitempty"`
	OrderNum      int32                  `protobuf:"varint,5,opt,name=orderNum,proto3" json:"orderNum,omitempty"`
	Path          string                 `protobuf:"bytes,6,opt,name=path,proto3" json:"path,omitempty"`
	Component     string                 `protobuf:"bytes,7,opt,name=component,proto3" json:"component,omitempty"`
	Query         string                 `protobuf:"bytes,8,opt,name=query,proto3" json:"query,omitempty"`
	IsFrame       string                 `protobuf:"bytes,9,opt,name=isFrame,proto3" json:"isFrame,omitempty"`
	IsCache       string                 `protobuf:"bytes,10,opt,name=isCache,proto3" json:"isCache,omitempty"`
	MenuType      string                 `protobuf:"bytes,11,opt,name=menuType,proto3" json:"menuType,omitempty"`
	Visible       string                 `protobuf:"bytes,12,opt,name=visible,proto3" json:"visible,omitempty"`
	Status        string                 `protobuf:"bytes,13,opt,name=status,proto3" json:"status,omitempty"`
	Perms         string                 `protobuf:"bytes,14,opt,name=perms,proto3" json:"perms,omitempty"`
	Icon          string                 `protobuf:"bytes,15,opt,name=icon,proto3" json:"icon,omitempty"`
	Children      []*MenuItem            `protobuf:"bytes,16,rep,name=children,proto3" json:"children,omitempty"`
	CreateTime    string                 `protobuf:"bytes,17,opt,name=createTime,proto3" json:"createTime,omitempty"`
	UpdateTime    string                 `protobuf:"bytes,18,opt,name=updateTime,proto3" json:"updateTime,omitempty"`
	CreateBy      string                 `protobuf:"bytes,19,opt,name=createBy,proto3" json:"createBy,omitempty"`
	UpdateBy      string                 `protobuf:"bytes,20,opt,name=updateBy,proto3" json:"updateBy,omitempty"`
	Remark        string                 `protobuf:"bytes,21,opt,name=remark,proto3" json:"remark,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *MenuItem) Reset() {
	*x = MenuItem{}
	mi := &file_api_base_system_proto_msgTypes[7]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *MenuItem) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*MenuItem) ProtoMessage() {}

func (x *MenuItem) ProtoReflect() protoreflect.Message {
	mi := &file_api_base_system_proto_msgTypes[7]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use MenuItem.ProtoReflect.Descriptor instead.
func (*MenuItem) Descriptor() ([]byte, []int) {
	return file_api_base_system_proto_rawDescGZIP(), []int{7}
}

func (x *MenuItem) GetMenuId() int64 {
	if x != nil {
		return x.MenuId
	}
	return 0
}

func (x *MenuItem) GetMenuName() string {
	if x != nil {
		return x.MenuName
	}
	return ""
}

func (x *MenuItem) GetParentName() string {
	if x != nil {
		return x.ParentName
	}
	return ""
}

func (x *MenuItem) GetParentId() int64 {
	if x != nil {
		return x.ParentId
	}
	return 0
}

func (x *MenuItem) GetOrderNum() int32 {
	if x != nil {
		return x.OrderNum
	}
	return 0
}

func (x *MenuItem) GetPath() string {
	if x != nil {
		return x.Path
	}
	return ""
}

func (x *MenuItem) GetComponent() string {
	if x != nil {
		return x.Component
	}
	return ""
}

func (x *MenuItem) GetQuery() string {
	if x != nil {
		return x.Query
	}
	return ""
}

func (x *MenuItem) GetIsFrame() string {
	if x != nil {
		return x.IsFrame
	}
	return ""
}

func (x *MenuItem) GetIsCache() string {
	if x != nil {
		return x.IsCache
	}
	return ""
}

func (x *MenuItem) GetMenuType() string {
	if x != nil {
		return x.MenuType
	}
	return ""
}

func (x *MenuItem) GetVisible() string {
	if x != nil {
		return x.Visible
	}
	return ""
}

func (x *MenuItem) GetStatus() string {
	if x != nil {
		return x.Status
	}
	return ""
}

func (x *MenuItem) GetPerms() string {
	if x != nil {
		return x.Perms
	}
	return ""
}

func (x *MenuItem) GetIcon() string {
	if x != nil {
		return x.Icon
	}
	return ""
}

func (x *MenuItem) GetChildren() []*MenuItem {
	if x != nil {
		return x.Children
	}
	return nil
}

func (x *MenuItem) GetCreateTime() string {
	if x != nil {
		return x.CreateTime
	}
	return ""
}

func (x *MenuItem) GetUpdateTime() string {
	if x != nil {
		return x.UpdateTime
	}
	return ""
}

func (x *MenuItem) GetCreateBy() string {
	if x != nil {
		return x.CreateBy
	}
	return ""
}

func (x *MenuItem) GetUpdateBy() string {
	if x != nil {
		return x.UpdateBy
	}
	return ""
}

func (x *MenuItem) GetRemark() string {
	if x != nil {
		return x.Remark
	}
	return ""
}

var File_api_base_system_proto protoreflect.FileDescriptor

const file_api_base_system_proto_rawDesc = "" +
	"\n" +
	"\x15api/base/system.proto\x12\x04base\x1a\x1cgoogle/api/annotations.proto\x1a\x1bgoogle/protobuf/empty.proto\"+\n" +
	"\tMenuReply\x12\x1e\n" +
	"\x04menu\x18\x01 \x03(\v2\n" +
	".base.MenuR\x04menu\"b\n" +
	"\bMenuMeta\x12\x12\n" +
	"\x04icon\x18\x01 \x01(\tR\x04icon\x12\x12\n" +
	"\x04link\x18\x02 \x01(\tR\x04link\x12\x18\n" +
	"\anoCache\x18\x03 \x01(\bR\anoCache\x12\x14\n" +
	"\x05title\x18\x04 \x01(\tR\x05title\"\xae\x02\n" +
	"\x04Menu\x12\x1e\n" +
	"\n" +
	"alwaysShow\x18\x01 \x01(\bR\n" +
	"alwaysShow\x12&\n" +
	"\bchildren\x18\x02 \x03(\v2\n" +
	".base.MenuR\bchildren\x12\x1c\n" +
	"\tcomponent\x18\x03 \x01(\tR\tcomponent\x12\x16\n" +
	"\x06hidden\x18\x04 \x01(\bR\x06hidden\x12\"\n" +
	"\x04meta\x18\x05 \x01(\v2\x0e.base.MenuMetaR\x04meta\x12\x12\n" +
	"\x04name\x18\x06 \x01(\tR\x04name\x12\x12\n" +
	"\x04path\x18\a \x01(\tR\x04path\x12\x14\n" +
	"\x05query\x18\b \x01(\tR\x05query\x12\x1a\n" +
	"\bredirect\x18\t \x01(\tR\bredirect\x12\x0e\n" +
	"\x02id\x18\n" +
	" \x01(\x03R\x02id\x12\x1a\n" +
	"\bparentID\x18\v \x01(\x03R\bparentID\"\xcf\x04\n" +
	"\x11AddSysMenuRequest\x12\x16\n" +
	"\x06menuId\x18\x01 \x01(\x03R\x06menuId\x12\x1a\n" +
	"\bmenuName\x18\x02 \x01(\tR\bmenuName\x12\x1e\n" +
	"\n" +
	"parentName\x18\x03 \x01(\tR\n" +
	"parentName\x12\x1a\n" +
	"\bparentId\x18\x04 \x01(\x03R\bparentId\x12\x1a\n" +
	"\borderNum\x18\x05 \x01(\x05R\borderNum\x12\x12\n" +
	"\x04path\x18\x06 \x01(\tR\x04path\x12\x1c\n" +
	"\tcomponent\x18\a \x01(\tR\tcomponent\x12\x14\n" +
	"\x05query\x18\b \x01(\tR\x05query\x12\x18\n" +
	"\aisFrame\x18\t \x01(\tR\aisFrame\x12\x18\n" +
	"\aisCache\x18\n" +
	" \x01(\tR\aisCache\x12\x1a\n" +
	"\bmenuType\x18\v \x01(\tR\bmenuType\x12\x18\n" +
	"\avisible\x18\f \x01(\tR\avisible\x12\x16\n" +
	"\x06status\x18\r \x01(\tR\x06status\x12\x14\n" +
	"\x05perms\x18\x0e \x01(\tR\x05perms\x12\x12\n" +
	"\x04icon\x18\x0f \x01(\tR\x04icon\x12*\n" +
	"\bchildren\x18\x10 \x03(\v2\x0e.base.MenuItemR\bchildren\x12\x1e\n" +
	"\n" +
	"createTime\x18\x11 \x01(\tR\n" +
	"createTime\x12\x1e\n" +
	"\n" +
	"updateTime\x18\x12 \x01(\tR\n" +
	"updateTime\x12\x1a\n" +
	"\bcreateBy\x18\x13 \x01(\tR\bcreateBy\x12\x1a\n" +
	"\bupdateBy\x18\x14 \x01(\tR\bupdateBy\x12\x16\n" +
	"\x06remark\x18\x15 \x01(\tR\x06remark\"&\n" +
	"\x14DeleteSysMenuRequest\x12\x0e\n" +
	"\x02id\x18\x01 \x01(\x03R\x02id\"#\n" +
	"\x11GetSysMenuRequest\x12\x0e\n" +
	"\x02id\x18\x01 \x01(\x03R\x02id\"4\n" +
	"\fAllMenuReply\x12$\n" +
	"\x05menus\x18\x01 \x03(\v2\x0e.base.MenuItemR\x05menus\"\xc6\x04\n" +
	"\bMenuItem\x12\x16\n" +
	"\x06menuId\x18\x01 \x01(\x03R\x06menuId\x12\x1a\n" +
	"\bmenuName\x18\x02 \x01(\tR\bmenuName\x12\x1e\n" +
	"\n" +
	"parentName\x18\x03 \x01(\tR\n" +
	"parentName\x12\x1a\n" +
	"\bparentId\x18\x04 \x01(\x03R\bparentId\x12\x1a\n" +
	"\borderNum\x18\x05 \x01(\x05R\borderNum\x12\x12\n" +
	"\x04path\x18\x06 \x01(\tR\x04path\x12\x1c\n" +
	"\tcomponent\x18\a \x01(\tR\tcomponent\x12\x14\n" +
	"\x05query\x18\b \x01(\tR\x05query\x12\x18\n" +
	"\aisFrame\x18\t \x01(\tR\aisFrame\x12\x18\n" +
	"\aisCache\x18\n" +
	" \x01(\tR\aisCache\x12\x1a\n" +
	"\bmenuType\x18\v \x01(\tR\bmenuType\x12\x18\n" +
	"\avisible\x18\f \x01(\tR\avisible\x12\x16\n" +
	"\x06status\x18\r \x01(\tR\x06status\x12\x14\n" +
	"\x05perms\x18\x0e \x01(\tR\x05perms\x12\x12\n" +
	"\x04icon\x18\x0f \x01(\tR\x04icon\x12*\n" +
	"\bchildren\x18\x10 \x03(\v2\x0e.base.MenuItemR\bchildren\x12\x1e\n" +
	"\n" +
	"createTime\x18\x11 \x01(\tR\n" +
	"createTime\x12\x1e\n" +
	"\n" +
	"updateTime\x18\x12 \x01(\tR\n" +
	"updateTime\x12\x1a\n" +
	"\bcreateBy\x18\x13 \x01(\tR\bcreateBy\x12\x1a\n" +
	"\bupdateBy\x18\x14 \x01(\tR\bupdateBy\x12\x16\n" +
	"\x06remark\x18\x15 \x01(\tR\x06remark2\x86\x04\n" +
	"\x06System\x12E\n" +
	"\x04Menu\x12\x16.google.protobuf.Empty\x1a\x0f.base.MenuReply\"\x14\x82\xd3\xe4\x93\x02\x0e\x12\f/system/menu\x12P\n" +
	"\aAllMenu\x12\x16.google.protobuf.Empty\x1a\x12.base.AllMenuReply\"\x19\x82\xd3\xe4\x93\x02\x13\x12\x11/system/menu/list\x12V\n" +
	"\n" +
	"AddSysMenu\x12\x17.base.AddSysMenuRequest\x1a\x16.google.protobuf.Empty\"\x17\x82\xd3\xe4\x93\x02\x11:\x01*\"\f/system/menu\x12Y\n" +
	"\rUpdateSysMenu\x12\x17.base.AddSysMenuRequest\x1a\x16.google.protobuf.Empty\"\x17\x82\xd3\xe4\x93\x02\x11:\x01*\x1a\f/system/menu\x12^\n" +
	"\rDeleteSysMenu\x12\x1a.base.DeleteSysMenuRequest\x1a\x16.google.protobuf.Empty\"\x19\x82\xd3\xe4\x93\x02\x13*\x11/system/menu/{id}\x12P\n" +
	"\n" +
	"GetSysMenu\x12\x17.base.GetSysMenuRequest\x1a\x0e.base.MenuItem\"\x19\x82\xd3\xe4\x93\x02\x13\x12\x11/system/menu/{id}BN\n" +
	"\x13dev.kratos.api.baseB\tBaseProtoP\x01Z*github.com/example/aichat/backend/api;baseb\x06proto3"

var (
	file_api_base_system_proto_rawDescOnce sync.Once
	file_api_base_system_proto_rawDescData []byte
)

func file_api_base_system_proto_rawDescGZIP() []byte {
	file_api_base_system_proto_rawDescOnce.Do(func() {
		file_api_base_system_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_api_base_system_proto_rawDesc), len(file_api_base_system_proto_rawDesc)))
	})
	return file_api_base_system_proto_rawDescData
}

var file_api_base_system_proto_msgTypes = make([]protoimpl.MessageInfo, 8)
var file_api_base_system_proto_goTypes = []any{
	(*MenuReply)(nil),            // 0: base.MenuReply
	(*MenuMeta)(nil),             // 1: base.MenuMeta
	(*Menu)(nil),                 // 2: base.Menu
	(*AddSysMenuRequest)(nil),    // 3: base.AddSysMenuRequest
	(*DeleteSysMenuRequest)(nil), // 4: base.DeleteSysMenuRequest
	(*GetSysMenuRequest)(nil),    // 5: base.GetSysMenuRequest
	(*AllMenuReply)(nil),         // 6: base.AllMenuReply
	(*MenuItem)(nil),             // 7: base.MenuItem
	(*emptypb.Empty)(nil),        // 8: google.protobuf.Empty
}
var file_api_base_system_proto_depIdxs = []int32{
	2,  // 0: base.MenuReply.menu:type_name -> base.Menu
	2,  // 1: base.Menu.children:type_name -> base.Menu
	1,  // 2: base.Menu.meta:type_name -> base.MenuMeta
	7,  // 3: base.AddSysMenuRequest.children:type_name -> base.MenuItem
	7,  // 4: base.AllMenuReply.menus:type_name -> base.MenuItem
	7,  // 5: base.MenuItem.children:type_name -> base.MenuItem
	8,  // 6: base.System.Menu:input_type -> google.protobuf.Empty
	8,  // 7: base.System.AllMenu:input_type -> google.protobuf.Empty
	3,  // 8: base.System.AddSysMenu:input_type -> base.AddSysMenuRequest
	3,  // 9: base.System.UpdateSysMenu:input_type -> base.AddSysMenuRequest
	4,  // 10: base.System.DeleteSysMenu:input_type -> base.DeleteSysMenuRequest
	5,  // 11: base.System.GetSysMenu:input_type -> base.GetSysMenuRequest
	0,  // 12: base.System.Menu:output_type -> base.MenuReply
	6,  // 13: base.System.AllMenu:output_type -> base.AllMenuReply
	8,  // 14: base.System.AddSysMenu:output_type -> google.protobuf.Empty
	8,  // 15: base.System.UpdateSysMenu:output_type -> google.protobuf.Empty
	8,  // 16: base.System.DeleteSysMenu:output_type -> google.protobuf.Empty
	7,  // 17: base.System.GetSysMenu:output_type -> base.MenuItem
	12, // [12:18] is the sub-list for method output_type
	6,  // [6:12] is the sub-list for method input_type
	6,  // [6:6] is the sub-list for extension type_name
	6,  // [6:6] is the sub-list for extension extendee
	0,  // [0:6] is the sub-list for field type_name
}

func init() { file_api_base_system_proto_init() }
func file_api_base_system_proto_init() {
	if File_api_base_system_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_api_base_system_proto_rawDesc), len(file_api_base_system_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   8,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_api_base_system_proto_goTypes,
		DependencyIndexes: file_api_base_system_proto_depIdxs,
		MessageInfos:      file_api_base_system_proto_msgTypes,
	}.Build()
	File_api_base_system_proto = out.File
	file_api_base_system_proto_goTypes = nil
	file_api_base_system_proto_depIdxs = nil
}
