server:
  http:
    addr: 0.0.0.0:6039
    timeout: 1000s
  grpc:
    addr: 0.0.0.0:9000
    timeout: 1000s
data:
  database:
    driver: mysql
    source: read_rentianhua:yNxruv24C26@tcp(rm-bp1hw1ynxruv24c26jo.mysql.rds.aliyuncs.com:3306)/rth?parseTime=True&loc=Local
  pg_database:
    host: sshjd.aihelper.chat
    port: 30532
    user: pgadmin
    password: "pgcj123456"
    dbname: pgdb
    sslmode: disable
  redis:
    addr: sshjd.aihelper.chat:30379
    read_timeout: 0.2s
    write_timeout: 0.2s
    password: "rediscj123456"

log:
  maxAge: 30
  level: "debug"
  format: "console"
  director: "./logs"
  encodeLevel: "CapitalColorLevelEncoder"

auth:
  qq:
    app_id: ""
    app_key: ""
    callback_url: ""
    frontend_redirect: "http://localhost:5173/chat"
    scope: "get_user_info"

# TODO minio 配置
oss:
  access_key: "7ns5yiCMFgN5rdZbkJnW"
  secret_key: "4GV4kNFqonmgFNlTkLMfK6R7ChCP4a63TFMIqHIx"