server:
  http:
    addr: 0.0.0.0:6039
    timeout: 1s
  grpc:
    addr: 0.0.0.0:9000
    timeout: 1s
data:
  database:
    driver: mysql
    source: read_rentianhua:yNxruv24C26@tcp(rm-bp1hw1ynxruv24c26jo.mysql.rds.aliyuncs.com:3306)/rth?parseTime=True&loc=Local
  pg_database:
    host: 115.120.248.67
    port: 31042
    user: pgadmin
    password: "123456"
    dbname: pgdb
    sslmode: disable
  redis:
    addr: 127.0.0.1:6379
    read_timeout: 0.2s
    write_timeout: 0.2s

log:
  maxAge: 30
  level: "debug"
  format: "console"
  director: "./logs"
  encodeLevel: "CapitalColorLevelEncoder"

